### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by poopingpenis** [bs-community/blessing-skin-server#101]
I translated the website to Spanish: https://crowdin.com/project/bs-i18n/es-ES

I don't think I should worry about the licence since GNU doesn't consider translations valid anyway, though.

**Comment by g-plane** [comment]
First, thanks for your participation!

However, language files at Crowdin are too old and need to be updated. Would you mind waiting? You can also translate them directly at this repository if you can wait for us, and files are at `resources/lang`.

Also, since v4, we re-licensed the code to MIT, so you don't need to worry about the license.

**Comment by poopingpenis** [comment]
I'd rather wait, as otherwise I'd need to manually copy paste or re-translate everything I've done already. But, if you can't update the Crowdin files I could do it, it would just take me a while.

**Comment by g-plane** [comment]
I will update Crowdin as soon as possible.

**Comment by poopingpenis** [comment]
Thank you, I'll look forward to it :)

**Comment by g-plane** [comment]
Welcome to translating here: https://crowdin.com/project/blessing-skin/ .

**Comment by poopingpenis** [comment]
Alright, thanks! Since it's a new project I'd have to copy things over so I'll try to do it sometime this week since I have some school work to do this weekend, but I'll get it done soon

**Comment by g-plane** [comment]
No problem!

**Comment by poopingpenis** [comment]
I finished with all of it :)

**Comment by g-plane** [comment]
Thank you very much!

**Comment by tnqzh123** [comment]
Great! You did a really nice job. Thank you!

However, could you please commit some translation to some plugins in [bs-community/blessing-skin-plugins](https://github.com/bs-community/blessing-skin-plugins)? This is our official plugin repository, but it isn't listed on Crowdin so you have to open a Pull Request to this repository manually to push the files.

Anyway, whether you will help us translate the plugins or not, we do apperaciate your contributions! Thank you!

> Sorry for my bad Engish XD

**Comment by poopingpenis** [comment]
Hey, no worries, your English is great.

I checked the link and went through the plugins but I don't see any lang folders inside any of them. 🤔

Am I missing something?

**Comment by tnqzh123** [comment]
@poopingpenis 
> Hey, no worries, your English is great.
> 
> I checked the link and went through the plugins but I don't see any lang folders inside any of them. 
> 
> Am I missing something?

The language files is under `{plugin name}/lang/{language code}`. For example, the English language files of `mojang-verification` plugin is under `mojang-verification/lang/en/`. Both `locale.js` and the YAML files are language files, their contents are different. For more information, please take a look at our [document](https://bs-plugin.netlify.com/guide/i18n.html) (only available in Simplified Chinese, sorry)

Some plugins don't display texts (e.g. `refresh-qcloud-cdn`), so they have no `lang` directory.

**Comment by poopingpenis** [comment]
@tnqzh123 Aha, I see, thank you! I will translate what I can soon

**Comment by g-plane** [comment]
@poopingpenis There're new strings added to Crowdin. Can you translate them? Thanks.

**Comment by g-plane** [comment]
Closing because there's no need to keep this open, but any discussions are still allowed.
