### ISSUE TITLE
css以及js丢失

### ISSUE THREAD

**Issue by longyup** [bs-community/blessing-skin-server#104]
/index.php的css以及js丢失，/setup安装成功了
- Blessing Skin 版本 (Version of Blessing Skin):4.4
- PHP 版本 (Version of PHP): 7.2
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version):Nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): chrome, http://139.9.119.190/index.php
控制台显示
GET http://139.9.119.190/index.php/app/style.f84dc57.css net::ERR_ABORTED 404 (Not Found)

**Comment by g-plane** [comment]
不应该以 `index.php` 形式的后缀去访问皮肤站。

**Comment by longyup** [comment]
如果直接访问ip，显示403 Forbidden

**Comment by g-plane** [comment]
那是你的配置问题。请先认真阅读「安装指南」。

**Comment by tnqzh123** [comment]
长时间未回复，Close。

如有需要，请 Reopen 并附上更多内容。
