### ISSUE TITLE
app_key生成问题

### ISSUE THREAD

**Issue by xiao-k233** [bs-community/blessing-skin-server#108]
## The Problem 问题描述
在我生成app_key时，失败了！

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):4.4.0
- PHP 版本 (Version of PHP):7.3
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version):Nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):

## Error Message 错误信息

Could not open input file: artisan

## Steps to Reproduce 重现步骤
ssh执行php artisan key:generate
然后报错Could not open input file: artisan

**Comment by g-plane** [comment]
1. https://blessing.netlify.com/setup.html
2. https://blessing.netlify.com/faq.html
