### ISSUE TITLE
更新插件时不检查插件需求

### ISSUE THREAD

**Issue by hempflower** [bs-community/blessing-skin-server#109]
## The Problem 问题描述
点击更新插件按钮后，皮肤站会将旧版插件文件替换为最新版插件文件，但无法启用（启用时有依赖检查）。

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):v4.3.6
- PHP 版本 (Version of PHP):7.2
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version):nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):https://mcskin.cn/admin/plugins/market

## Error Message 错误信息
![image](https://user-images.githubusercontent.com/22955496/70407696-4f7dc500-1a80-11ea-817a-ea06cfdf6646.png)

## Steps to Reproduce 重现步骤
1. 皮肤站上安装有旧版本插件并且皮肤站不满足新版本插件要求（如v5插件）
2. 点击对应的更新按钮
3. 待下载完成后，会有启用按钮
4. 无法启用插件，因为皮肤站不满足依赖要求。

(回滚插件去了....)

**Comment by g-plane** [comment]
这是当初插件市场设计得不够完善。

由此带来的不便，在此表示歉意。如果需要旧的插件，可以从 [这里](https://dev.azure.com/blessing-skin/_git/Plugins) 下载。
