### ISSUE TITLE
无法使用Sendmail发送邮件

### ISSUE THREAD

**Issue by hank9999** [bs-community/blessing-skin-server#118]
## The Problem 问题描述
找回密码时无法发送邮件（使用Sendmail）

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): v4.4.0
- PHP 版本 (Version of PHP):  PHP7.3.11
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version): Nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):  /auth/forgot

## Error Message 错误信息
邮件发送失败，详细信息：Address in mailbox given [] does not comply with RFC 2822, 3.6.2.
已反复核查邮件地址
已确认Sendmail可以正常发送邮件
![1577014023(1)](https://user-images.githubusercontent.com/20784591/71321294-77464180-24f2-11ea-9faa-ddc623b64e36.jpg)

Sendmail正常工作证明：
![4444](https://user-images.githubusercontent.com/20784591/71321370-44e91400-24f3-11ea-8922-bbef2f0357af.png)

## Steps to Reproduce 重现步骤
在.env中配置mail为sendmail
![( BZPGY2YOHU_3T TGH3S41](https://user-images.githubusercontent.com/20784591/71321337-de63f600-24f2-11ea-9bdb-0313bf6c7d4c.png)
然后进行找回密码操作

log:
[laravel (1).log](https://github.com/bs-community/blessing-skin-server/files/3992395/laravel.1.log)

**Comment by g-plane** [comment]
寄件人的地址有没有正确填写？

**Comment by hank9999** [comment]
> 寄件人的地址有没有正确填写？

已多次确认，且使用smtp可以正常发送

**Comment by g-plane** [comment]
但是这个错误一般是由于 `MAIL_USERNAME` 没有正确填写引起的。

**Comment by hank9999** [comment]
> 但是这个错误一般是由于 `MAIL_USERNAME` 没有正确填写引起的。

地址确实没有错误
令人费解

**Comment by g-plane** [comment]
也不排除是 Laravel 的验证不正确，但似乎没有看到 changelog 中有相关的 bug 修复说明。

**Comment by hank9999** [comment]
> 也不排除是 Laravel 的验证不正确，但似乎没有看到 changelog 中有相关的 bug 修复说明。

[Laravel发送邮件报错](https://segmentfault.com/q/1010000008793944/a-1020000008794305)
这个可否参考一下？

**Comment by g-plane** [comment]
你试试在前面加个 `"From:"` 看看？如果可以，我去修复这个问题。

**Comment by hank9999** [comment]
> 你试试在前面加个 `"From:"` 看看？如果可以，我去修复这个问题。

好吧，不行
网上说的特殊字符也不是
![O%}X0S0446_`%~X32TAF}06](https://user-images.githubusercontent.com/20784591/71323387-65be6300-250d-11ea-9872-e71cd5fc5124.png)

也许要去求助google了

**Comment by g-plane** [comment]
难道你的邮件地址中包含特殊字符？

**Comment by hank9999** [comment]
> 难道你的邮件地址中包含特殊字符？

![7C$}T@ZOH N SGRF9$8~R{8](https://user-images.githubusercontent.com/20784591/71323411-b46bfd00-250d-11ea-9371-2d4e5b5afad1.png)
![O%}X0S0446_`%~X32TAF}06](https://user-images.githubusercontent.com/20784591/71323416-b766ed80-250d-11ea-8964-3690903dd584.png)

**Comment by g-plane** [comment]
你能先手动改源码试试吗？

**Comment by hank9999** [comment]
> 你能先手动改源码试试吗？

正在尝试

**Comment by g-plane** [comment]
有进展吗？

**Comment by hank9999** [comment]
> 有进展吗？

还没有，还在研究

**Comment by hank9999** [comment]
> 有进展吗？

算了，用smtp绕一圈吧
