### ISSUE TITLE
无法在PHP7.4环境下正常运行

### ISSUE THREAD

**Issue by hank9999** [bs-community/blessing-skin-server#122]
## The Problem 问题描述

无法在PHP7.4环境下正常运行

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):  v4.4.0
- PHP 版本 (Version of PHP):  PHP 7.4.1
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version):  Nginx 1.17
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):  /setup/finish || /csl/xx.json || /xx.json || /usm/xx.json

## Error Message 错误信息
500 Internal Server Error
Trying to access array offset on value of type null

## Steps to Reproduce 重现步骤
在PHP7.4.1环境下重新安装
（PHP7.3安装后切换到7.4后，无法获取皮肤）

![R0D9(8VP1YN I4 2VRLS$EL](https://user-images.githubusercontent.com/20784591/71553247-2630d300-2a47-11ea-96d7-e50d1c3209b8.png)
[log.log](https://github.com/bs-community/blessing-skin-server/files/4007823/log.log)
[Debug_infog.pdf](https://github.com/bs-community/blessing-skin-server/files/4007825/Debug_infog.pdf)

**Comment by g-plane** [comment]
已在 v5 中修复。
