### ISSUE TITLE
邮箱验证功能怎么用?

### ISSUE THREAD

**Issue by koiNoCirculation** [bs-community/blessing-skin-server#128]
既然是邮箱验证,肯定要发邮件
但是为什么我没有找到任何SMTP/POP3的配置入口?
如果确实有,那怎么做呢?
使用4.4.0

**Comment by 2810676203** [comment]
在配置文件里设置的哦

**Comment by 2810676203** [comment]
`MAIL_DRIVER = smtp`
`MAIL_HOST = 服务器地址`
`MAIL_PORT = 端口`
`MAIL_USERNAME = 账号`
`MAIL_PASSWORD = 密码`
`MAIL_ENCRYPTION = ssl`
大概就是这样

**Comment by g-plane** [comment]
请阅读手册：https://blessing.netlify.com/env.html#%E9%82%AE%E4%BB%B6%E7%9B%B8%E5%85%B3 。
