### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by WC12366** [bs-community/blessing-skin-server#129]
## The Problem 问题描述
安装信息填写后点击完成出现500错误

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):5.0.3
- PHP 版本 (Version of PHP):7.4.2
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version):nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):localhost/setup/finish

## Error Message 错误信息

500 Internal Server Error
详细信息：Use of undefined constant STDIN - assumed 'STDIN' (this will throw an Error in a future version of PHP)

## Steps to Reproduce 重现步骤
打开安装地址
填写信息
点击 完成 按钮

**Comment by g-plane** [comment]
在另分支已修复。
