### ISSUE TITLE
上传材质时，若皮肤库内已有相同材质，跳转时不会提示用户

### ISSUE THREAD

**Issue by tnqzh123** [bs-community/blessing-skin-server#132]
## The Problem 问题描述

上传新材质时，若皮肤库内已有相同材质，BS 会直接跳转到对应的材质详情页面，但跳转前后均没有对应提示（`skinlib.upload.repeated`）。

_另请参阅：#133_

## Environment 运行环境

- Blessing Skin 版本：开发版 `f721ac2`
- PHP 版本：7.2.24
- Web 服务器：Nginx
- 浏览器：Microsoft Edge 80.0.361.57

## Error Message 错误信息

无。laravel.log 和 Console 中均无输出错误。

## Steps to Reproduce 重现步骤

上传一份已经存在于皮肤库中的完全相同的材质。

**Comment by tnqzh123** [comment]
欸？#133 并没有解决这个 Issue 才对…

**Comment by g-plane** [comment]
Sorry.
