### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by xiao-k233** [bs-community/blessing-skin-server#136]
## The Problem 问题描述
我在安装时，填写了数据库信息，我确认肯定我的信息没填错，而且网站目录下全部文件为777权限（包括所有子目录）

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):4.4.0
- PHP 版本 (Version of PHP):7.3.15
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version):Apache
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):chrome78,/setup/database

## Error Message 错误信息
![image](https://user-images.githubusercontent.com/58621432/75416959-c7b2a300-596a-11ea-87f9-64ea0c37e66f.png)
file_put_contents(/www/wwwroot/mine233.tpddns.cn/.env): failed to open stream: Permission denied

## Steps to Reproduce 重现步骤
1.打开安装页面
2.输入完数据库信息
3.出现本页面

**Comment by tnqzh123** [comment]
**不要指定 777 权限。**

你应该将皮肤站根目录的所有者设为 Web 引擎的用户。

```bash
cd /path/to/bs
chown -hR user ./*
```

其中 `path` 为你的皮肤站根目录的路径，`user` 为你的 Web 引擎的用户。

**Comment by xiao-k233** [comment]
[root@localhost mine233.tpddns.cn]# chown -hR www ./*
chown: 正在更改'./public/.user.ini' 的所有者: 不允许的操作
出现这种情况

**Comment by Asnxthaony** [comment]
> [root@localhost mine233.tpddns.cn]# chown -hR www ./*
> chown: 正在更改'./public/.user.ini' 的所有者: 不允许的操作
> 出现这种情况

**请忽视这个文件**

你似乎在使用某面板，如果你使用 `lsattr .user.ini` 查看这个文件的属性时，会看到如下内容：
`
----i----------- .user.ini
`
拥有 immutable(i) 属性的文件或文件夹不可被修改。

**Comment by xiao-k233** [comment]
@Asnxthaony 确实，我在使用宝塔面板，请问有什么办法吗？

**Comment by tnqzh123** [comment]
@xiao-k233
> 确实，我在使用宝塔面板，请问有什么办法吗？

Just ignore it. 这个文件应该不会对 Blessing Skin 的正常运作造成影响。

**Comment by xiao-k233** [comment]
@tnqzh123 那，请问，如何解决这个问题？

**Comment by tnqzh123** [comment]
@xiao-k233
> 那，请问，如何解决这个问题？

不需要解决。其他文件的权限设置完成了就可以了。

如果真的看这个问题不爽，想要解决它，那我建议你放弃宝塔面板。

> **宝 塔 是 垃 圾**

**Comment by xiao-k233** [comment]
@tnqzh123 我其他的文件都已设置完毕，可是还有这个问题，网页刷新了。

**Comment by xiao-k233** [comment]
我直接编辑.env配置文件可以么？

**Comment by xiao-k233** [comment]
> 我直接编辑.env配置文件可以么？

![image](https://user-images.githubusercontent.com/58621432/75419108-131b8000-5970-11ea-9256-0706828c2db4.png)
于是。。。。。我太难了

**Comment by tnqzh123** [comment]
建议删整站，重新来过。

根据我的经验，可能是你设置的 777 权限出了问题。

**Comment by xiao-k233** [comment]
> 建议删整站，重新来过。
> 
> 根据我的经验，可能是你设置的 777 权限出了问题。

我使用chmod -Rf 777 *  来设置777权限

**Comment by tnqzh123** [comment]
@xiao-k233 
>我使用chmod -Rf 777 * 来设置777权限

https://askubuntu.com/questions/812513/permission-denied-in-777-folder

**Comment by xiao-k233** [comment]
> @xiao-k233
> 
> > 我使用chmod -Rf 777 * 来设置777权限
> 
> https://askubuntu.com/questions/812513/permission-denied-in-777-folder
> 
> 再次建议放弃宝塔。

好了，根据链接里的方法
md
