### ISSUE TITLE
无法上传

### ISSUE THREAD

**Issue by xiao-k233** [bs-community/blessing-skin-server#137]
## The Problem 问题描述

Missing a temporary folder上传时出现这个报错！emmmmm，我裂开了

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):4.4.0
- PHP 版本 (Version of PHP):7.3.15
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version):Nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):

## Error Message 错误信息

Missing a temporary folder
![image](https://user-images.githubusercontent.com/58621432/75421683-c6d33e80-5975-11ea-8379-805f7a11742b.png)

## Steps to Reproduce 重现步骤
普通的上传

**Comment by tnqzh123** [comment]
STFW, GIYF.

https://stackoverflow.com/questions/14235871/missing-a-temporary-folder

**Comment by g-plane** [comment]
这是你的运行环境的问题，不是 Blessing Skin 的问题。
