### ISSUE TITLE
Relicense

### ISSUE THREAD

**Issue by g-plane** [bs-community/blessing-skin-server#14]
虽然可能没什么意义，不过还是值得提一提。

@printempw 现在应该不会活跃参与开发此项目了，所以我希望这个项目能在 license 上有所放松，我觉得 MIT 或 Apache License 2.0 就不错。

不知道各位有什么看法？如果大家还是更喜欢 GPL，那我也是不介意的。

**Comment by printempw** [comment]
我无意见。

**Comment by yushijinhun** [comment]
我认为应该保持GPL。

**Comment by tnqzh123** [comment]
我没有意见，但是考虑到 Apache License 需要在每个修改过的文件中添加说明的繁琐，我觉得 MIT 协议更合适。
不过相比起这个，我们是不是应该先考虑怎么防止用户私自移除站点中的版权说明文本(

**Comment by yushijinhun** [comment]
> 不过相比起这个，我们是不是应该先考虑怎么防止用户私自移除站点中的版权说明文本

据我所知，如果使用MIT协议，用户没有义务保留版权说明。但如果使用GPLv3，这可以被视为Section 7中的附加条款，是有法律效力的：
```
...
    b) Requiring preservation of specified reasonable legal notices or
    author attributions in that material or in the Appropriate Legal
    Notices displayed by works containing it; or
...
```

**Comment by g-plane** [comment]
实际上，私自移除站点中的版权说明文本是国内一部分人的作为，但不是大多数。另外，在这种环境下，更多是一种约束，没法强制。 @printempw 以前就说过，他更多地只是把这视为君子条款，没法控制小人行为。

**Comment by g-plane** [comment]
另外，源码可以与编译成品使用不同的 license，参考 VS Code（二进制版本的 VS Code 不是开源的）。

**Comment by yushijinhun** [comment]
我想问使用MIT而不是GPL对谁有好处？

如果这是个类库，MIT许可会给使用这个类库的人带来方便，因为他们可以决定自己的程序是开源还是闭源。只要你不是一个极端的GNU信徒，我觉得自己的类库被别人的闭源软件使用是可以接受的。这种情况下我支持用MIT。

但如果这是个应用程序，MIT许可会给那些修改了这个软件并且想把代码闭源的人带来方便。我不知你是否能容忍这种行为，至少我是不能，所以我选择GPL。

**Comment by g-plane** [comment]
我不反对用户将 BS 闭源。

**Comment by g-plane** [comment]
在保留版权的前提下，我欢迎任何用户自行对 BS 作出任意的修改。

**Comment by g-plane** [comment]
@xfl03 @lzjluzijie @timgiroux 同意允许将这个项目的 license 改为 MIT 吗？

**Comment by lzjluzijie** [comment]
可以啊

**Comment by tnqzh123** [comment]
@yushijinhun 那是否可以在 MIT 协议之下，添加一条附加条款，声明不得移除站点中的版权说明文本？
@g-plane 我觉得，目前来看，编译成品和源码使用不同的 License 没有什么意义，因为 BS 当前的分发的预编译的压缩包除了依赖和编译后的前端文件之外，和 Git 上的源码没有什么差别。

**Comment by lzjluzijie** [comment]
![image](https://user-images.githubusercontent.com/7992620/54207544-4e316300-4515-11e9-8c26-3fea680bbf48.png)

**Comment by tnqzh123** [comment]
@lzjluzhujie 这条是适用于再分发的吧？
我指的是，部分使用 BS 的皮肤站的站长私自移除了本不允许移除的页面底部的版权说明文本（但没有分发修改后的版本）。

**Comment by lzjluzijie** [comment]
@tnqzh123 有道理，GPL说的更明白吧（虽然我觉得国内这情况啥License都没用

**Comment by g-plane** [comment]
我以后大概会想办法通过一些技术方法来 *尽量* 阻止直接对发行版 BS 的版权信息进行修改。
即，从 GitHub clone 下来的源码可以任意修改，不会受影响；但如果对 release 包进行去除版权信息操作则阻止。

**Comment by xfl03** [comment]
我觉得用户对代码的任何修改都是可以接受的，即使不开源也是勉强可以的，这一点我支持MIT。
但是我不能容忍用户对二进制的release随意修改，这一点偏向于GPL。

**Comment by yushijinhun** [comment]
> 即，从 GitHub clone 下来的源码可以任意修改，不会受影响；但如果对 release 包进行去除版权信息操作则阻止。

那请问如果用户下载了源代码，移除了版权信息，自己再打包，是否违反协议呢？自己打的包和官方的release包能分辨出差别吗？所以我觉得对官方发布的release包加附加条件是毫无意义的。

既然选择了MIT，那么就用户就被赋予了MIT协议中所规定的权利。这时候如果再加任何附加条件，都会导致BS变成**非MIT协议的软件**。

**Comment by g-plane** [comment]
@timgiroux Do you mind us relicensing this project to MIT License?

**Comment by g-plane** [comment]
Friendly ping @timgiroux

**Comment by g-plane** [comment]
考虑到长时间未收到 @timgiroux 的回复，我决定移除 @timgiroux 的 work 再进行 relicense，大概会在「材质举报」功能完成后进行。
