### ISSUE TITLE
authme对接

### ISSUE THREAD

**Issue by Yuii-guoguo** [bs-community/blessing-skin-server#140]
#123  The Problem 问题描述
authme对接环境配置好后更改密码对网站无效，游戏生效了,疑似网站登录注册的算法没有变更.
## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):4.4.0
- PHP 版本 (Version of PHP):7.3
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version):nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):
chrome,https://skin.guoguokm.com/auth/login

## Error Message 错误信息
登录错误
## Steps to Reproduce 重现步骤
新安装网站和authme数据对接，修改.env文件的PWD_METHOD为SHA256进行登录

**Comment by g-plane** [comment]
本仓库不处理数据对接相关的问题。请移步到插件仓库提问题。
