### ISSUE TITLE
找回密码的邮箱验证功能失效

### ISSUE THREAD

**Issue by Yuii-guoguo** [bs-community/blessing-skin-server#141]
## The Problem 问题描述
点击邮箱链接显示403，Invalid signature.
## Environment 运行环境
- Blessing Skin 版本 (Version of Blessing Skin):4.4.0
- PHP 版本 (Version of PHP):7.3
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version):nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):
chrome
## Error Message 错误信息
403 Forbidden 详细信息:Invalid signature
## Steps to Reproduce 重现步骤
找回密码，获取邮箱链接，打开即可显示403

**Comment by g-plane** [comment]
https://github.com/bs-community/blessing-skin-server/issues/75 中有类似情况，但没有解决方法。

**Comment by g-plane** [comment]
我在 Laravel 的 issues 列表也没找到解决方法，我们也不清楚具体是什么原因引起的。

**Comment by g-plane** [comment]
此问题已在 v5 中尝试进行修复。
