### ISSUE TITLE
bs4.x中涉及到Azure的网址可能已经失效

### ISSUE THREAD

**Issue by Windelight** [bs-community/blessing-skin-server#143]
## The Problem 问题描述

RT

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): v4.4.0
- PHP 版本 (Version of PHP): 7.3.14
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version): Apache 2.4.38
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): https://some-urls/admin/update

## Error Message 错误信息

无法访问当前更新源。详细信息：Client error: `GET https://dev.azure.com/blessing-skin/51010f6d-9f99-40f1-a262-0a67f788df32/_apis/git/repositories/a9ff8df7-6dc3-4ff8-bb22-4871d3a43936/Items?path=%2Fupdate_2.json` resulted in a `404 Not Found` response: {"$id":"1","innerException":null,"message":"TF401174: The item 'update_2.json' could not be found in the repository 'Ble (truncated...)

## Steps to Reproduce 重现步骤

后台-检查更新

挎弧，包括Release页面中的Azure网址也已经失效了

**Comment by Asnxthaony** [comment]
安装 「使用预览版」 插件来切换更新源到预览版。

**Comment by g-plane** [comment]
这个不用担心。因为下个版本将会是 v5，即 v4 不再更新，到时我们会恢复。
