### ISSUE TITLE
建议：在用户注册完毕后，弹出一个服务条款（新人指南/用户手册）

### ISSUE THREAD

**Issue by jinzhijie** [bs-community/blessing-skin-server#145]
建议：在用户注册完毕后，弹出一个服务条款（新人指南/用户手册）。
建议设置为可选选项：在网页中使用`<iframe>`加载由皮肤站自定义的页面，例如用户手册。用户可选择跳过。
（星际玩家实在太多了

**Comment by g-plane** [comment]
我觉得这个用插件应该就可以？

**Comment by jinzhijie** [comment]
哪个插件呢？
或者是写一个？

**Comment by g-plane** [comment]
自己写一个吧。
