### ISSUE TITLE
更新到开发版材质全部失效。

### ISSUE THREAD

**Issue by zhzRedstone** [bs-community/blessing-skin-server#147]
## The Problem 问题描述
更新到开发版材质全部失效。

## Environment 运行环境

Blessing Skin
--
版本 | 5.0.0-beta.3
应用环境 | production
是否处于调试状态 | Yes
提交 | 59f8f33df7d39ff2
Laravel 版本 | 7.0.8

PHP 版本 | 7.3.5
Web 服务软件 | nginx/1.14.2
操作系统 | Linux 3.10.0-514.26.2.el7.x86_64 x86_64

## Error Message 错误信息

![image](https://user-images.githubusercontent.com/39423408/76389388-0d795d80-63a6-11ea-811c-9b442e20383a.png)
![image](https://user-images.githubusercontent.com/39423408/76389408-1e29d380-63a6-11ea-9678-bad4f504fa97.png)

## Steps to Reproduce 重现步骤
从5.0 beta3 laravel6.9 替换文件为最新开发版的。重新登录，进入皮肤库，材质图片全不见

**Comment by g-plane** [comment]
环境问题。

**Comment by zhzRedstone** [comment]
注释.env下的 TEXTURES_DIR = null 配置项解决。
