### ISSUE TITLE
我的衣柜alex材质预览问题。

### ISSUE THREAD

**Issue by zhzRedstone** [bs-community/blessing-skin-server#152]
## 问题描述
在上传alex皮肤到我的衣柜预览时，预览模型不是alex模型而是steve模型，

## 运行环境

Blessing Skin
--
版本 | 5.0.0-beta.5
应用环境 | production
是否处于调试状态 | No
提交 | 52340ff28cad7f3a
Laravel 版本 | 7.0.8

PHP 版本 | 7.3.5
Web 服务软件 | nginx/1.16.1
操作系统 | Linux 5.5.8-1.el7.elrepo.x86_64 x86_64

已开启的插件 (13)
批量导入 | 4.0.0
-- | --
配置生成 | 3.1.2
嵌入第三方评论 | 1.0.2
Eruda | 1.0.0
Gravatar | 0.1.2
一言 | 1.2.1
使用预览版 | 1.0.2
传统皮肤加载方式 | 1.1.1
正版验证 | 1.7.0
使用 LittleSkin 登录 | 0.1.3
材质类型强制转换 | 0.2.0
Universal Skin API | 1.1.1
Yggdrasil API | 4.2.0

## Error Message 错误信息
![8Dj67n.png](https://s1.ax1x.com/2020/03/19/8Dj67n.png)
## Steps to Reproduce 重现步骤
上传alex模型皮肤，进我的衣柜查看皮肤预览，

**Comment by g-plane** [comment]
能提供一下材质以便我们测试吗？

**Comment by zhzRedstone** [comment]
![琪露诺(1)](https://user-images.githubusercontent.com/39423408/77020253-14175e80-69be-11ea-9a66-9597aed63299.png)
![Flame](https://user-images.githubusercontent.com/39423408/77020268-1b3e6c80-69be-11ea-94a9-814298c47f79.png)

**Comment by g-plane** [comment]
这两个都是 Alex 模型的材质吗？

**Comment by zhzRedstone** [comment]
一个alex一个steve
蓝色的为alex模型

**Comment by g-plane** [comment]
你是说在衣柜的预览不对还是上传的时候识别错误？

**Comment by zhzRedstone** [comment]
衣柜预览
