### ISSUE TITLE
关于3.x升级到4.x的问题

### ISSUE THREAD

**Issue by GiriNeko** [bs-community/blessing-skin-server#153]
## The Problem 问题描述
一开始没注意到这个项目，所以建站的时候采用的是3.5.0的版本。
现在我的服务器用户量增多，安全起见，我决定更新。
在更新的过程中遇到了一些问题，在文档中也没有看到解决方案。
![后台紊乱1](https://user-images.githubusercontent.com/21117880/77499762-f189b780-6e8d-11ea-8e94-8419e55e74cb.png)
后台选项名
![后台紊乱2](https://user-images.githubusercontent.com/21117880/77499795-0a926880-6e8e-11ea-8ea2-3b72e98028dd.png)
后台的配置选项排版

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):4.2.0
- PHP 版本 (Version of PHP):7.3
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version):Nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):Chrome,/admin/resource

除此之外，还有一些数据库的报错，只要重复升级步骤即可复现。

**Comment by g-plane** [comment]
具体有什么报错吗？

**Comment by GiriNeko** [comment]
`php artisan migrate --force
使用这个命令的时候，报了reports数据库已存在的错误
要是不理会的话，/user/closet页面500
要是删除reports的话就正常

**Comment by g-plane** [comment]
那就删除 reports 表然后重新 migrate？

**Comment by GiriNeko** [comment]
在4.2.0皮肤站文件+3.5.0sql的情况下就没有这个报错了
但是管理面板类似general.xxxx字样的选项和排版问题依然存在

**Comment by g-plane** [comment]
是不是你在升级过程中出现了什么文件缺失或者旧的文件没有被更新到？

**Comment by GiriNeko** [comment]
我是直接在旧文件的基础上，按照文档删除了一些文件，然后直接下载zip包解压覆盖的。
我甚至把env都换了

**Comment by g-plane** [comment]
你看看 `resources/lang/zh_CN/options.yml` 文件里有没有跟 `reports` 以及 `res-option` 相关的翻译文本。如果没有，说明文件没有被更新到。

**Comment by GiriNeko** [comment]
![image](https://user-images.githubusercontent.com/21117880/77501659-9c50a480-6e93-11ea-839e-7ddbec1391d3.png)
是有的

**Comment by g-plane** [comment]
尝试一下清除 i18n 缓存，目录位置大概在 `storage` 下的 `yaml-translations`。

**Comment by GiriNeko** [comment]
正常了，谢谢你！
