### ISSUE TITLE
上传皮肤时更改上传的皮肤不会改变材质名称

### ISSUE THREAD

**Issue by Cnzw** [bs-community/blessing-skin-server#154]
## The Problem 问题描述

上传皮肤时(无论拖动还是选择文件)
更改上传的皮肤不会改变材质名称

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):Lastest

## Steps to Reproduce 重现步骤

e.g. 上传了 a.png 材质名称显示 a ,但是又更改了上传的皮肤 b.png ,材质名称还是会显示 a ,而不是 b .

**Comment by g-plane** [comment]
这是故意设计的。如果用户手动指定了名称，如果还是用材质的文件名作材质名称，那么用户之前手动指定的名称就会被覆盖掉。
