### ISSUE TITLE
在阿里云上部署遇到的问题

### ISSUE THREAD

**Issue by xiaozhe19** [bs-community/blessing-skin-server#155]
## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):
- PHP 版本 (Version of PHP):
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version):
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):

**Comment by g-plane** [comment]
请认真按照我们的模板填写内容，谢谢。
