### ISSUE TITLE
在阿里云上部署遇到的问题

### ISSUE THREAD

**Issue by xiaozhe19** [bs-community/blessing-skin-server#156]
## The Problem 问题描述
阿里云上部署，使用LAPM环境，输入  域名/public/index.php 中提示
[Error] The program lacks write permission to directory < bootstrap/cache >
[错误] 程序缺少对 < bootstrap/cache > 目录的写权限，请手动授权。

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):4.4.0
- PHP 版本 (Version of PHP):7.3
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version):Apache
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):chrome 域名/public/index.php

## Error Message 错误信息

[Error] The program lacks write permission to directory < bootstrap/cache >
[错误] 程序缺少对 < bootstrap/cache > 目录的写权限，请手动授权。

**Comment by tnqzh123** [comment]
错误信息已经说明地很清楚了，你没有给予正确的文件权限。

如何更改文件权限请自行 Google。

**Comment by g-plane** [comment]
如有需要，可以加入我们的群组以寻求帮助。但在这之前请先认真阅读「安装指南」以及 FAQ，谢谢。
