### ISSUE TITLE
500错误

### ISSUE THREAD

**Issue by xiao-k233** [bs-community/blessing-skin-server#158]
## The Problem 问题描述

我,,,,安装了,,,,解压了,,,,,生成了appkey,,,配置文件也搞成.env了
但是打不开

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):5.0.0beta6
- PHP 版本 (Version of PHP):7.3
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version):Nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):/

## Error Message 错误信息
500错误
该网页无法处理请求

## Steps to Reproduce 重现步骤

我,,,,安装了,,,,解压了,,,,,生成了appkey,,,配置文件也搞成.env了
但是打不开

**Comment by g-plane** [comment]
请给日志。

**Comment by xiao-k233** [comment]
192.168.1.107 - - [06/Apr/2020:18:23:41 +0800] "GET / HTTP/1.1" 500 5 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"

**Comment by xiao-k233** [comment]
就是这样,没办法,Nginx日志不知道为何关闭了

**Comment by g-plane** [comment]
你需要给的是 Laravel 日志，位于 `storage/logs/laravel-xx.log`。请把日志贴在 pastebin 或类似网站上。

**Comment by xiao-k233** [comment]
emmmmmmmmmmmmmmm,我,尝试一下,换成4.4.0版本吧,那个,Laravel日志是在网站下面吗?

**Comment by g-plane** [comment]
是的。

**Comment by xiao-k233** [comment]
抱歉,我已经删了.............
