### ISSUE TITLE
开发者应用

### ISSUE THREAD

**Issue by xiao-k233** [bs-community/blessing-skin-server#159]
## The Problem 问题描述
![image](https://user-images.githubusercontent.com/58621432/78552637-6d92e080-783a-11ea-9a09-b94a3298e9a4.png)
这个东西能不能关掉!
看着不爽

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):4.4.0
- PHP 版本 (Version of PHP):7.3
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version):
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):

**Comment by tnqzh123** [comment]
你可以写插件屏蔽掉这一块，或者直接从源码中删掉这一块的菜单项。
