### ISSUE TITLE
皮肤库中查询请求多次发出

### ISSUE THREAD

**Issue by Asnxthaony** [bs-community/blessing-skin-server#161]
## The Problem 问题描述

皮肤库中查询请求多次发出

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): 71a1caf95dd02441670e9696d06411818cf85026

## Error Message 错误信息

![image](https://user-images.githubusercontent.com/12845643/78574905-3eda3180-785d-11ea-957b-007759802415.png)
![image](https://user-images.githubusercontent.com/12845643/78575288-bb6d1000-785d-11ea-8828-cd4a13707608.png)

## Steps to Reproduce 重现步骤

1、在浏览器内打开 http://skin.localhost.test/skinlib?filter=skin&sort=time&page=1
2、等待页面加载完成后，将 URL 中的 `page=1` 改为 `page=3`
3、在 Console 中可观察到查询请求多次发出

**Comment by g-plane** [comment]
https://github.com/bs-community/blessing-skin-server/commit/f0e3b6a8666ff3ea8e02528ec7ecd04b415fa300
