### ISSUE TITLE
验证邮箱出现问题

### ISSUE THREAD

**Issue by Sword-bob** [bs-community/blessing-skin-server#162]
## The Problem 问题描述

点击验证邮箱显示出Malformed UTF-8 characters, possibly incorrectly encoded.

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):3.5.0
- PHP 版本 (Version of PHP):5.5.9
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version):Apache
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):http://45.125.47.240:26079/user

## Error Message 错误信息

[2020-04-05 16:56:06] production.ERROR: exception 'InvalidArgumentException' with message 'Malformed UTF-8 characters, possibly incorrectly encoded' in C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Http\JsonResponse.php:58
Stack trace:
#0 C:\phpstudy_pro\WWW\skin\vendor\symfony\http-foundation\JsonResponse.php(49): Illuminate\Http\JsonResponse->setData(Array)
#1 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Http\JsonResponse.php(27): Symfony\Component\HttpFoundation\JsonResponse->__construct(Array, 200, Array)
#2 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(89): Illuminate\Http\JsonResponse->__construct(Array, 200, Array, 0)
#3 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(217): Illuminate\Routing\ResponseFactory->json(Array)
#4 C:\phpstudy_pro\WWW\skin\app\helpers.php(95): Illuminate\Support\Facades\Facade::__callStatic('json', Array)
#5 C:\phpstudy_pro\WWW\skin\app\helpers.php(95): Illuminate\Support\Facades\Response::json(Array)
#6 C:\phpstudy_pro\WWW\skin\app\Http\Controllers\UserController.php(140): json('???????????????...', 2)
#7 [internal function]: App\Http\Controllers\UserController->sendVerificationEmail()
#8 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(80): call_user_func_array(Array, Array)
#9 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('sendVerificatio...', Array)
#10 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\UserController), Object(Illuminate\Routing\Route), 'sendVerificatio...')
#11 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#15 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#16 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\UserController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'sendVerificatio...')
#17 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\Http\Contro...', 'sendVerificatio...')
#18 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\Route.php(140): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#19 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\Router.php(724): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 C:\phpstudy_pro\WWW\skin\app\Http\Middleware\CheckAuthenticated.php(47): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 [internal function]: App\Http\Middleware\CheckAuthenticated->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#25 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#30 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 C:\phpstudy_pro\WWW\skin\app\Http\Middleware\CheckSessionUserValid.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 [internal function]: App\Http\Middleware\CheckSessionUserValid->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#35 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#37 C:\phpstudy_pro\WWW\skin\app\Http\Middleware\DetectLanguagePrefer.php(12): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 [internal function]: App\Http\Middleware\DetectLanguagePrefer->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#40 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#42 C:\phpstudy_pro\WWW\skin\app\Http\Middleware\AfterSessionBooted.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: App\Http\Middleware\AfterSessionBooted->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#45 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#47 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#50 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#52 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#55 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#57 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#58 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#60 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#62 C:\phpstudy_pro\WWW\skin\app\Http\Middleware\RedirectIfUrlEndsWithSlash.php(22): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 [internal function]: App\Http\Middleware\RedirectIfUrlEndsWithSlash->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#65 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#67 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#68 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#69 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#70 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#72 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#73 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#74 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#75 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#76 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#77 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#78 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#79 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#80 C:\phpstudy_pro\WWW\skin\plugins\yggdrasil-api\src\Middleware\AddApiIndicationHeader.php(11): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#81 [internal function]: Yggdrasil\Middleware\AddApiIndicationHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#82 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#83 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#84 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#85 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#86 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#87 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#88 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#89 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#90 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#91 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#92 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#93 C:\phpstudy_pro\WWW\skin\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#94 C:\phpstudy_pro\WWW\skin\bootstrap\kernel.php(20): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#95 C:\phpstudy_pro\WWW\skin\index.php(30): require('C:\phpstudy_pro...')
#96 {main}  

## Steps to Reproduce 重现步骤

1、打开邮箱验证系统
2、以玩家模式点击验证邮箱发送
3、等待一会就会出现这种问题（邮件未发送）

**Comment by g-plane** [comment]
请不要直接把日志贴在 issue 里，谢谢合作。另外，v3 已停止支持。
