### ISSUE TITLE
Redis能否支持UNIX连接

### ISSUE THREAD

**Issue by hank9999** [bs-community/blessing-skin-server#164]
## The Problem 问题描述
Redis能否支持UNIX连接

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):5.0.0-beta8
- PHP 版本 (Version of PHP):7.3
- Apache / Nginx: Apache
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):

## Error Message 错误信息
https://pastebin.com/kBFM5w1v

## Steps to Reproduce 重现步骤
配置redis

**Comment by g-plane** [comment]
能的。

**Comment by tnqzh123** [comment]
支持，请在 .env 中添加如下字段：

- `REDIS_SCHEME`：Redis 连接方式，将其值设为`unix` 即可使用 Unix Socket 方式连接 Redis；
- `REDIS_SOCKET_PATH`：Redis 的 Unix Socket 文件的路径。

**Comment by hank9999** [comment]
> 支持，请在 .env 中添加如下字段：
> 
> * `REDIS_SCHEME`：Redis 连接方式，将其值设为`unix` 即可使用 Unix Socket 方式连接 Redis；
> * `REDIS_SOCKET_PATH`：Redis 的 Unix Socket 文件的路径。

谢谢 ok

**Comment by hank9999** [comment]
`REDIS_HOST`填写 Unix Socket 路径
`REDIS_POST`设置为0
