### ISSUE TITLE
Predis unix运行缺少变量

### ISSUE THREAD

**Issue by hank9999** [bs-community/blessing-skin-server#165]
## The Problem 问题描述
config/database.php没有定义predis所需变量

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): 5.0.0-beta.8
- PHP 版本 (Version of PHP): 7.4
- Apache / Nginx: Apache
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): /

## Error Message 错误信息
![e1](https://user-images.githubusercontent.com/20784591/79641159-55bb4500-81c8-11ea-9f7f-303843faa477.png)
![e2](https://user-images.githubusercontent.com/20784591/79641162-581d9f00-81c8-11ea-93a0-234e18ebb997.png)
手动在config/database.php添加后运行正常
![修改后](https://user-images.githubusercontent.com/20784591/79641199-9024e200-81c8-11ea-904c-f62e569c1f6f.png)

## Steps to Reproduce 重现步骤
配置Redis并启用Predis插件

**Comment by g-plane** [comment]
你是不是 .env 哪里配置错了？

**Comment by hank9999** [comment]
> 你是不是 .env 哪里配置错了？

emm? 另一个issues不是说REDIS_SCHEME和REDIS_SOCKET_PATH?

**Comment by g-plane** [comment]
你可以直接配置 `REDIS_URL` 的。

**Comment by hank9999** [comment]
测试发现scheme传递不过去?

**Comment by g-plane** [comment]
Laravel 里已经没有 scheme 这一项了。

**Comment by hank9999** [comment]
> Laravel 里已经没有 scheme 这一项了。

![TIM截图20200418231701](https://user-images.githubusercontent.com/20784591/79641547-bba8cc00-81ca-11ea-89b4-c098f82169ba.png)
那predis这是是不是该改下？

**Comment by g-plane** [comment]
Predis 的问题我们也管不了。

**Comment by hank9999** [comment]
我这边测试phpredis也有问题..需不需要再开一个issues?

**Comment by g-plane** [comment]
什么问题？

**Comment by hank9999** [comment]
> 什么问题？

稍后我传下log
我也说不太清楚

**Comment by g-plane** [comment]
请记得把 log 贴在 pastebin。

**Comment by hank9999** [comment]
> 请记得把 log 贴在 pastebin。

明白的

**Comment by hank9999** [comment]
log: https://pastebin.com/Lvpvyc1Z
debug截图:
![TIM截图20200418232840](https://user-images.githubusercontent.com/20784591/79641815-5bb32500-81cc-11ea-9ec6-2dff6382477a.png)

**Comment by hank9999** [comment]
完整log: https://pastebin.com/FvZzBCqZ

**Comment by g-plane** [comment]
这个应该是你那边的问题。

**Comment by hank9999** [comment]
> 这个应该是你那边的问题。

Predis可以正常运行;w;

**Comment by g-plane** [comment]
那我就不清楚了。

**Comment by hank9999** [comment]
> 那我就不清楚了。

好的，那我尽量试试找出问题

**Comment by hank9999** [comment]
测试发现配置unix后仍然连接的tcp?
$config并没有传递过来unix配置

**Comment by hank9999** [comment]
找到正确的方法了
`REDIS_HOST`填写路径
`REDIS_PORT`设置为0
