### ISSUE TITLE
注册时验证码不能加载

### ISSUE THREAD

**Issue by zcj924** [bs-community/blessing-skin-server#166]
## The Problem 问题描述

注册时验证码不能加载
![批注 2020-04-19 163158](https://user-images.githubusercontent.com/20927006/79683241-53ee9180-825b-11ea-8566-d6a0b1ce8f9f.png)

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):5.0.0-beta.8
- PHP 版本 (Version of PHP):7.4.4
- Apache / Nginx:nginx/1.17.9
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):https://192.168.123.101:8080/auth/register

**Comment by zcj924** [comment]
把图片打开会出现
(https://192.168.123.101:8080/auth/captcha?v=1587285106098)
500 Internal Server Error
详细信息：Call to undefined function imagettfbbox()

**Comment by tnqzh123** [comment]
**请给日志。**

日志位于 storage/logs/laravel.log，请自行截取相关的部分，上传至 Pastebin 后给出链接，或直接上传日志文件，**不要直接粘贴日志内容**。

**Comment by zcj924** [comment]
这里是日志
https://paste.ubuntu.com/p/WnNrFh73Zg/

**Comment by tnqzh123** [comment]
> GD Library extension not available with this PHP installation.

你没有安装 PHP 的 GD 扩展。

**Comment by zcj924** [comment]
之前头像不能加载,我开启GD后,头像可以了,但验证码还是不行.
这里的现在的GD信息


gd                                                                                         
                                                                                           
GD Support => enabled                                                                      
GD Version => bundled (2.1.0 compatible)                                                   
GIF Read Support => enabled                                                                
GIF Create Support => enabled                                                              
PNG Support => enabled                                                                     
libPNG Version => 1.6.36                                                                   
WBMP Support => enabled                                                                    
XBM Support => enabled                                                                     
BMP Support => enabled                                                                     
TGA Read Support => enabled                                                                
                                                                                           
Directive => Local Value => Master Value                                                   
gd.jpeg_ignore_warning => 1 => 1

**Comment by g-plane** [comment]
我记得这好像跟 GD 的配置有关，好像是字体方面的，你搜索一下相关资料？

**Comment by tnqzh123** [comment]
> 之前头像不能加载,我开启GD后,头像可以了,但验证码还是不行.

所以让你先自行截取日志中有用的部分…

你在安装 GD 扩展时，有启用 FreeType 2 支持吗？

https://stackoverflow.com/questions/7290958/php-fatal-error-call-to-undefined-function-imagettftext

**Comment by zcj924** [comment]
我刚刚看了一下,确实没有FreeType
我来启用试试

**Comment by zcj924** [comment]
我安装了FreeType,也是一样的不能加载
````
gd                                                                                         
                                                                                           
GD Support => enabled                                                                      
GD Version => bundled (2.1.0 compatible)                                                   
FreeType Support => enabled                                                                
FreeType Linkage => with freetype                                                          
FreeType Version => 2.9.1                                                                  
GIF Read Support => enabled                                                                
GIF Create Support => enabled                                                              
PNG Support => enabled                                                                     
libPNG Version => 1.6.36                                                                   
WBMP Support => enabled                                                                    
XBM Support => enabled                                                                     
BMP Support => enabled                                                                     
TGA Read Support => enabled 
````

不过这次提示不一样

````
500 Internal Server Error
详细信息：Call to undefined function Gregwar\Captcha\imagejpeg()
````
[这里是最新的日志](https://paste.ubuntu.com/p/hFNbvy8QWG/)

**Comment by tnqzh123** [comment]
@zcj924 
> 我安装了FreeType,也是一样的不能加载
> ````
> gd                                                                                         
>                                                                                            
> GD Support => enabled                                                                      
> GD Version => bundled (2.1.0 compatible)                                                   
> FreeType Support => enabled                                                                
> FreeType Linkage => with freetype                                                          
> FreeType Version => 2.9.1                                                                  
> GIF Read Support => enabled                                                                
> GIF Create Support => enabled                                                              
> PNG Support => enabled                                                                     
> libPNG Version => 1.6.36                                                                   
> WBMP Support => enabled                                                                    
> XBM Support => enabled                                                                     
> BMP Support => enabled                                                                     
> TGA Read Support => enabled 
> ````
> 
> 不过这次提示不一样
> 
> ````
> 500 Internal Server Error
> 详细信息：Call to undefined function Gregwar\Captcha\imagejpeg()
> ````
> [这里是最新的日志](https://paste.ubuntu.com/p/hFNbvy8QWG/)
> 

你怎么安装的 GD 扩展？

根据 PHP 的文档：
> JPEG 支持仅在 PHP 与 GD-1.8 或更高版本一起编译时可用。

**Comment by zcj924** [comment]
是联合编译的

**Comment by zcj924** [comment]
全部重来后,目前看起来一切正常
虽然不是网站的问题,估计是PHP的问题,谢谢作者解答
