### ISSUE TITLE
有没有可能添加个uuid 获取皮肤的接口了 

### ISSUE THREAD

**Issue by graytoowolf** [bs-community/blessing-skin-server#170]
https://crafatar.com/skins/4d19c01f518c3977ac1cdba4d0f77e51.png

就像这种接口

**Comment by g-plane** [comment]
安装 Yggdrasil API 插件就是了。

**Comment by graytoowolf** [comment]
> 安装Yggdrasil API插件就是了。

我安装了 也没有呀 能给个演示地址吗。谢谢

**Comment by g-plane** [comment]
请阅读 Yggdrasil API 相关文档和规范，自行研究。
