### ISSUE TITLE
功能请求：添加测试邮箱设置是否有效

### ISSUE THREAD

**Issue by graytoowolf** [bs-community/blessing-skin-server#172]

**Comment by g-plane** [comment]
请认真编辑你的 issue，重新组织语言。谢谢合作。

**Comment by graytoowolf** [comment]
> 请认真编辑你的问题，重新组织语言。谢谢合作。
就是 现在 编辑邮箱 smtp  不是只可以 改.env 吗   ?  我想验证 smtp 设置正确没 也只能注册个账号来 发送邮件 . 来验证 smtp 有没有设置 正确.
我的想法是  在管理后台 可不可以添加相应的 功能了?

**Comment by g-plane** [comment]
你把自己的邮箱验证状态设置为「未验证」，然后自己给自己发送一封验证邮件就行了。
记得先打开「要求验证邮箱」选项。
