### ISSUE TITLE
材质所需积分计算方式不统一

### ISSUE THREAD

**Issue by NPBeta** [bs-community/blessing-skin-server#174]
## The Problem 问题描述

“上传材质” 页面的积分计算规则与后端执行积分扣除时采用的计算规则不同，导致上传材质时，有几率出现“积分不足”提示。

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): **5.0.0-beta9 (8b2f2d)**
- PHP 版本 (Version of PHP): **7.3.12**
- Apache / Nginx: **Nginx 1.17.6**
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): **/skinlib/upload**

## Error Message 错误信息

无。

## Steps to Reproduce 重现步骤

首先，约定每 KB 存储空间消耗 10 积分，以便下面的描述。
“上传材质” 页面采用的计算规则是 “对文件大小**向下取整**”，即 1.9KB 的文件**按 1KB 计算**，结果为 “预计消耗 **10** 积分”。
积分扣除时采用的规则是 “对文件大小**向上取整**”，即同样为 1.9KB 的文件**按 2KB 计算**，结果为 “扣除 **20** 积分”。
若用户要上传此文件，且积分余额在 **[10,19]** 区间内，则无法成功上传材质，提示 **“积分不足”**。
再提一个小建议，在 “上传材质” 页面增加 “积分余额显示” 功能，或许可以更加便于用户参照。
~~（如果在拉取一次 积分余额 后，再利用 JS 实现 所需积分 和 积分余额 的实时比较，并设置表单是否可以提交，可以避免每次都需提交到 PHP 处理并查询数据库进行比较的操作，从而提升效率和性能。不过这属于优化范畴了。）~~

**Comment by g-plane** [comment]
> 如果在拉取一次 积分余额 后，再利用 JS 实现 所需积分 和 积分余额 的实时比较，并设置表单是否可以提交

这个不太可能吧……后端肯定要进行计算和判断的，因为不能保证用户那边发送了什么内容过来。

**Comment by NPBeta** [comment]
> > 如果在拉取一次 积分余额 后，再利用 JS 实现 所需积分 和 积分余额 的实时比较，并设置表单是否可以提交
> 
> 这个不太可能吧……后端肯定要进行计算和判断的，因为不能保证用户那边发送了什么内容过来。

可能举个例子说明会清晰一点。
用户访问 “上传材质” 页面时，会查询用户的积分余额。这里定为 500.
此时，该用户预览了一个需要 1000 积分的材质，JS 判断 500<1000，因此将 “确认上传” 按钮设置为**不可用**状态。

> 因为不能保证用户那边发送了什么内容过来。

或许你们是有对安全性或其他方面的考量，所以没有采用我上面的方案，统一提交到后端处理？

**Comment by g-plane** [comment]
对的，将按钮设置成「不可用」状态这个没问题，可以实现。但不能因为实现了这个功能而去掉后端的检查。
