### ISSUE TITLE
无法访问更新源。

### ISSUE THREAD

**Issue by mkwwmka5** [bs-community/blessing-skin-server#175]
## The Problem 问题描述
无法访问当前更新源。

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): 4.4.0
- PHP 版本 (Version of PHP): 7.3.4
- Apache / Nginx: Nginx 1.15.11
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): 
- 浏览器谷歌
- 出错地址: http://skin.cagebird.cn/admin/update

## Error Message 错误信息
cURL error 60: SSL: no alternative certificate subject name matches target host name 'cmi.zerodream.net' (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

## Steps to Reproduce 重现步骤
按照教程安装程序后，想升级程序但无法升级

按照教程安装程序后，想升级程序但无法升级

**Comment by g-plane** [comment]
这不是我们的官方源。

**Comment by mkwwmka5** [comment]
> 这不是我们的官方源。

官方源依然如此

**Comment by g-plane** [comment]
如果是 404 那是正常现象，但其它错误就不是我们的问题了。

**Comment by mkwwmka5** [comment]
> 如果是 404 那是正常现象，但其它错误就不是我们的问题了。

不是404
请问有没有方法解决
重装php或者什么其他操作

**Comment by tnqzh123** [comment]
@mkwwmka5 

> 不是404
> 请问有没有方法解决
> 重装php或者什么其他操作

麻烦给一下官方源的报错

**Comment by mkwwmka5** [comment]
> @mkwwmka5
> 
> > 不是404
> > 请问有没有方法解决
> > 重装php或者什么其他操作
> 
> 麻烦给一下官方源的报错

好的
(https://user-images.githubusercontent.com/59493751/83346039-c74fec80-a34b-11ea-9a09-d765b61b4500.png)

**Comment by tnqzh123** [comment]
@mkwwmka5 

> 好的
> (https://user-images.githubusercontent.com/59493751/83346039-c74fec80-a34b-11ea-9a09-d765b61b4500.png)

麻烦你再仔细看一眼报错。

**Comment by g-plane** [comment]
这就是 404 了。

**Comment by mkwwmka5** [comment]
> @mkwwmka5
> 
> > 好的
> > (https://user-images.githubusercontent.com/59493751/83346039-c74fec80-a34b-11ea-9a09-d765b61b4500.png)
> 
> 麻烦你再仔细看一眼报错。

非官方源也会受到影响的吗

**Comment by tnqzh123** [comment]
@mkwwmka5

> 非官方源也会受到影响的吗

仔细看一眼，谢谢。这是不一样的错误信息。

**Comment by mkwwmka5** [comment]
> @mkwwmka5
> 
> > 非官方源也会受到影响的吗
> 
> 仔细看一眼，谢谢。这是不一样的错误信息。

好吧
