### ISSUE TITLE
更新版本后出现部分无法使用，如何解决

### ISSUE THREAD

**Issue by mkwwmka5** [bs-community/blessing-skin-server#176]
## The Problem 问题描述
从4.4.0版本更新至5.0.0-beta 9版本后
导致了这样的问题
首页不完整
https://i2.tiimg.com/711435/13d610a13ff3871a.png
登录窗口无法进入
https://i2.tiimg.com/711435/110bbee7ca675998.png

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): 4.4.0升级至5.0.0 -beta 9
- PHP 版本 (Version of PHP): 7.3.4
- Apache / Nginx: nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): 谷歌

## Error Message 错误信息
无

## Steps to Reproduce 重现步骤

装载预览版扩展，然后使用官方源下载安装升级程序
升级完毕后，导致了如上情况
请问如何解决

**Comment by g-plane** [comment]
浏览器控制台有没有什么错误提示？

**Comment by mkwwmka5** [comment]
> 浏览器控制台有没有什么错误提示？

稍等，我上传图片外链

**Comment by mkwwmka5** [comment]
> 浏览器控制台有没有什么错误提示？

https://i2.tiimg.com/711435/80f0358910bf5c9c.png

**Comment by g-plane** [comment]
不是这里，是 Console 标签页。

**Comment by mkwwmka5** [comment]
> 不是这里，是 Console 标签页。

https://i2.tiimg.com/711435/644d79a22143703f.png

**Comment by g-plane** [comment]
哦 404……你访问的时候 URL 有没有带 `index.php`？

**Comment by tnqzh123** [comment]
@hempflower 你家 CDN 好像又炸了

**Comment by mkwwmka5** [comment]
> index.php

没得

**Comment by g-plane** [comment]
换个 CDN 吧……或者直接不用。

**Comment by mkwwmka5** [comment]
> 换个 CDN 吧……或者直接不用。

想尝试更换，但是无法进入后台。
数据库里改咯？

**Comment by g-plane** [comment]
能进后台的，除非你没有登录。

另外，如果只是单纯的问题，不是 bug 报告或特性请求请在 Telegram 群组或 QQ 群中讨论。

**Comment by hempflower** [comment]
CDN没有跟进beta版本，而根据报错信息来看，你用的4.x版本的CDN（

**Comment by mkwwmka5** [comment]
> CDN没有跟进beta版本，而根据报错信息来看，你用的4.x版本的CDN（

确实如此，很抱歉

**Comment by mkwwmka5** [comment]
> 能进后台的，除非你没有登录。
> 
> 另外，如果只是单纯的问题，不是 bug 报告或特性请求请在 Telegram 群组或 QQ 群中讨论。

好的，请问QQ群的群号多少呢

**Comment by g-plane** [comment]
手册中有，自己找。
