### ISSUE TITLE
无法加载模型皮肤图片

### ISSUE THREAD

**Issue by myktw** [bs-community/blessing-skin-server#180]
## The Problem 问题描述
第一次搭建，无法加载皮肤其他图片正常，关闭了Nginx对png缓存也是一样无法加载皮肤模型以及皮肤图片
## Environment 运行环境
- Blessing Skin 版本 (Version of Blessing Skin): 5.0.0-rc.1
- PHP 版本 (Version of PHP): 7.4.6
- Apache / Nginx:Nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):Google Chrome

## Error Message 错误信息
https://s1.ax1x.com/2020/06/11/t7bIyR.png
https://s1.ax1x.com/2020/06/11/t7b7ex.png

**Comment by g-plane** [comment]
升级到 RC 2 之后，新上传的材质应该正常了。但原来的材质需要重新上传：先进入 `storage/textures` 目录，检查这个目录下有没有子目录，如果有就将所有的子目录删除。接着重新上传这些之前失败的材质。

**Comment by myktw** [comment]
已正常
