### ISSUE TITLE
在衣柜更换皮肤后在角色管理处仍然显示默认史蒂夫,2D预览显示未上传

### ISSUE THREAD

**Issue by mwx2006** [bs-community/blessing-skin-server#182]
## The Problem 问题描述
在衣柜更换皮肤后在角色管理处仍然显示默认史蒂夫,2D预览显示未上传

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):5.0.0-rc.2
- PHP 版本 (Version of PHP):7.4.6
- Apache / Nginx:Apache 
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): http://mc.lovetopia.top:233/user/player MS Edge 版本 83.0.478.45
- 已开启的插件 (8)
```
配置生成 | 3.2.0
Gravatar | 0.1.2
一言 | 1.3.0
传统皮肤加载方式 | 1.1.1
正版验证 | 1.9.0
OAuth 客户端核心 | 1.0.1
单角色限制 | 3.0.0
Yggdrasil API | 4.7.3
```
## Error Message 错误信息
1.后台未报错但是我觉得这个应该算是bug
2.如图:
[再现截图(gif文件较大)](https://cdn.jsdelivr.net/gh/mwx2006/Img/%E8%A7%92%E8%89%B2%E7%AE%A1%E7%90%86%20-%20MCtopia-Skin%20%E5%92%8C%E5%8F%A6%E5%A4%96%2027%20%E4%B8%AA%E9%A1%B5%E9%9D%A2%20-%20%E4%B8%AA%E4%BA%BA%20-%20Microsoft%E2%80%8B%20Edge%202020-06-14%2013-07-33.gif)

## Steps to Reproduce 重现步骤
[再现截图(gif文件较大)](https://cdn.jsdelivr.net/gh/mwx2006/Img/%E8%A7%92%E8%89%B2%E7%AE%A1%E7%90%86%20-%20MCtopia-Skin%20%E5%92%8C%E5%8F%A6%E5%A4%96%2027%20%E4%B8%AA%E9%A1%B5%E9%9D%A2%20-%20%E4%B8%AA%E4%BA%BA%20-%20Microsoft%E2%80%8B%20Edge%202020-06-14%2013-07-33.gif)
如图:
1.登录皮肤站
2.进入我的衣柜
3.选择皮肤并应用
4.进入角色管理
5.预览仍显示默认史蒂夫,2D预览显示未上传

**Comment by g-plane** [comment]
已经修复了，请耐心等待新版本。
