### ISSUE TITLE
部分皮肤预览失败

### ISSUE THREAD

**Issue by mwx2006** [bs-community/blessing-skin-server#183]
## The Problem 问题描述
部分皮肤预览失败

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):5.0.0-rc.2
- PHP 版本 (Version of PHP):7.4.6
- Apache / Nginx:Apache
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):http://mc.lovetopia.top:233/preview/1?height=150

## Error Message 错误信息
ErrorException
imagecolorat(): 43,52 is out of bounds
http://mc.lovetopia.top:233/preview/1?height=150

## Steps to Reproduce 重现步骤
上传特点皮肤时出现

**Comment by Asnxthaony** [comment]
材质模型不正确，请选择 `Steve` 模型。
