### ISSUE TITLE
阿里云CDN下材质删除问题

### ISSUE THREAD

**Issue by hank9999** [bs-community/blessing-skin-server#184]
## The Problem 问题描述
您好，删除材质发送的DELETE请求 Body带有2个括号
![1](https://user-images.githubusercontent.com/20784591/84654168-47c43f00-af41-11ea-93e5-acda6c9fbcf9.png)
阿里云CDN除POST GET方法以外仅支持无Body
进而导致删除失败

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): 5.0.0-rc2
- PHP 版本 (Version of PHP): 7.4
- Apache / Nginx: Nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): Chrome 83 https://xxx.com/skinlib/show/85

## Error Message 错误信息
CDN 返回的504错误(请求未传递)
![2](https://user-images.githubusercontent.com/20784591/84654430-c0c39680-af41-11ea-8735-cd3e126e9a2f.png)

## Steps to Reproduce 重现步骤
在部署阿里云CDN后删除材质

实测抓包删掉两个括号后即可删除

**Comment by g-plane** [comment]
PUT 方法正常吗？

**Comment by hank9999** [comment]
阿里云CDN支持PUT带Body
BS的删除材质相关路由还不支持PUT
`"message": "The PUT method is not supported for this route. Supported methods: GET, HEAD, DELETE."`

**Comment by hank9999** [comment]
阿里云文档

仅支持POST和PUT方式发送带有请求体（BODY）的HTTP请求。

请求方式 | 描述 | 是否支持
-- | -- | --
GET | 从指定的资源请求数据。 | 支持
POST | 向指定的资源提交要被处理的数据。 | 支持
HEAD | 与GET相同，但只返回HTTP报头，不返回文档主体。 | 支持
PUT | 上传指定的URI。 | 支持
DELETE | 删除指定资源。 | 支持
OPTIONS | 返回服务器支持的HTTP方法。 | 支持
CONNECT | 把请求连接转换到透明的TCP/IP通道。 | 不支持

**Comment by g-plane** [comment]
我稍晚些会检查所有的 delete 路由。

**Comment by hank9999** [comment]
好的 谢谢

**Comment by g-plane** [comment]
目前是由两处的 delete 路由会传递 body：
- 清除角色的材质
- 管理员删除某个用户的衣柜物品（这个用得比较少，因为目前这个功能只存在于 Web CLI 中）
