### ISSUE TITLE
[Bug] Blessing-Skin-Server 5.0.0-rc.4 安装若干插件后出现 HTTP 500 错误

### ISSUE THREAD

**Issue by TheZihanGu** [bs-community/blessing-skin-server#191]
## 问题描述
通过 Blessing-Skin-Server 程序附带的插件商店安装插件后出现页面报错，刷新后出现 HTTP 500 错误。开启 ```debug```后发现为```Class Illuminate\Translation\Translator contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods```报错。

## 运行环境

- Blessing Skin 版本: 5.0.0-rc.4
- PHP 版本: 7.4.7
- Apache 2.4
- Chrome 83.0.4103.116, [https://skin.tzg-craft.com/](https://skin.tzg-craft.com/)

## 错误信息
![截屏2020-07-03 下午11 13 01](https://user-images.githubusercontent.com/39030261/86481577-e0045580-bd82-11ea-8d38-f803dc66c7e6.png)   
目前可重现。

## 重现步骤
目前可以复现此错误。   
出现此错误前进行过以下动作：
* 安装若干插件 (官方商店) 后出现报错，无法进行正常操作   
* 重新刷新页面后报 HTTP 500

**Comment by tnqzh123** [comment]
请提供完整的 Laravel 日志文件。

[报告问题的正确姿势](https://blessing.netlify.app/report.html)

**Comment by g-plane** [comment]
有没有启用过什么插件？

**Comment by TheZihanGu** [comment]
> 有没有启用过什么插件？

yggdrasil-api, single-player-limit, mojang-verification, gravatar
应该只有这四个插件被启用了。

**Comment by g-plane** [comment]
不过这个复现步骤没什么有效信息……

**Comment by TheZihanGu** [comment]
> 请提供完整的 Laravel 日志文件。
> 
> 提供下载链接，或将其放到 Pastebin 上。
> 
> [报告问题的正确姿势](https://blessing.netlify.app/report.html)

[blessing-skin-server - #191 - Pastebin Service](https://paste.centos.org/view/247d3305)

**Comment by TheZihanGu** [comment]
> 不过这个复现步骤没什么有效信息……

hmm...的确，因为我其实也不知道是哪里出了问题🤷‍♂️

**Comment by g-plane** [comment]
似乎恢复了？

**Comment by TheZihanGu** [comment]
> 似乎恢复了？

...我换了个服务器。
之前可能是由于 remote-addr 的问题，我这边在新服务器开启这个插件依然出现错误。

**Comment by g-plane** [comment]
开启 remote-addr 会导致这个错误？

**Comment by TheZihanGu** [comment]
> 开启 remote-addr 会导致这个错误？

嗯，对的。
至少我这里尝试是这样。

**Comment by g-plane** [comment]
我这边没遇到，而且理论上这个插件不会出现那种错误。

**Comment by TheZihanGu** [comment]
> 我这边没遇到，而且理论上这个插件不会出现那种错误。

那就不知道了。我先close掉吧，等再出现之后reopen.

**Comment by hilookas** [comment]
尝试清除一下缓存？`php artisan clear-compiled`
