### ISSUE TITLE
[Bug] Blessing-Skin-Server 5.0.0-rc.4 注册/登陆页面 SRI 验证错误

### ISSUE THREAD

**Issue by TheZihanGu** [bs-community/blessing-skin-server#192]
## 问题描述
多名玩家反应无法正常登陆/注册，查看Console后发现为子资源完整性验证失败，出现报错并被屏蔽。
**B U G 体 质**

## 运行环境

- Blessing Skin 版本: 5.0.0-rc.4
- PHP 版本: 7.4.3
- Apache 2.4
- Chrome 83.0.4103.116, [https://skin.tzg-craft.com/](https://skin.tzg-craft.com/)

## 错误信息
```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdn.jsdelivr.net/npm/@blessing-skin/admin-lte@3.0/dist/admin-lte.min.js' with computed SHA-256 integrity '8RoBtV28TLYWlTMCRwqGv4NQW9bgc4jZphsQV3iLV4g='. The resource has been blocked.
```
```
Uncaught ReferenceError: jQuery is not defined
    at Object.<anonymous> (app.b531baf.js:10)
    at i (app.b531baf.js:1)
    at Object.<anonymous> (app.b531baf.js:10)
    at i (app.b531baf.js:1)
    at Object.<anonymous> (app.b531baf.js:1)
    at i (app.b531baf.js:1)
    at Object.<anonymous> (app.b531baf.js:10)
    at i (app.b531baf.js:1)
    at Module.<anonymous> (app.b531baf.js:10)
    at i (app.b531baf.js:1)
```

## 重现步骤
目前可以重现此报错。
未对源程序做任何修改。

**Comment by TheZihanGu** [comment]
再给张图。
![截屏2020-07-04 上午11 01 49](https://user-images.githubusercontent.com/39030261/86503955-cd6f3800-bde5-11ea-9d85-dfb5810a3c35.png)

**Comment by g-plane** [comment]
SRI 是我们的问题。

**Comment by TheZihanGu** [comment]
> SRI 是我们的问题。

那就催更（
顺便，有什么临时措施么...

**Comment by g-plane** [comment]
有， https://github.com/bs-community/blessing-skin-server/blob/ae687b8cf5817344b8bdaaa2fd3adb0e01ee91c8/app/Http/View/Composers/FootComposer.php#L77

把 `3.0` 改成 `3.0.4`。

**Comment by TheZihanGu** [comment]
> 有，
> 
> https://github.com/bs-community/blessing-skin-server/blob/ae687b8cf5817344b8bdaaa2fd3adb0e01ee91c8/app/Http/View/Composers/FootComposer.php#L77
> 
> 把 `3.0` 改成 `3.0.4`。

gotcha.

**Comment by g-plane** [comment]
RC 5 已发布。
