### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by Krusoe** [bs-community/blessing-skin-server#193]
## The Problem 问题描述
按照安装指南安装后
浏览器指示HTTP ERROR 500
翻了一下Log好像也只有没配置的SQL的错误

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):5.0.0-rc5
- PHP 版本 (Version of PHP):PHP7.4
- Apache / Nginx:Apache2.6
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):Chrome,my.domain/setup

## Error Message 错误信息
Laravel Log: https://pan.baidu.com/s/1YduCHtYysCMKEnvAbvNkBw  :  sgc5
![image](https://user-images.githubusercontent.com/62324837/87239857-76e9a580-c446-11ea-8434-d0828147c3f4.png)

## Steps to Reproduce 重现步骤
安装指南

**Comment by g-plane** [comment]
麻烦日志不要放在网盘，请把它放在 pastebin 上。

**Comment by g-plane** [comment]
我猜很有可能是因为你没有生成 app key？

**Comment by Krusoe** [comment]
Pastebin提示Public pasting is currently disabled
顺带一提，刚才发现是Appkey的问题，谢谢回复

**Comment by g-plane** [comment]
你这叫「按照指南来安装」吗？

**Comment by tnqzh123** [comment]
帮你把图删了，以后 IP 记得打码...

**Comment by Krusoe** [comment]
确实是我的问题，对不起.
