### ISSUE TITLE
同一用户可重复上传相同的私有材质

### ISSUE THREAD

**Issue by tnqzh123** [bs-community/blessing-skin-server#194]
## The Problem 问题描述

当用户上传了一件私有材质后，他可以再次上传相同的材质，而不会跳转至该用户之前上传的私有材质的材质详情页面。

## Environment 运行环境

- Blessing Skin 版本：开发版 `a4849c70`
- PHP 版本：7.4.6

## Error Message 错误信息

无。

## Steps to Reproduce 重现步骤

上传一件材质并将其设为私有后，再次上传该材质。

**Comment by tnqzh123** [comment]
同样的，私有材质在转换为公开材质时不会检测皮肤库中是否已存在相同的材质。如，若用户 A 上传了一件材质并将其私有，而后用户 B 也上传了这件材质并将其设为公开，用户 A 仍可以直接将该材质设为公开材质。

**Comment by hs-err** [comment]
已pr，将私有转为公有产生的重复问题前端部分未处理。
