### ISSUE TITLE
更新5.0.0后无法更新插件列表&获取更新

### ISSUE THREAD

**Issue by BecodReyes** [bs-community/blessing-skin-server#196]
## The Problem 问题描述

更新5.0.0后无法更新插件列表&获取更新

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): 5.0.0
- PHP 版本 (Version of PHP): 7.3.19
- Apache / Nginx: Nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): Chrome  https://skin.***.com/admin/plugins/market

## Error Message 错误信息
500 Internal Server Error
详细信息：Call to undefined method GuzzleHttp\Utils::chooseHandler()
logs:
[https://pastebin.com/Vq4TqdQj](https://pastebin.com/Vq4TqdQj)

## Steps to Reproduce 重现步骤

通过面板内检查更新选项将5.0.0-rc.5更新为5.0.0后出现错误

**Comment by g-plane** [comment]
先关掉所有插件，然后更新所有插件，再更新它们。
