### ISSUE TITLE
[Add]Login可用于验证密码，建议同时使用ip+用户名限制

### ISSUE THREAD

**Issue by hs-err** [bs-community/blessing-skin-server#206]
## The Problem 问题描述

https://github.com/bs-community/blessing-skin-server/blob/20b172c842d430c8b1b6d2482d8f94746c6a700c/app/Http/Controllers/AuthController.php#L29

https://github.com/bs-community/blessing-skin-server/blob/20b172c842d430c8b1b6d2482d8f94746c6a700c/app/Http/Controllers/AuthController.php#L368

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): 527cd706b2216e352612bf5f0eedc5a15db4cde8
- PHP 版本 (Version of PHP):7.4.3
- Apache / Nginx:PHP 7.4.3 Development Server
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):http://127.0.0.1:8000/auth/login

**Comment by g-plane** [comment]
请详细描述你的问题。

**Comment by hs-err** [comment]
> 请详细描述你的问题。

jwt可用于爆破密码

**Comment by g-plane** [comment]
有速率限制的。

**Comment by hs-err** [comment]
希望添加以user为主键的限制。

**Comment by g-plane** [comment]
速率限制与用户无关，对所有 API 均起作用。
