### ISSUE TITLE
[Question] How to install a new translation from Crowdin ? 

### ISSUE THREAD

**Issue by Aeris1One** [bs-community/blessing-skin-server#207]
Hi,
I just opened my instance of Blessing Skin for my server but a great majority of our players are French.
Can you tell me how to use the French translation from the Crowdin ?

**Comment by Aeris1One** [comment]
Solved !

**Comment by g-plane** [comment]
Hi, are you willing to help us to translate Blessing Skin to French?

**Comment by Aeris1One** [comment]
I already started to translate French on Crowdin (#195) and as soin I've the time i'll translate somme others strings ;)

**Comment by g-plane** [comment]
Thanks! And you can ask your friends to translate it as well.
