### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by Pai2Chen** [bs-community/blessing-skin-server#210]
点击检查更新出现
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
插件市场也是这样

**Comment by Restent** [comment]
由于维护停机或容量问题，服务器暂时无法为您的请求提供服务。
这个可能得问GPlane

**Comment by Pai2Chen** [comment]
不是面板的问题就好~
