### ISSUE TITLE
Syntax error or access violation: 1071 Specified key was too long;

### ISSUE THREAD

**Issue by KJZH001** [bs-community/blessing-skin-server#211]
## The Problem 问题描述
发生在安装时（全新安装，且删除数据表后进行过多次尝试）
在创建数据库内容时或载入./setup/finish页面会返回500错误

## Environment 运行环境

- Blessing Skin 版本 :v5.0.0 - Crescent Moon Dance(非自行构建)
- PHP 版本 :php7.3.4nts_p
- Apache / Nginx : Apache
- 什么浏览器，出现错误时的地址栏 URL 是什么 :http://skin.rcraft.ml:30000/setup/finish

## Error Message 错误信息

https://cdn.jsdelivr.net/gh/KJZH001/For_PicGO@master/jsDelivr_static_files/img/large/20200728190011.png

https://cdn.jsdelivr.net/gh/KJZH001/For_PicGO@master/jsDelivr_static_files/laravel-2020-07-26.log

https://cdn.jsdelivr.net/gh/KJZH001/For_PicGO@master/jsDelivr_static_files/laravel-2020-07-28.log

## Steps to Reproduce 重现步骤

1. 创建数据库

2. 修改.env文件中的APP_DEBUG=true

3. 填写安装信息

4. 进入下一步后错误出现

## 更多附加的信息

使用的是PhpStudy(小皮面板)Windows版集成环境（非Web面板）

MySql5.7.26

抱歉Markdown不太会用，排版只能请你将就看下了= =

**Comment by tnqzh123** [comment]
@KJZH001

**Comment by mochaaP** [comment]
@KJZH001 这个 jsdelivr 当图床简直天才

**Comment by tnqzh123** [comment]
这是 Windows 下 MySQL 的问题。

请将操作系统更换为 Linux，或使用除 MySQL 外的数据库。

顺带，P h p S t u d y 是 垃 圾

**Comment by g-plane** [comment]
快快换掉这种问题多多的面板吧……最好是把操作系统也换了。

**Comment by KJZH001** [comment]
emmn....好吧，我了解了
不过这个问题我已经在参考了这篇文章以后自己解决了
https://www.cnblogs.com/rendd/p/10244361.html
顺利安装
不过在安装插件的时候经常会返回Get和Post方法的严重错误....
不知道这个算是windows系统或者面板bug吗？

**Comment by g-plane** [comment]
是什么错误？

**Comment by KJZH001** [comment]
抱歉
因为这个不是100%会遇到的错误，是有时会发作
此前几次出现的时候大致都是在尝试安装 OAuth 客户端核心 一类比较大的插件
返回的错误内容大致是 "此方法为GET但是目标只能为POST类型的方法"(英文翻译的过来大致意思是这样)
所有这个 issue 能否暂时保留为开启状态，我会在近期遇到的时候尽快将其提交到此处

**Comment by g-plane** [comment]
你可以给日志。
