### ISSUE TITLE
Yggdrasil 日志 无任何记录 登录什么调试都正常

### ISSUE THREAD

**Issue by Fcatme** [bs-community/blessing-skin-server#213]
## The Problem 问题描述
Yggdrasil 日志 没有显示任何东西  
看到有5.0新版 升级失败 索性直接清库重装了一波。 安装了Yggdrasil API 插件 就出现了日志没有记录登录这些日志

之前用4.0版本的时候没有遇到这类情况。 配置什么都是正常的。

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): v5.0.0
- PHP 版本 (Version of PHP): PHP 7.3
- Apache / Nginx: Nginx 1.16.1
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): https://xxxxxx/admin/yggdrasil-log

## Steps to Reproduce 重现步骤

清理所有网站文件和数据库
然后下载了最新版的 Blessing Skin
正常的安装步骤。
清空了 PHP 所有禁用函数
安装成功
安装了
Yggdrasil API插件
删除了HMCL创建的用户重新登录添加
登录成功
Yggdrasil 日志 没有显示任何东西

**Comment by tnqzh123** [comment]
请在 .env 中添加一行 `YGG_VERBOSE_LOG=true`。

**Comment by Fcatme** [comment]
> [.env]`YGG_VERBOSE_LOG=true`

感谢你的回答 已经ok~
