### ISSUE TITLE
启动器读取角色头像时读取失败

### ISSUE THREAD

**Issue by zsn741656478** [bs-community/blessing-skin-server#215]
## The Problem 问题描述
PCL2启动器读取角色头像时读取失败，同个用户其他角色都没问题，但其中有一个角色的头像一直无法读取，不过在游戏中是能正常显示皮肤，感觉像是皮肤站的问题。

## Environment 运行环境
Blessing Skin 版本 (Version of Blessing Skin): v5.0.0
PHP 版本 (Version of PHP): 7.3.4 nts_p
Apache / Nginx: Apache 2.4.39

## Error Message 错误信息
启动器日志：https://paste.ubuntu.com/p/jWKYR9ScVx/
皮肤站没相关日志。

## Steps to Reproduce 重现步骤
在启动器内多个角色中切换，其中一个始终无法被读取，与皮肤站连接超时。

**Comment by mochaaP** [comment]
@zsn741656478 https://del.dog/acuhingyst.txt
请检查 Laravel 日志。

**Comment by zsn741656478** [comment]
> @zsn741656478 https://del.dog/acuhingyst.txt
> 请检查 Laravel 日志。

https://paste.ubuntu.com/p/CxGRQFzmQF/

**Comment by g-plane** [comment]
能不能尝试一下在浏览器中单独访问 PCL2 显示头像所请求的那个 URL？

**Comment by mochaaP** [comment]
我 curl 过了。

**Comment by zsn741656478** [comment]
> 能不能尝试一下在浏览器中单独访问 PCL2 显示头像所请求的那个 URL？

访问不了。[https://i.loli.net/2020/08/03/y42EfgLvAT3pFih.jpg](url)

貌似就只有这一个皮肤会这样。。会是缓存问题吗
