### ISSUE TITLE
[错误] 请不要在 php.ini 中禁用任何函数。

### ISSUE THREAD

**Issue by GiriNeko** [bs-community/blessing-skin-server#218]
## The Problem 问题描述
我是从4.x升级到5.0的。
升级完后由500变成了[Error] Please don't disable any functions, which is specified in "php.ini" file.
[错误] 请不要在 php.ini 中禁用任何函数。我们不建议使用您使用宝塔等面板软件，因为容易引起兼容性问题。
但是我的环境可以运行上一个版本的BlessingSkin
难道这个版本需要新的函数依赖？

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): Latest. 5.0
- PHP 版本 (Version of PHP): 7.3
- Apache / Nginx: Nginx 
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): New Edge and /

## Error Message 错误信息
[Error] Please don't disable any functions, which is specified in "php.ini" file.
[错误] 请不要在 php.ini 中禁用任何函数。我们不建议使用您使用宝塔等面板软件，因为容易引起兼容性问题。

很抱歉，我没有看到相关日志。

**Comment by g-plane** [comment]
这不是写得挺清楚的吗……？就是不要禁用任何函数。

**Comment by GiriNeko** [comment]
问题是我没有禁用任何函数
我甚至没有动过php.ini

发送自 Windows 10 版邮件应用

发件人: Pig Fang
发送时间: 2020年8月5日 17:23
收件人: bs-community/blessing-skin-server
抄送: ギリ猫; Author
主题: Re: [bs-community/blessing-skin-server] [错误] 请不要在 php.ini 中禁用任何函数。 (#218)

这不是写得挺清楚的吗……？就是不要禁用任何函数。

**Comment by GiriNeko** [comment]
https://github.com/bs-community/blessing-skin-server/blob/master/README.md#%E7%8E%AF%E5%A2%83%E8%A6%81%E6%B1%82
并且我是照着这篇文档安装了php拓展

**Comment by g-plane** [comment]
你是不是在用宝塔？

**Comment by GiriNeko** [comment]
不，我是在Debian种用apt手动搭建的LNMP

发送自 Windows 10 版邮件应用

发件人: Pig Fang
发送时间: 2020年8月5日 18:43
主题: Re: [bs-community/blessing-skin-server] [错误] 请不要在 php.ini 中禁用任何函数。 (#218)

你是不是在用宝塔？

**Comment by g-plane** [comment]
检查一下 php.ini？

**Comment by GiriNeko** [comment]
发送自 Windows 10 版邮件应用

发件人: Pig Fang
发送时间: 2020年8月5日 18:47
收件人: bs-community/blessing-skin-server
抄送: ギリ猫; Author
主题: Re: [bs-community/blessing-skin-server] [错误] 请不要在 php.ini 中禁用任何函数。 (#218)

检查一下 php.ini？

**Comment by g-plane** [comment]
没有看到任何内容。如果需要贴配置文件或日志之类的，请放 pastebin。

**Comment by GiriNeko** [comment]
https://pastebin.com/CgDcQ4RW
这里我贴出了php.ini中disable_functions的字段
![image](https://user-images.githubusercontent.com/21117880/89404679-f5d3b480-d74c-11ea-8ad2-8f3a40e58752.png)

**Comment by g-plane** [comment]
这不是有一些被禁用的函数吗？把这些都去掉就可以了。

**Comment by GiriNeko** [comment]
fixed.
很好奇，这看上去都像是无关函数，也不知道哪条影响到了主题。
感谢。

**Comment by g-plane** [comment]
你上面列出的函数，BS 是没有用到的。而目前 BS 现在是不允许禁用任何函数，因为我们也没有办法保证现在和将来会使用哪些函数。

**Comment by GiriNeko** [comment]
了解了，
那这样的话不会造成安全问题吗？

发送自 Windows 10 版邮件应用

发件人: Pig Fang
发送时间: 2020年8月5日 19:03
收件人: bs-community/blessing-skin-server
抄送: ギリ猫; State change
主题: Re: [bs-community/blessing-skin-server] [错误] 请不要在 php.ini 中禁用任何函数。 (#218)

你上面列出的函数，BS 是没有用到的。而目前 BS 现在是不允许禁用任何函数，因为我们也没有办法保证现在和将来会使用哪些函数。

**Comment by g-plane** [comment]
要说 100% 安全当然是不可能的，但禁用函数与否并不会显著影响安全性，现在的 PHP 也没有以前那么脆弱了。
你可以换个角度想，假设这个软件是用 Node.js 或 Ruby 写的，这些并没有「禁用函数」这样的机制，但安全问题同样值得考虑。
