### ISSUE TITLE
皮肤站配置邮箱后无法正常加载

### ISSUE THREAD

**Issue by MoYanAce** [bs-community/blessing-skin-server#219]
在.env文件中配置完邮箱smtp部分后，网页将无法加载

- Blessing Skin 版本 (Version of Blessing Skin): 5.0.0
- PHP 版本 (Version of PHP): 7.4
- Apache / Nginx: Apache 2.4
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): Chrome/Edge/Firefox/IE 无

## Error Message 错误信息

没有日志

## Steps to Reproduce 重现步骤

根目录.env文件，配置smtp服务，配置完毕后并保存，不管你如何操作，都无法加载

**Comment by g-plane** [comment]
请在 pastebin 上贴出你的配置文件。

**Comment by MoYanAce** [comment]
> 请在 pastebin 上贴出你的配置文件。

https://paste.ubuntu.com/p/PFbbXk4V8G/

**Comment by g-plane** [comment]
把 `APP_DEBUG` 打开以获取可能的错误信息。

**Comment by MoYanAce** [comment]
> 把 `APP_DEBUG` 打开以获取可能的错误信息。

打开或关闭都没有错误信息，网站标题直接变成 https://网站域名 内容是空白的

**Comment by g-plane** [comment]
这我也无法帮你解决问题，因为信息不足。

**Comment by MoYanAce** [comment]
> 这我也无法帮你解决问题，因为信息不足。

好吧，感谢您的耐心解答
