### ISSUE TITLE
IIS的虚拟路径搭建皮肤站时无法显示网站资源

### ISSUE THREAD

**Issue by q56535** [bs-community/blessing-skin-server#223]
## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):5.1.0
- PHP 版本 (Version of PHP):7.2.33
- Apache / Nginx:Microsoft-IIS/10.0
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):主流浏览器，地址为正常皮肤站地址

## Error Message 错误信息

我使用iis的url重写，在内网的localhost地址可以正常显示皮肤站，但是到外网之后无法显示皮肤站的资源，例如：
![QQ截图20200827144445.png](https://i.loli.net/2020/08/27/Vz2fJilZ6GvERFH.png)
![QQ截图20200827145027.png](https://i.loli.net/2020/08/27/RpW3qyjfN7PtnEH.png)
![QQ截图20200827145041.png](https://i.loli.net/2020/08/27/wlBtFEdOMIhH3bA.png)
小部分人可以打开，不知与何有关，而且app/manifest.json可以打开，url重写的内容为.htaccess导入的，并且使用了虚拟路径，当把皮肤站设置为域名主页时，所有资源可以加载，而皮肤站设置到虚拟路径时，资源无法加载，推测是重写的问题，希望有人能指导我，并且如果是url重写问题，建议添加一个可以使用虚拟路径的配置以供选用。大概就这样了

**Comment by g-plane** [comment]
不支持  IIS。

**Comment by q56535** [comment]
IIS是可以搭建的，但是感觉虚拟路径的重写有问题

**Comment by g-plane** [comment]
你可以先试一试。
