### ISSUE TITLE
Please don't disable any functions

### ISSUE THREAD

**Issue by TheMrMes109** [bs-community/blessing-skin-server#224]
## Environment 运行环境

- Blessing Skin git clone https://github.com/bs-community/blessing-skin-server.git
- PHP 7,3
php.ini

; open_basedir, if set, limits all file operations to the defined directory
; and below. This directive makes most sense if used in a per-directory
; or per-virtualhost web server configuration file.
; Note: disables the realpath cache
; http://php.net/open-basedir
open_basedir = /var/www/skins/

; This directive allows you to disable certain functions for security reasons.
; It receives a comma-delimited list of function names.
; http://php.net/disable-functions
disable_functions =

; This directive allows you to disable certain classes for security reasons.
; It receives a comma-delimited list of class names.
; http://php.net/disable-classes
disable_classes =

; Colors for Syntax Highlighting mode. Anything that's acceptable in
; would work.
- Nginx:
server {
	listen 80;
	listen [::]:80;

	server_name domain.com;
    root /var/www/skins/public;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
	
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php7.3-fpm.sock;
    }

    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|flv|ico)$ {
        expires 30d;
        access_log off;
    }	
	
}
- GoogleCrome https://domain.com/setup

## Error Message 错误信息

[Error] Please don't disable any functions, which is specified in "php.ini" file.
[错误] 请不要在 php.ini 中禁用任何函数。我们不建议使用您使用宝塔等面板软件，因为容易引起兼容性问题。

**Comment by g-plane** [comment]
Hello, what can I help for you?

**Comment by TheMrMes109** [comment]
php.ini file as written in FAQ line disable_functions = (empty)

all dependencies are
OpenSSL PDO Mbstring Tokenizer GD XML Ctype JSON fileinfo zip

Why does the error appear?

**Comment by tnqzh123** [comment]
Which web server are you using? Have you restarted PHP-FPM after editing php.ini?

**Comment by TheMrMes109** [comment]
nginx

yes i reloaded php - service php7.3-fpm restart

**Comment by g-plane** [comment]
Could you show us your `phpinfo()`?

**Comment by TheMrMes109** [comment]
https://docs.google.com/document/d/15dVNYzWwsG-aS74Z7E9aMlUjZVlqw4b764IGYjF3Io0/edit?usp=sharing

**Comment by TheMrMes109** [comment]
I removed the php validation line from bootstrap / chkenv.php and everything seems to work: D

**Comment by g-plane** [comment]
Solved. Closing now.
