### ISSUE TITLE
在更新网站程序时返回严重错误

### ISSUE THREAD

**Issue by KJZH001** [bs-community/blessing-skin-server#226]
## The Problem 问题描述

问题1 在检查更新页面更新下载更新包时返回严重错误
问题2 配置生成插件从v2.3.0更新至v2.3.1后，访问配置生成页面返回500错误

抱歉，因为这是两个问题近乎同时发生了，log我也不太好重复提交两份，所以插件的问题我也只好一起放到这里来了

## Environment 运行环境

- Blessing Skin 版本 :v5.0.0 - Crescent Moon Dance(非自行构建)
- PHP 版本 :php7.3.4nts_p
- Apache / Nginx : Apache

- 什么浏览器，出现错误时的地址栏：
QQ浏览器Windows版 
- 问题1 http://skin.rcraft.ml:30000/admin/update
- 问题2 http://skin.rcraft.ml:30000/user/config

## Error Message 错误信息

日志信息 
https://pastebin.com/CsJPths3
错误截图
http://icdn.7t5j.cn/2020/08/29/86906bcd38052.png
http://icdn.7t5j.cn/2020/08/29/5819d0d082e4c.png

### 问题1 

- 前往检查更新
- 点击马上升级后不久出现

### 问题2

- 在后台插件市场中更新插件
- 返回前台用户中心，点击配置生成，出现500错误

**Comment by KJZH001** [comment]
还有就是pastebin.com这玩意我不太会用= =
文本类型也不太清楚有没有选错了，只能麻烦你们将就一下了，抱歉

**Comment by g-plane** [comment]
先把所有东西都升级到最新版再说。

**Comment by KJZH001** [comment]
> 先把所有东西都升级到最新版再说。

抱歉，我的皮肤站本体无法进行正常更新
以下是返回的错误内容，和先前的截图中的错误内容是相同的，此外这个错误曾经在我安装插件时也返回过

## 严重错误
The GET method is not supported for this route. Supported methods: POST.
### 详细信息
[1] app\Http\Middleware\DetectLanguagePrefer.php#L30
[2] app\Http\Middleware\ConvertEmptyStringsToNull.php#L23

**Comment by g-plane** [comment]
你可以在 GitHub 或其它更新源手动下载，然后解压覆盖原来的文件。

**Comment by KJZH001** [comment]
> 你可以在 GitHub 或其它更新源手动下载，然后解压覆盖原来的文件。

直接整个覆盖是吗？好的

**Comment by KJZH001** [comment]
> 你可以在 GitHub 或其它更新源手动下载，然后解压覆盖原来的文件。

现在的配置生成插件已经没有问题了，不过我又遇到了一些其他的bug，但是这些都是属于插件部分的，因此需要我重新开个issue在插件的仓库中吗？

**Comment by g-plane** [comment]
最好是这样。

**Comment by KJZH001** [comment]
在更新Oauth客户端核心时返回了如下的错误

## 严重错误
ZipArchive::extractTo(): File exists
## 详细信息
[1] app\Services\Unzip.php#L30
[2] app\Http\Controllers\MarketController.php#L69
[3] app\Http\Middleware\CheckRole.php#L22
[4] app\Http\Middleware\FireUserAuthenticated.php#L15
[5] app\Http\Middleware\EnsureEmailFilled.php#L17
[6] app\Http\Middleware\RejectBannedUser.php#L23
[7] app\Http\Middleware\RedirectToSetup.php#L28
[8] app\Http\Middleware\EnforceEverGreen.php#L23
[9] app\Http\Middleware\DetectLanguagePrefer.php#L30
[10] app\Http\Middleware\ConvertEmptyStringsToNull.php#L23

并且，如果我启用信任代理插件会导致全站500(非框架的500，是直接返回的服务器状态代码中的500内部错误)
这个问题在5.0.0正式版中也发生过

**Comment by KJZH001** [comment]
> 最好是这样。

好的

**Comment by KJZH001** [comment]
> 最好是这样。

现在我已经在插件仓库中提交了一个新的issue，所以这个issue我先关闭了
感谢您的帮助
