### ISSUE TITLE
安装时出现[应该是数据库的]错误

### ISSUE THREAD

**Issue by Liushilang** [bs-community/blessing-skin-server#230]
## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):5.1.1
- PHP 版本 (Version of PHP):7.3.4nts
- Apache / Nginx:Apache2.4.39
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): Google Chrome,  ./setup/finish

## Error Message 错误信息
![image](https://user-images.githubusercontent.com/60663465/92998347-e74a9b00-f54b-11ea-9f36-2acc762dbc71.png)

## Steps to Reproduce 重现步骤

phpstudy集成环境安装WAMP（至于为什么要选Apache，其实一开始我用的是nginx，但css加载不出来（或许吧））--->改.env.example去掉example(小数点留着）-->创建网站（设置根目录为./public）--->创建数据库--->访问ip/setup/ --->很正常的按页面上的信息填东西--->Table 'notifications' already exists---->解决，重新安装---->报错，解决不了了

我自己也尝试了很久，但始终不行。自己不熟悉环境部署，只能用集成环境。求开发者大大回复，本人其实也是想学习一下。

给开发者大大磕头了！！！

望回复。

**Comment by g-plane** [comment]
- 不能使用 phpStudy 或宝塔
- 尽量不要用 Windows，请使用 Linux

**Comment by g-plane** [comment]
长时间未收到反馈，现关闭 issue。
