### ISSUE TITLE
邮箱验证严重错误

### ISSUE THREAD

**Issue by SLAVRINGT** [bs-community/blessing-skin-server#236]
## The Problem 问题描述
使用找回密码功能验证邮箱时提示Malformed UTF-8 characters, possibly incorrectly encoded

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):5.1.1
- PHP 版本 (Version of PHP):7.3
- Apache / Nginx:Apache
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):Crome http://skin.ziesmc.top/auth/forgot

## Error Message 错误信息

![QQ截图20201004231709](https://user-images.githubusercontent.com/20715670/95019458-0397ae80-0698-11eb-8cb5-d7755ae4c9cc.png)

## Steps to Reproduce 重现步骤
进入登入界面
找回密码
输入邮箱验证码
发送
报错

**Comment by g-plane** [comment]
这可能与对面的邮件服务器有关。试试换别的邮局？

**Comment by SLAVRINGT** [comment]
我尝试在/app/helpers.php L44加入encode代码                 
'message' => mb_convert_encoding( $args[0], 'UTF-8', 'UTF-8,GBK,GB2312,BIG5' ),
目前可以正常使用邮箱服务器
我把issue close掉吧= =

**Comment by SLAVRINGT** [comment]
> 这可能与对面的邮件服务器有关。试试换别的邮局？

我尝试在/app/helpers.php L44加入encode代码
'message' => mb_convert_encoding( $args[0], 'UTF-8', 'UTF-8,GBK,GB2312,BIG5' ),
目前可以正常使用邮箱服务器
我把issue close掉吧= =
