### ISSUE TITLE
如何设置默认显示的语言

### ISSUE THREAD

**Issue by Andy-Chuck** [bs-community/blessing-skin-server#237]
可能是浏览器或CDN节点的原因，现在打开bs后会自动显示es_ES那个语言，请问如何设置默认显示的语言？

**Comment by g-plane** [comment]
- 如果用户已经登录，通过那个菜单切换语言就行。切换后 BS 会记住；
- 对于未登录的用户，就需要在 .env 文件里修改 fallback locale。
