### ISSUE TITLE
无法安装，setup页面访问反馈错误 log文件未生成

### ISSUE THREAD

**Issue by WorldHim** [bs-community/blessing-skin-server#238]
## The Problem 问题描述
访问网站反馈错误，无法进入 setup页面
## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):5.2.0
- PHP 版本 (Version of PHP):7.4
- Apache / Nginx:apache2
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):localhost 127.0.0.1 0.0.0.0
- mysql5.7
## Error Message 错误信息

make(Illuminate\Contracts\Http|Kernel::class); $response = &kernel->handle( $request = Illuminate\Http\Request::capture() ); $response->send(); $kernel->terminate($request, $response);
storage/logs/文件夹为空 权限为777
## Steps to Reproduce 重现步骤

正常安装其他服务，最后一步完成后访问localhost;0.0.0.0;127.0.0.1访问安装向导 首页等 反馈错误
参照 https://www.bilibili.com/video/BV1Xg4y187zx

**Comment by g-plane** [comment]
请根据我们的官方文档来进行安装。

**Comment by WorldHim** [comment]
根据官方文档安装：
依然报错
错误同上

**Comment by mikazukiaug** [comment]
操作系统是什么，是否使用了集成环境？

**Comment by mochaaP** [comment]
操作系统是什么？有没有使用集成环境？

**Comment by WorldHim** [comment]
Ubuntu 16.04.7
没有集成

**Comment by g-plane** [comment]
你能把完整的错误信息发出来吗？

**Comment by WorldHim** [comment]
emmmm
log 文件未生成
权限777

**Comment by mochaaP** [comment]
@WorldHim 请在网站根目录下 ls -lah，并反馈给我们。
或者，以 http 用户手动在命令行运行 php public/index.php 查看结果。

**Comment by WorldHim** [comment]
https://pastebin.com/u8whNMgz

**Comment by mochaaP** [comment]
@WorldHim 所有的文件都没有 owner 和 group。请手动 chown（记得 -R）。

**Comment by WorldHim** [comment]
emmmm，难为情的说一句怎么搞

**Comment by WorldHim** [comment]
不对啊
我的用户名设的是null 他的组就是null 所有者也是null

**Comment by mochaaP** [comment]
@WorldHim

**Comment by WorldHim** [comment]
？

**Comment by g-plane** [comment]
你没把你遇到的错误信息发出来。

不发或者已经没问题的话我就关闭 issue 了。

**Comment by WorldHim** [comment]
make(Illuminate\Contracts\Http|Kernel::class); $response = &kernel->handle( $request = Illuminate\Http\Request::capture() ); $response->send(); $kernel->terminate($request, $response);
log文件没有生成

**Comment by g-plane** [comment]
你能把错误页面截个图吗？

**Comment by WorldHim** [comment]
嗯，等等

**Comment by WorldHim** [comment]
![Uploading Snipaste_2020-10-21_12-25-24.png…]()

**Comment by WorldHim** [comment]
![Snipaste_2020-10-21_12-25-24](https://user-images.githubusercontent.com/68632311/96673218-958dff80-1398-11eb-9058-354449b2d026.png)

**Comment by g-plane** [comment]
多半是你的环境问题。但具体是环境哪里有问题，我就不清楚。
