### ISSUE TITLE
[求助] 验证码无法加载

### ISSUE THREAD

**Issue by SakuraTao2007** [bs-community/blessing-skin-server#239]
## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): 5.2.0
- PHP 版本 (Version of PHP): 7.4.0
- Apache / Nginx: Nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): 谷歌

## Error Message 错误信息

F12报错如下：
captcha:1 GET http://127.0.0.1:224/auth/captcha?v=1602942632172 500 (Internal Server Error)

## Steps to Reproduce 重现步骤

就是在注册页面时，无法加载yanzhengma验证码（我没调用谷歌验证）

**Comment by tnqzh123** [comment]
请提供 Laravel 日志。

**Comment by SakuraTao2007** [comment]
> 请提供 Laravel 日志。

具体如何操作嘞 xD

**Comment by tnqzh123** [comment]
https://blessing.netlify.app/report.html#%E6%88%91%E5%BA%94%E8%AF%A5%E6%8F%90%E4%BE%9B%E4%BB%80%E4%B9%88%E4%BF%A1%E6%81%AF%E7%BB%99%E5%BC%80%E5%8F%91%E8%80%85%E4%BB%A5%E5%B8%AE%E5%8A%A9%E8%B0%83%E8%AF%95%EF%BC%9F

合着说你连用户手册都不看？

**Comment by g-plane** [comment]
我猜你是没有安装 GD 这个 PHP 扩展？

**Comment by SakuraTao2007** [comment]
> https://blessing.netlify.app/report.html#%E6%88%91%E5%BA%94%E8%AF%A5%E6%8F%90%E4%BE%9B%E4%BB%80%E4%B9%88%E4%BF%A1%E6%81%AF%E7%BB%99%E5%BC%80%E5%8F%91%E8%80%85%E4%BB%A5%E5%B8%AE%E5%8A%A9%E8%B0%83%E8%AF%95%EF%BC%9F
> 
> 合着说你连用户手册都不看？

Debug的信息不知如何导出，share分享说不行

**Comment by SakuraTao2007** [comment]
> 我猜你是没有安装 GD 这个 PHP 扩展？

貌似是没有，用的BT(doge)

**Comment by tnqzh123** [comment]
> Debug的信息不知如何导出，share分享说不行

你直接把日志内容传到 https://paste.ubuntu.com 然后把链接发上来就行，最好是自己截取一下有用的内容。

以及，**宝 塔 是 垃 圾**。

**Comment by SakuraTao2007** [comment]
> > Debug的信息不知如何导出，share分享说不行
> 
> 你直接把日志内容传到 https://paste.ubuntu.com 然后把链接发上来就行，最好是自己截取一下有用的内容。
> 
> 以及，**宝 塔 是 垃 圾**。

https://paste.ubuntu.com/p/2ThQGbS3Nr/

**Comment by g-plane** [comment]
环境问题。解决方法请根据错误消息自行搜索相关资料。

**Comment by SakuraTao2007** [comment]
> 环境问题。解决方法请根据错误消息自行搜索相关资料。

好吧，我慢慢摸索
