### ISSUE TITLE
详细信息：无法连接至 MySQL/MariaDB 服务器，请检查你的配置。服务器返回的信息：could not find driver

### ISSUE THREAD

**Issue by Yizhao666** [bs-community/blessing-skin-server#242]
## The Problem 问题描述

详细信息：无法连接至 MySQL/MariaDB 服务器，请检查你的配置。服务器返回的信息：could not find driver
所有依赖已安装
没有禁用的函数

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):5.2.0/5.1.1
- PHP 版本 (Version of PHP):php7.4-fpm
- Apache / Nginx:nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):chrome /setup/database

## Error Message 错误信息
详细信息：无法连接至 MySQL/MariaDB 服务器，请检查你的配置。服务器返回的信息：could not find driver

## Steps to Reproduce 重现步骤
安装向导->出错

**Comment by g-plane** [comment]
请贴出你的 ,env 文件。

**Comment by g-plane** [comment]
出现这种错误通常是以下这两种情况：
- `.env` 文件中的 `DB_CONNECTION` 写错误了
- PHP 没有配置好 PDO 扩展以及 pdo-mysql。
