### ISSUE TITLE
在不能注册模式下的内部注册api

### ISSUE THREAD

**Issue by msj20080623** [bs-community/blessing-skin-server#246]
几分钟前我发了一个相似的你们似乎没听懂

就是皮肤站不是有禁止注册开关吗？我就需要一个内部注册api，比如在我的一系列产品中，只需注册一样，其他的就会自动注册

**Comment by msj20080623** [comment]
再我下次回复前希望先不要关闭

**Comment by tnqzh123** [comment]
讲道理这不就是「数据对接」么……

你可以在你的其它产品中使用和 BS 一样的数据表结构，然后多个程序使用同一个表就行了。

**Comment by msj20080623** [comment]
关闭吧
