### ISSUE TITLE
Support to PHP 8.0

### ISSUE THREAD

**Issue by EdisonJwa** [bs-community/blessing-skin-server#247]
## The Problem 问题描述

Please add support to PHP 8.0 

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): **5.2.0**
- PHP 版本 (Version of PHP): **8.0**
- Apache / Nginx: **1.19.0**
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): Chrome

## Error Message 错误信息

<details>
<summary>Details</summary>

```php
Symfony\Component\ErrorHandler\Error\FatalError
Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs)

```

`vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php`

</details>

## Steps to Reproduce 重现步骤

Just run the website with PHP 8.0 and you'll get it

**Comment by g-plane** [comment]
PHP 8 支持已在计划中，敬请期待。

**Comment by hs-err** [comment]
https://learnku.com/laravel/t/52822

**Comment by g-plane** [comment]
如果仍然遇到问题，欢迎报告。
