### ISSUE TITLE
可以添加一个获取用户皮肤头像的api吗

### ISSUE THREAD

**Issue by luluxiaoyu** [bs-community/blessing-skin-server#249]
可以添加一个获取用户皮肤的api吗
我在服务器中用了litebans插件，需要用用户名调用用户头像

**Comment by g-plane** [comment]
BS 不存在「用户名」这一概念。不过，你可以通过 UID 或角色名来获取头像。

**Comment by luluxiaoyu** [comment]
是的我需要角色id获取
请问api地址是？

**Comment by g-plane** [comment]
具体可以看手册，手册写得很详细。
