### ISSUE TITLE
[建议]安装时进行对 .env 文件中数据库连接配置的检查

### ISSUE THREAD

**Issue by tnqzh123** [bs-community/blessing-skin-server#25]
在全新安装 v4 时，尽管在 `.env` 中已经配置过了数据库连接信息，安装向导仍会要求填写数据库连接信息。

我的建议是在分发时，`.env.example` 文件中关于数据库连接的配置项的值留空，在安装时检查对应配置项的值是否非空。若为空或非空但无法连接至数据库服务器，则要求用户填写数据库连接信息（后一种情况最好给出无法连接至数据库的提示），若不为空且可以连接至数据库服务器则直接填写管理员信息。

**Comment by g-plane** [comment]
不错的建议！另外下面那里应该是「`.env`」吧？

**Comment by tnqzh123** [comment]
> 另外下面那里应该是「.env」吧？

这就是另一个问题了。

我直接 pull 下来的源码里还是只有 `.env.example` 和 `.env.testing`，若不将 `.env.example` 重命名为 `.env`，访问首页时会报告数据库连接异常，而不是跳转到 `/setup` 执行安装向导。如果直接访问 `/setup` 是可以执行安装向导，但是在填写完数据库连接信息之后会报错：
```
File does not exist at path ../.env
```

**Comment by g-plane** [comment]
.env 只会出现在发行包中，从 GitHub 上 pull 下来是没有的，必须手动重命名。
