### ISSUE TITLE
[提问] 实现 BlessingSkin 皮肤站与 WordPress 网站的数据库互通

### ISSUE THREAD

**Issue by RisingInIris2017** [bs-community/blessing-skin-server#250]
这篇 issue 并不是 bug 反馈，只询问一个手册上没有提及的问题。
因此 issue 中不包含报错。
## The Problem 问题描述
我的服务器使用 WordPress 搭建了官方网站，并在 WP 下实现了玩家用户名（游戏ID）、密码、邮箱的数据库。
已经设置了 Authme 服务端插件使用 WP 的数据库进行 mc 服务器内的登录验证。

现在想使用 Blessing Skin 搭建皮肤站，想问能否需要实现 BlessingSkin 与 WordPress 的数据库直接对接？
或者是只需要与Authme对接即可？

我仔细阅读过手册，手册上应该只提及了与论坛程序，如 Discuz!, Flaurm 等的对接，
并没有提及与 WordPress 数据互通的实现方式。

在这里想询问一下在如上文提到的服务器环境下，如何实现 BlessingSkin，WordPress 与 Authme 三者的互联互通？
先在这里感谢开发者们的耐心指导和帮助！
## Environment 运行环境
- Blessing Skin 版本 (Version of Blessing Skin): v5.2.0
- PHP 版本 (Version of PHP): PHP 7.3
- Apache / Nginx:  Apache 2.4
- MySQL 版本: 5.7

**Comment by tnqzh123** [comment]
@RisingInIris2017 如果你已经把 WP 和 AuthMe 对接好了，那 BS 直接和 AuthMe 对接就行，理论上是行得通的。

这边更推荐用 OAuth，如果你知道怎么做的话。

**Comment by g-plane** [comment]
可以考虑加入我们的 Telegram 群组讨论。
