### ISSUE TITLE
500

### ISSUE THREAD

**Issue by TunaFish2K** [bs-community/blessing-skin-server#251]
(1/1) InvalidArgumentExceptionView [setup.wizard.welcome] not found.
--
in FileViewFinder.php line 137
at FileViewFinder->findInPaths()in FileViewFinder.php line 79
at FileViewFinder->find()in Factory.php line 131
at Factory->make()in ViewController.php line 37
at ViewController->__invoke()
at call_user_func_array()in Controller.php line 54
at Controller->callAction()in ControllerDispatcher.php line 45
at ControllerDispatcher->dispatch()in Route.php line 219
at Route->runController()in Route.php line 176
at Route->run()in Router.php line 680
at Router->Illuminate\Routing\{closure}()in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}()in CheckInstallation.php line 16
at CheckInstallation->handle()in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}()in SubstituteBindings.php line 41
at SubstituteBindings->handle()in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}()in RedirectToSetup.php line 28
at RedirectToSetup->handle()in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}()in EnforceEverGreen.php line 23
at EnforceEverGreen->handle()in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}()in VerifyCsrfToken.php line 75
at VerifyCsrfToken->handle()in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}()in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle()in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}()in StartSession.php line 56
at StartSession->handle()in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}()in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle()in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}()in EncryptCookies.php line 66
at EncryptCookies->handle()in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}()in Pipeline.php line 104
at Pipeline->then()in Router.php line 682
at Router->runRouteWithinStack()in Router.php line 657
at Router->runRoute()in Router.php line 623
at Router->dispatchToRoute()in Router.php line 612
at Router->dispatch()in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}()in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}()in DetectLanguagePrefer.php line 30
at DetectLanguagePrefer->handle()in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}()in TransformsRequest.php line 21
at TransformsRequest->handle()in ConvertEmptyStringsToNull.php line 23
at ConvertEmptyStringsToNull->handle()in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}()in TransformsRequest.php line 21
at TransformsRequest->handle()in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}()in CheckForMaintenanceMode.php line 62
at CheckForMaintenanceMode->handle()in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}()in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}()in Pipeline.php line 104
at Pipeline->then()in Kernel.php line 151
at Kernel->sendRequestThroughRouter()in Kernel.php line 116
at Kernel->handle()in index.php line 57

**Comment by g-plane** [comment]
没有足够的有效信息。
