### ISSUE TITLE
[Enhancement]能否添加自定义验证邮件样式功能?

### ISSUE THREAD

**Issue by DreamUniverse843** [bs-community/blessing-skin-server#254]
这并非一个bug报告的issue，本文中不包含bug信息。

`<?php
namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;

class EmailVerification extends Mailable
{
    use Queueable;
    use SerializesModels;

    public $url;

    public function __construct($url)
    {
        $this->url = $url;
    }

    public function build()
    {
        $site_name = option_localized('site_name');

        return $this
            ->subject(trans('user.verification.mail.title', ['sitename' => $site_name]))
            ->view('mails.email-verification');
    }
}`

我实在是没找到自定义验证邮件样式的位置...
我想在现在的纯文本验证邮件里面插入一个自定义的图片文件，但是我连邮件模板都没找着......
感谢各位的付出，辛苦开发者们加以指点！

### Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): v5.2.0
- PHP 版本 (Version of PHP): PHP 7.3
- Apache / Nginx: Apache 2.4
- MySQL 版本: 5.7

**Comment by mochaaP** [comment]
@DreamUniverse843 https://t.me/blessing_skin/168852

找到 resources/views/overrides 目录，按照 resources/views 下的同样目录结构创建对应的视图。
