### ISSUE TITLE
皮肤库无法显示预览图片

### ISSUE THREAD

**Issue by XiaoZhouCn** [bs-community/blessing-skin-server#256]
## The Problem 问题描述
无法显示皮肤预览图片，玩家头像也无法显示
皮肤站其余功能全部正常
https://github.com/printempw/blessing-skin-server/issues/46 的解决方法已经修改过，没有效果。
## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):v3.5.0
- PHP 版本 (Version of PHP):7.2
- Apache / Nginx:Nginx 2.3.2 1.17.3
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):Google Chrome（其他一些浏览器下也出现同样错误，如火狐、360等）；IP/skinlib
## Error Message 错误信息
![image](https://user-images.githubusercontent.com/71212726/104112255-66e44d00-5327-11eb-9a8c-b4dd997c5614.png)

## Steps to Reproduce 重现步骤
安装->设置个性化->上传皮肤->出错

**Comment by g-plane** [comment]
我们已经不再提供对 3.5.0 的支持，请安装 v5 版本。

**Comment by Restent** [comment]
@XiaoZhouCn https://blessing.netlify.app/upgrade-guide.html
