### ISSUE TITLE
某些皮膚圖片上傳后皮膚庫頁面無法正常預覽

### ISSUE THREAD

**Issue by mitokohaku** [bs-community/blessing-skin-server#257]
## The Problem 问题描述
某些皮膚在皮膚庫頁面中無法正常顯示，直接預覽圖片顯示錯誤：錯誤500 详细信息：imagecolorat(): 43,52 is out of bounds

## Environment 运行环境
- Blessing Skin 版本 (Version of Blessing Skin): 5.2.0
- PHP 版本 (Version of PHP):7.4.12
- Apache / Nginx:Nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):  Chrome/87.0.4280.141
- URL：https://login.nekomc.net/skinlib?filter=skin&sort=time&page=2
- 具體出錯圖片URL：https://login.nekomc.net/preview/3?height=150

## Error Message 错误信息
![QQ截图20210112160411](https://user-images.githubusercontent.com/42205627/104286699-5df2a780-54f0-11eb-992a-aa850b1d5f94.png)
![QQ截图20210112160422](https://user-images.githubusercontent.com/42205627/104286704-5fbc6b00-54f0-11eb-8970-6bddb70e6293.png)

## Steps to Reproduce 重现步骤
玩家上傳皮膚→上傳成功→直接打開皮膚庫→該皮膚預覽錯誤
出錯皮膚文件本體：
![8fb65d1000bf9b1b0be122d3deb91aceea686ddc087534eb84102380ece7c93a](https://user-images.githubusercontent.com/42205627/104286556-2be14580-54f0-11eb-9bd1-5d09b439d014.png)

**Comment by tnqzh123** [comment]
这是材质模型选择错误造成的，通常是 Slim 模型（Alex 模型，3px 手臂的材质在上传时选择了 Default 模型（Steve 模型，4px 手臂）。

修改材质模型后即可正常生成 2D 预览图。

**Comment by mitokohaku** [comment]
已修復，感謝。
