### ISSUE TITLE
皮肤站在皮肤库预览不正常 但预览具体皮肤可以看

### ISSUE THREAD

**Issue by Guyao146** [bs-community/blessing-skin-server#258]
## The Problem 问题描述
没有Error 只是皮肤站变成了这样
https://s3.ax1x.com/2021/01/25/sqqshQ.png
但是具体预览可以看
https://s3.ax1x.com/2021/01/25/sqq2Xq.png

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):5.2.0
- PHP 版本 (Version of PHP):7.4
- Apache / Nginx:apache
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): edge新版 URL http://pfz.mcylyr.cn/skinlib?filter=skin&sort=time&page=1

## Steps to Reproduce 重现步骤

迁移了下皮肤站然后更新到5.2.0就成这样了

**Comment by g-plane** [comment]
请你直接访问这些预览图的链接，看看有什么报错。

**Comment by Guyao146** [comment]
> 请你直接访问这些预览图的链接，看看有什么报错。

没报错 啊这 我看了我的皮肤

**Comment by g-plane** [comment]
是在这些预览图上右键点开菜单，选择「在新标签页显示图像」。

**Comment by Guyao146** [comment]
> 是在这些预览图上右键点开菜单，选择「在新标签页显示图像」。

正常的 https://imgchr.com/i/sqL3D0

**Comment by g-plane** [comment]
你没有正确理解我的意思……不是直接在新标签页打开链接，是在新标签页显示图像，这两个是不同的。

**Comment by Guyao146** [comment]
> 你没有正确理解我的意思……不是直接在新标签页打开链接，是在新标签页显示图像，这两个是不同的。
您指的是这个嘛？ https://imgchr.com/i/sqLIqP

**Comment by g-plane** [comment]
![图片](https://user-images.githubusercontent.com/17216317/105661356-26c8c100-5f08-11eb-8827-371835601a4d.png)

**Comment by Guyao146** [comment]
出现500错误了 https://imgchr.com/i/sqv3z4

**Comment by mochaaP** [comment]
@Guyao146 您的 fileinfo 扩展未打开，请检查 php.ini。

**Comment by Guyao146** [comment]
> @Guyao146 您的 fileinfo 扩展未打开，请检查 php.ini。

解决了！谢谢你！
