### ISSUE TITLE
生存APPkey出错？

### ISSUE THREAD

**Issue by xiaozhiyl** [bs-community/blessing-skin-server#259]
- Blessing Skin 版本 (Version of Blessing Skin):5.2.0
- PHP 版本 (Version of PHP):7.4
- Apache / Nginx:Nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):QQ浏览器

## Error Message 错误信息
![image](https://user-images.githubusercontent.com/57853246/105802791-d139f600-5f93-11eb-9392-8487b152ff8c.png)

我运行php artisan key:generate这个命令就直接出现这个出错了 解决问题上面也没有写这个出错的解决方式

**Comment by tnqzh123** [comment]
@xiaozhiyl ？

> 解决问题上面也没有写这个出错的解决方式

https://blessing.netlify.app/faq.html#xxx-has-been-disabled-for-security-reasons

**Comment by xiaozhiyl** [comment]
![image](https://dl.xzyla.com/pf.png)
显示这样的报错？输入php artisan key:generate这个命令后

**Comment by xiaozhiyl** [comment]
运行php artisan key:generate这个命令就直接出现这个出错了 图片位置：[点我](https://dl.xzyla.com/pf.png)
