### ISSUE TITLE
ygg-api和authlib-injector出现cookie报错问题

### ISSUE THREAD

**Issue by Miuss** [bs-community/blessing-skin-server#260]
## The Problem 问题描述
Blessing-skin-server配合(https://github.com/yushijinhun/authlib-injector)服务器使用出现cookie报错不知道是不是yggapi问题

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):v5.2.0
- PHP 版本 (Version of PHP):7.4
- Apache / Nginx:Nginx

## Error Message 错误信息
![image](https://user-images.githubusercontent.com/26337587/105848414-d704fb00-5fd6-11eb-806c-35bcba11cbd1.png)

## Steps to Reproduce 重现步骤
![image](https://user-images.githubusercontent.com/26337587/105848429-de2c0900-5fd6-11eb-901b-4c43292f8057.png)

**Comment by yushijinhun** [comment]
这个问题似乎与 blessing-skin-server 无关，并且你已经在 authlib-injector 项目提过这个问题了 (yushijinhun/authlib-injector#101)，因此将此 issue 关闭。
