### ISSUE TITLE
MySQL迁移至PostgreSQL后注册出现问题

### ISSUE THREAD

**Issue by CraftDream** [bs-community/blessing-skin-server#261]
## The Problem 问题描述

MySQL迁移至PostgreSQL后注册出现问题

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):5.1.0
- PHP 版本 (Version of PHP):7.3
- Apache / Nginx:Apache
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):谷歌浏览器 http://admin.5imczy.cn:1322/auth/register

## Error Message 错误信息

![报错](https://user-images.githubusercontent.com/47418954/106230045-a072ee80-6229-11eb-953f-b74ea537d863.png)

## Steps to Reproduce 重现步骤

打开皮肤站，填写信息注册

**Comment by CraftDream** [comment]
```
严重错误
SQLSTATE[23502]: Not null violation: 7 错误: null value in column "uid" of relation "users" violates not-null constraint DETAIL: 失败, 行包含(null, 11111@qq.com, 11111, null, 20, 0, $SHA$859ae20178d789f7$6072a10cb37cdc896a48b14dd8175bd74b2b600de0..., 172.16.0.1, 0, 2021-01-28 11:28:09, 2021-01-29 11:28:09, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null). (SQL: insert into "users" ("email", "nickname", "score", "avatar", "password", "ip", "permission", "register_at", "last_sign_at") values (11111@qq.com, 11111, 20, 0, $SHA$859ae20178d789f7$6072a10cb37cdc896a48b14dd8175bd74b2b600de0d74d33323f2606dedb4c54, 172.16.0.1, 0, 2021-01-29 11:28:09, 2021-01-28 11:28:09) returning "uid")
详细信息
[1] app\Http\Controllers\AuthController.php#L208
[2] app\Http\Middleware\RedirectIfAuthenticated.php#L11
[3] app\Http\Middleware\RedirectToSetup.php#L28
[4] app\Http\Middleware\EnforceEverGreen.php#L23
[5] app\Http\Middleware\DetectLanguagePrefer.php#L30
[6] app\Http\Middleware\ConvertEmptyStringsToNull.php#L23
```

**Comment by g-plane** [comment]
难得出现 PostgreSQL 用户。

正常来讲，uid 是不会出现空值的，会不会是有其它地方的数据导入然后出现空值？或者迁移过程中数据有没有问题？

**Comment by CraftDream** [comment]
> 难得出现 PostgreSQL 用户。
> 
> 正常来讲，uid 是不会出现空值的，会不会是有其它地方的数据导入然后出现空值？或者迁移过程中数据有没有问题？

用的Navicat的数据传输迁移的，应该数据没有问题的

**Comment by CraftDream** [comment]
> 难得出现 PostgreSQL 用户。
> 
> 正常来讲，uid 是不会出现空值的，会不会是有其它地方的数据导入然后出现空值？或者迁移过程中数据有没有问题？

接下来我应该做什么？我玩家都还等着要注册hhh

**Comment by CraftDream** [comment]
> 难得出现 PostgreSQL 用户。
> 
> 正常来讲，uid 是不会出现空值的，会不会是有其它地方的数据导入然后出现空值？或者迁移过程中数据有没有问题？

之前换PostgreSQL是因为mysqld吃我100%CPU

**Comment by g-plane** [comment]
是只有少数几条数据有问题吗？如果是，看看能不能先从旧数据库那里补上

**Comment by CraftDream** [comment]
> 是只有少数几条数据有问题吗？如果是，看看能不能先从旧数据库那里补上。

数据没有问题，只是注册不了

**Comment by g-plane** [comment]
这就比较奇怪了……但是现在我暂时没有拿 PostgreSQL 测试的条件。

**Comment by CraftDream** [comment]
> 这就比较奇怪了……但是现在我暂时没有拿 PostgreSQL 测试的条件。

你需要在我皮肤站上测试吗？我玩家注册不了，比较急的，我也不知道该怎么办了

**Comment by CraftDream** [comment]
```
[DTF] Data Transfer started
[DTF] 0> Getting tables
[DTF] 1> invitation_codes: Getting table structure
[DTF] 2> jobs: Getting table structure
[DTF] 3> language_lines: Getting table structure
[DTF] 4> migrations: Getting table structure
[DTF] 1> invitation_codes: Fetching records
[DTF] 1> invitation_codes: Drop table
[DTF] 3> language_lines: Fetching records
[DTF] 2> jobs: Fetching records
[DTF] 2> jobs: Drop table
[DTF] 3> language_lines: Drop table
[DTF] 1> invitation_codes: Create table
[DTF] 3> language_lines: Create table
[ERR] 3> CREATE TABLE `language_lines`  (
  `id` int NOT NULL,
  `group` varchar(255) NOT NULL,
  `key` varchar(255) NOT NULL,
  `text` longtext NOT NULL,
  `created_at` datetime NULL,
  `updated_at` datetime NULL,
  PRIMARY KEY (`id`),
  INDEX `language_lines_group_index`(`"group"`) USING BTREE
)
[ERR] 3> 1072 - Key column '"group"' doesn't exist in table
[DTF] 5> mojang_verifications: Getting table structure
[DTF] Process terminated
```
我用Navicat要把PostgreSQL迁移到MySQL的时候出了这个错误

**Comment by CraftDream** [comment]
石锤乐健了就是PostgreSQL的问题，我刚换MySQL又能注册了

**Comment by g-plane** [comment]
要不先用着 MySQL 吧？感觉你的皮肤站用户数量、访问量不至于搞到这么高的占用。

**Comment by CraftDream** [comment]
> 不至于

用户量三千多，但我的mysqld经常占到100%CPU，会不会是Blessingskin有慢sql语句

**Comment by CraftDream** [comment]
> 要不先用着 MySQL 吧？感觉你的皮肤站用户数量、访问量不至于搞到这么高的占用。

![MySQL数据库吃cpu](https://user-images.githubusercontent.com/47418954/106259257-f3fd3080-6259-11eb-816c-c9d1fb2fea91.png)

**Comment by Rabbit0w0** [comment]
> 要不先用着 MySQL 吧？感觉你的皮肤站用户数量、访问量不至于搞到这么高的占用。

它是如何分配Uid的

**Comment by g-plane** [comment]
整数自增。

**Comment by Rabbit0w0** [comment]
> 整数自增。

Thx 修好了

**Comment by g-plane** [comment]
所以只是数据表的字段没有设置好？

**Comment by Rabbit0w0** [comment]
并不是，卡在了AuthController.php第208行，我解决了MySQL的占用问题，勉勉强强用MySQL垫上去了

**Comment by Rabbit0w0** [comment]
issue反应的问题仍未解决，希望可以尽快修理

**Comment by g-plane** [comment]
我刚刚用 PostgreSQL 测试了，注册正常，没有遇到问题。

另外不建议使用 Windows 系统。

**Comment by CraftDream** [comment]
> 我刚刚用 PostgreSQL 测试了，注册正常，没有遇到问题。
> 
> 另外不建议使用 Windows 系统。

估计是数据迁移的问题

**Comment by CraftDream** [comment]
另外，我解决了mysqld进程cpu占用过高以及皮肤站访问过慢的问题

**Comment by CraftDream** [comment]
> 另外，我解决了mysqld进程cpu占用过高以及皮肤站访问过慢的问题

是authme数据同步插件的问题，SyncWithAuthme里面的问题，我一开始发现关闭这个插件cpu正常了，访问速度变快了，但是密码无论如何都错误，后来我看了代码，是这个插件修改了密码格式，所以我干脆把SyncWithAuthme删掉了，这个插件保持开启，一切问题都解决了。

**Comment by CraftDream** [comment]
估计是SyncWithAuthme里面存在一些慢查询语句，希望相关开发者可以优化。

**Comment by g-plane** [comment]
嗯……干脆别用这个插件吧，这类数据同步插件的或多或少有问题，它的存在本身就是个问题。

**Comment by g-plane** [comment]
大概找到原因了，我试试能不能修复。

**Comment by CraftDream** [comment]
那么新开的flarum论坛应该怎么使用皮肤站的账号密码登录，在authme数据同步插件修改过密码格式后

**Comment by g-plane** [comment]
如果要对接 Flarum 论坛，请用我们专为 Flarum 开发的 Flarum 扩展，而不是使用「论坛对接」插件。

**Comment by Rabbit0w0** [comment]
草 还有flarum的插件

**Comment by g-plane** [comment]
AuthMe 对接插件已更新。如果插件有问题，请在插件的仓库开新 issue。
