### ISSUE TITLE
怎么设置邮箱用于发送验证信息？

### ISSUE THREAD

**Issue by WHY-Studio** [bs-community/blessing-skin-server#262]
## The Problem 问题描述

想询问一下如何正确的设置邮箱，setup的时候没有要求填写验证码发送所要用的邮箱，安装指南里也没写，于是自己填写了.env文件中的邮件部分。

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):v5.2.0
- PHP 版本 (Version of PHP):PHP-7.3
- Apache / Nginx:Nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):http://我的域名/auth/forgot
- 浏览器信息：
```
Google Chrome | 88.0.4324.104 (正式版本) （64 位） (cohort: Stable)
-- | --
修订版本 | 17905c015d3376dee9cce5dd079a3f4fa906e060-refs/branch-heads/4324_96@{#3}
操作系统 | Windows 10 OS Version 1909 (Build 18363.1316)
JavaScript | V8 8.8.278.14
用户代理 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
```

## Error Message 错误信息

红色弹窗弹出：
严重错误
readfrom tcp 192.168.1.7:56392->111.67.207.43:6677: http: invalid Read on closed Body
（不知道怎么上传截图，反正就只有一个红框，死活收不到重置密码的邮件，在发送验证码的邮箱里的已发送中也没查到邮件）

## Steps to Reproduce 重现步骤

重置密码，输入了正确的邮箱和验证码，但就是无法发送邮件。

## 补充说明

如果有信息不足，请告知我，我会尽可能的提供信息

**Comment by g-plane** [comment]
我觉得你没有正确在 .env 文件里配置邮箱相关的设置，具体请参考手册。

**Comment by WHY-Studio** [comment]
> 我觉得你没有正确在.env文件里配置邮箱相关的设置，具体请参考手册。

邮箱设置在用户手册里的哪一页？我翻了好几遍没找到，能否提供URL？

**Comment by g-plane** [comment]
你自己看看好吧？不要做伸手党。

**Comment by WHY-Studio** [comment]
哦，谢谢。找到相关帮助了，我把加密方式填错了，抱歉。
