### ISSUE TITLE
API无法返回正确的token

### ISSUE THREAD

**Issue by Rabbit0w0** [bs-community/blessing-skin-server#263]
## The Problem 问题描述

blessing api 无法返回正确的令牌

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): v5.2.0
- PHP 版本 (Version of PHP): 7.3.4
- Apache / Nginx: Apache
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): Python, ~/api/auth/login

## Steps to Reproduce 重现步骤

写一个api测试程序
```python
from requests import post
param = {'email':'~@qq.com','password':'~'}
txt = post('http://~/api/auth/login',json=param)
print(txt.text)
```
确保密码正确
![image](https://user-images.githubusercontent.com/21006278/106436442-0de38100-64af-11eb-97db-c3f40940df68.png)

**Comment by g-plane** [comment]
之前不只一次收到这个问题报告，但我一直无法重现这个问题，无论是我本地的开发环境还是 LittleSkin。

**Comment by Rabbit0w0** [comment]
> 之前不只一次收到这个问题报告，但我一直无法重现这个问题，无论是我本地的开发环境还是 LittleSkin。

测试链接 http://admin.5imczy.cn:1322/ 你可以自己试试

如果有需要 我可以提供我们服务器上运行的副本

**Comment by g-plane** [comment]
不过由于 `tymon/jwt-auth` 依赖的维护状况不理想，JWT 功能目前已在 v6 中被移除。所以这个问题要到 `tymon/jwt-auth` 包达到可以被重新添加进来的条件再考虑。
