### ISSUE TITLE
在皮肤站上传皮肤时提示 500 Internal Server Error

### ISSUE THREAD

**Issue by xiao-gy** [bs-community/blessing-skin-server#264]
## The Problem 问题描述

在皮肤站上传皮肤时提示`500 Internal Server Error`

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): 5.2.0
- PHP 版本 (Version of PHP): 7.4.0
- Apache / Nginx: Nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): https://skin.xiao-gy.top/skinlib/upload

## Error Message 错误信息

```
stack traceback:
coroutine 0:
	[C]: in function 'socket'
	/www/common/waf_lua//access_ctrl.lua:674: in function 'post'
	/www/common/waf_lua//access_ctrl.lua:840: in main chunk, client: ******, server: example.com, request: "POST /texture HTTP/2.0", host: "example.com", referrer: "https://example.com/skinlib/upload"

```
## Steps to Reproduce 重现步骤

上传皮肤

**Comment by g-plane** [comment]
看起来是 Nginx 报的错，是不是 Nginx 哪里配置出问题了？

**Comment by xiao-gy** [comment]
和没有配置`client_body_temp_path`有关吗，我不是很懂

**Comment by g-plane** [comment]
建议自行搜索相关资料？我不是 Nginx 专家。

**Comment by xiao-gy** [comment]
好吧，谢谢了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Pig Fang"<notifications@github.com&gt;; 
发送时间: 2021年2月5日(星期五) 中午1:53
收件人: "bs-community/blessing-skin-server"<blessing-skin-server@noreply.github.com&gt;; 
抄送: "xiao-gy"<wgy20050420@gmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [bs-community/blessing-skin-server] 在皮肤站上传皮肤时提示 500 Internal Server Error (#264)





 
建议自行搜索相关资料？我不是 Nginx 专家。
 
&mdash;

**Comment by hempflower** [comment]
应该是nginx配置了防火墙类的保护脚本。
