### ISSUE TITLE
功能请求：披风预览时可以预览鞘翅

### ISSUE THREAD

**Issue by poly000** [bs-community/blessing-skin-server#265]
我希望做一个高清披风皮肤模板 通过预览功能……
因为我找不到2000x1000的有鞘翅的mc带鞘翅披风模板（精确到像素）

**Comment by g-plane** [comment]
这属于 skinview3d 的功能，相关功能以被实现。但 skinview3d 的 v2 仍处于 beta 阶段，待正式版发布够我们会更新。
