### ISSUE TITLE
可否在安装程序中增加对 MariaDB 5.5 / MySQL 5.5 的支持

### ISSUE THREAD

**Issue by Xasdas** [bs-community/blessing-skin-server#266]
## The Problem 问题描述

一直以来都在小内存VPS中使用MariaDB 5.5
我**已经成功在MariaDB 5.5.68运行Blessing Skin Server**，看起来运行无任何问题。
问题仅仅是**安装程序无法在MariaDB 5.5下成功安装**，尽管启用了large_prefix和barracuda。
安装过程中依然是max key length is 767 bytes。
搜索资料和研究数据表后，发现只在ROW_FORMAT是DYNAMIC或COMPRESSED时支持更长的bytes。
然而安装的默认ROW_FORMAT是COMPACT
所以解决方法只要是在CREATE TABLE时增加ROW_FORMAT=DYNAMIC参数就可以了
考虑过直接修改安装程序php文件加入ROW_FORMAT=DYNAMIC，然而没编程基础的我发现完全看不懂。
也想过修改数据库默认ROW_FORMAT然而发现MariaDB 5.5无法修改建表的默认ROW_FORMAT...

最后解决方法是，先在MariaDB 10.4环境下安装了Blessing Skin Server。
然后导出数据库，修改导出的sql文件，在每个CREATE TABLE里都加入ROW_FORMAT=DYNAMIC，
然后在MariaDB 5.5中导入，完美运行没有问题。

所以只要在安装程序中CREATE TABLE增加参数ROW_FORMAT=DYNAMIC就可以支持MariaDB 5.5了。

注：需要修改MariaDB 5.5配置文件 新增
innodb_large_prefix = true （或者 innodb_large_prefix = 1，而非更高版本的 innodb_large_prefix = on）
innodb_file_format = barracuda

以上安装过程给还在使用MariaDB 5.5的用户作为参考，我知道已经EOL很久了，反正我已经装上了，不增加这个支持也行（？

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): 5.2.0
- MariaDB 版本 (Version of MariaDB): 5.5.68 with innodb_large_prefix = true & innodb_file_format = barracuda

## Error Message 错误信息

max key length is 767 bytes

## Steps to Reproduce 重现步骤

在MariaDB 5.5环境中安装

**Comment by g-plane** [comment]
如果你有小内存的需求，为什么不考虑 SQLite 呢？

另外对于已 EOL 的软件还继续提供支持，你知道这意味着什么吗？

**Comment by Xasdas** [comment]
> 如果你有小内存的需求，为什么不考虑 SQLite 呢？

因为我是什么都不懂的小白，使用国产面板一键安装LNMP，默认安装MariaDB 5.5，还附带自动安装PhpMyAdmin如此炫酷的可视化面板，SQLite什么都看不到，好像就一个单文件，用记事本打不开，不会用。MySQL导出的数据库都能直接用记事本txt打开，最适合我这种小白了。

> 另外对于已 EOL 的软件还继续提供支持，你知道这意味着什么吗？

~~敢于攻关、敢于创新、敢于领先~~
这题我搜不到答案，还请指教一下。

**Comment by g-plane** [comment]
我个人并不推荐使用面板类软件，特别是宝塔。我已经收到过很多次关于此类面板软件的问题反馈了。

建议学习网站建站技术，而不是以自己「是小白」为荣。但你能如此分析，应该不是小白才对。

总之，我不会做「支持 EOL」这种扭曲的事。
