### ISSUE TITLE
皮肤库筛选器的排序中的「最多收藏」不可用

### ISSUE THREAD

**Issue by tnqzh123** [bs-community/blessing-skin-server#27]
在皮肤库筛选器的排序中选择「最多收藏」后，皮肤库一直显示「正在加载」，Console 中有出现 Error：
![Snipaste_2019-03-17_14-08-46](https://user-images.githubusercontent.com/16630630/54486097-37489300-48be-11e9-8b5a-493e89e76816.png)
浏览器是 Chrome 72 Stable。

**Comment by g-plane** [comment]
暂时没法复现

**Comment by g-plane** [comment]
OK，复现出来了。

**Comment by g-plane** [comment]
Fixed by https://github.com/bs-community/blessing-skin-server/commit/749339f33180c0002a0bbec185ae8af32dff32ae
