### ISSUE TITLE
Mojang账号无法直接登录

### ISSUE THREAD

**Issue by Zero-Luo** [bs-community/blessing-skin-server#270]
The Problem 问题描述
mojang正版无法直接登录,直接登录提示用户不存在

Environment 运行环境
Blessing Skin 版本 (Version of Blessing Skin): 5.2.0
PHP 版本 (Version of PHP): 7.4.0
Apache / Nginx: Nginx
Browser: Twinkstar Browser 7.2.2000.2012 ( Chromium: 80.0.3987.163 Res: 2006.423 ) （64 位）
URL:https://www.zeroskin.top/auth/login

**Comment by g-plane** [comment]
请安装「正版验证」插件。

**Comment by g-plane** [comment]
如果是与「正版验证」插件相关的问题，请在插件对应的仓库提 issue。
