### ISSUE TITLE
请求帮助:希望将皮肤站安装在子目录下如xxx.com/blessingskinserver/public

### ISSUE THREAD

**Issue by ExcitedForg** [bs-community/blessing-skin-server#271]
此issues不包含bug(大概)
鄙人仅略微接触过java，没有学习过php以及网站结构，若本请求不合逻辑还请各位大佬见谅
使用apache php7.3 mysql, windows server2016(别骂了别骂了真不会linux)
我用wordpress建了一个主站，apache的站点根目录设置在wordpress根目录，然后我将bss放在wordpress根目录中的blessingskinserver文件夹，修改了public中的.htaccess，修改部分如下

    # You may need to uncomment the following line for some hosting environments,
    # if you have installed to a subdirectory, enter the name here also.
    #
    RewriteBase /BlessingSkinServer/Public/

然后浏览器通过127.0.0.1/blessingskinserver/public可以访问安装程序，可以成功安装，但安装完成后皮肤站界面有问题(如截图),若直接将apache站点根目录指向public并重新安装则可以正常使用。
![1](https://user-images.githubusercontent.com/79185387/108160323-d5d17480-7123-11eb-9d4b-2e94e181bb9b.PNG)
![2](https://user-images.githubusercontent.com/79185387/108160330-d833ce80-7123-11eb-8488-03bd60026e58.PNG)
        有没有可能达成此目的？若可以，我的方法是不是有问题？
        另:尝试过使用子域名，但我的ddns提供商似乎不提供3级域名转发，无法访问

**Comment by tnqzh123** [comment]
@ExcitedForg > 另:尝试过使用子域名，但我的ddns提供商似乎不提供3级域名转发，无法访问 

你自己买个域名然后 CNAME 过去不就行了……

**Comment by g-plane** [comment]
从 v4 起我们就已经不再提供子目录的支持。

**Comment by TowardtheStars** [comment]
用反代功能+对响应修改可以实现类似的效果。
这里我新开一个 Blessing Skin 的网站，端口 20080
然后下面是写在主网站 nginx 配置里的东西，题主可参考自行改成 Apache
```nginx
    # Blessing Skin
    set $blessingskin_url 127.0.0.1:20080;
    # blessingskin 是子目录名字
    location /blessingskin {
      return 302 $scheme://$host/blessingskin/;
    }
    location ^~ /blessingskin/ {
      proxy_pass http://$blessingskin_url;
      proxy_redirect ~http://$blessingskin_url/(.*) /blessingskin/$1;
      proxy_set_header Accept-Encoding "";
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      rewrite ^/blessingskin$ / break;
      rewrite ^/blessingskin/(.*)$ /$1 break;
      sub_filter '\"/app' '\"/blessingskin/app';
      sub_filter '\"/avatar' '\"/blessingskin/avatar';
      sub_filter '$blessingskin_url' '$host/blessingskin';
      sub_filter_types *;
      sub_filter_once off;
    }
```
