### ISSUE TITLE
站点标题在不同语言间无法保持同步

### ISSUE THREAD

**Issue by DreamUniverse843** [bs-community/blessing-skin-server#272]
## The Problem 问题描述

自定义的站点标题无法在所有的语言页面保持同步。
示例：站点名称为 DreamCraft Skin ， 中文（简体）、英语正常显示，但是在西班牙语和中文（繁体）中变为默认的 Blessing Skin

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):6.0.0-beta.2
- PHP 版本 (Version of PHP):7.4.3
- Apache / Nginx:Apache
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):全站的站点标题

## Error Message 错误信息

![QQ截图20210218203342](https://user-images.githubusercontent.com/53889721/108358994-5e3a3d00-722a-11eb-804a-56cc7cbc1040.png)
![QQ截图20210218203354](https://user-images.githubusercontent.com/53889721/108359564-1bc53000-722b-11eb-9caf-b601baf2ebcc.png)

## Steps to Reproduce 重现步骤

在站点管理面板 > 站点配置中定义站点名称和站点描述，英语会和简体中文保持同步，但其余语言不同步。

**Comment by g-plane** [comment]
其它文本比如站点公告有这个问题吗？

**Comment by DreamUniverse843** [comment]
没有，站点公告是保持同步的。
而且站点公告本身就是针对多语言而有所不同的。

**Comment by g-plane** [comment]
我这里不能复现：
![图片](https://user-images.githubusercontent.com/17216317/108369151-394bc700-7236-11eb-817f-da51309eb8a0.png)

![图片](https://user-images.githubusercontent.com/17216317/108369191-47014c80-7236-11eb-922e-77fdf861b3be.png)

**Comment by DreamUniverse843** [comment]
那是否可能在升级过程中出现的问题呢？
我去新建一个实例看下。

**Comment by g-plane** [comment]
应该不会吧？最近我没有改动过这部分功能。

**Comment by DreamUniverse843** [comment]
新建的实例没有问题。
可能在自动升级过程中未向新的语言添加数据库表项？

**Comment by g-plane** [comment]
这个有可能，手动修改一下站点名应该会保存。

**Comment by DreamUniverse843** [comment]
已经手动修改好了，谢谢。
不过仍然建议在升级时检测新语言的数据库池，否则升级后数据缺失会造成服务器运营者浪费大量人力物力。

**Comment by g-plane** [comment]
这的确是问题，但问题是 Blessing Skin 本身没法识别哪些设置项是需要本地化的。

**Comment by g-plane** [comment]
我检查了数据库，在 `options` 表里没有繁体中文与西班牙语对应的站点名记录，但是切换到这两种语言的时候，站点名仍然能正常显示。
