### ISSUE TITLE
Blessing skin server 6.0.0 beta 2有些显示问题

### ISSUE THREAD

**Issue by TGCyrus** [bs-community/blessing-skin-server#274]
## The Problem 问题描述

在最新的beta2版本中，可能奇数次的刷新会导致一些网页无法被浏览器显示(不会显示内容)

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):6.0.0 beta2
- PHP 版本 (Version of PHP):7.4
- Apache / Nginx:apache 4.8
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):Google Chrome，网址letusskin.bloker.top

## Error Message 错误信息

我无法提供日志，因为console控制台中没有弹出错误信息

## Steps to Reproduce 重现步骤

按照正常步骤(下载并上传到云服务器中，解禁函数，安装fileinfo拓展，关闭防跨站攻击{另外一点就是APPkey貌似在此版本中初始时就有})

开始大批量(当然也是一个一个)上传新皮肤
奇数次上传皮肤，网页显示有误

**Comment by g-plane** [comment]
我访问了你的网站，没看到有什么问题。
