### ISSUE TITLE
不知道怎么描述

### ISSUE THREAD

**Issue by Shizuri23** [bs-community/blessing-skin-server#276]
## The Problem 问题描述
![image](https://user-images.githubusercontent.com/46082179/109462626-c1d03000-7a9e-11eb-8b32-e09cf1410ad8.png)

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): 5.2.0
- PHP 版本 (Version of PHP): 7.3
- Apache / Nginx: Nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):
https://skin.nmsl.pet/user/player/bind
## Steps to Reproduce 重现步骤
不清楚更新什么插件之后，出现上面的问题

**Comment by g-plane** [comment]
请在原 issue 下讨论相关问题。
