### ISSUE TITLE
皮肤库预览图片无法显示

### ISSUE THREAD

**Issue by JPEI042** [bs-community/blessing-skin-server#278]
## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):  v6.0.0-beta.2
- PHP 版本 (Version of PHP): 8.0.1
- Apache / Nginx: Apache
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): Google Chrome ,http://43.248.189.228:45564/preview/8?height=150

## Error Message 错误信息

https://imgtu.com/i/6rQNwV
https://imgtu.com/i/6rQsyR

## Steps to Reproduce 重现步骤

从安装完一直都会

**Comment by g-plane** [comment]
Duplicate of #277 .
