### ISSUE TITLE
我的衣柜页面“皮肤”和“披风”的导航问题

### ISSUE THREAD

**Issue by CK-Tex** [bs-community/blessing-skin-server#279]
## The Problem 问题描述

“我的衣柜”页面下方分类导航不一致问题，具体见重现部分。

## Environment 运行环境
• Blessing Skin 版本 (Version of Blessing Skin): v6.0.0-beta.2
• PHP 版本 (Version of PHP): 7.4
• Apache / Nginx: Apache
• 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): Google Chrome , https://domain/user/closet

## Error Message 错误信息

无报错

## Steps to Reproduce 重现步骤

进入“我的衣柜”页面，点击一次“皮肤”会显示所有皮肤，在当前状态下再点击一下“皮肤”按钮，下面会自动换成“披风”。所以就出现了上方标亮的分类为“皮肤”，但是下方实际显示的是披风。此情况按两次“披风”也能触发。
此问题在Littleskin上也能重现。

https://imgtu.com/i/6rRJXj
https://imgtu.com/i/6rRGcQ

**Comment by g-plane** [comment]
已确认。
