### ISSUE TITLE
可以对6.0版本以上添加对PHP7.3的支持吗？

### ISSUE THREAD

**Issue by mocha666** [bs-community/blessing-skin-server#283]
## The Problem 问题描述
可以对6.0版本以上添加对PHP7.3的支持吗？<br>
因为服务器暂时使用的是arm架构的cpu，7.4+的php不可以很好的运行在arm的机器上面

**Comment by g-plane** [comment]
没有相关计划。

**Comment by mocha666** [comment]
好的 感谢
