### ISSUE TITLE
6.0.0 beta2中页面切换问题

### ISSUE THREAD

**Issue by TGCyrus** [bs-community/blessing-skin-server#284]
## The Problem 问题描述
在普通用户，打开自己的衣柜，点击皮肤，然后选中第三页，这时候换成披风，页面信息可能会显示到第三页，但是披风页并没有第三页，希望在切换页面的时候把页数归为1

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):
- PHP 版本 (Version of PHP):7.4
- Apache / Nginx:APACHE
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):letusskin.bloker.top

## Error Message 错误信息

没有日志，因为这是特殊错误原因，请见上面的问题描述

## Steps to Reproduce 重现步骤

打开皮肤站，打开用户中心，打开我的衣柜，点击皮肤，选择第三页，点击披风(披风没有第三页)，无显示内容

**Comment by g-plane** [comment]
Duplicate of #279 .

**Comment by g-plane** [comment]
抱歉，当初理解错以为是同一个问题。
