### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by LanceOnTop** [bs-community/blessing-skin-server#286]
## The Problem 问题描述
安装时出错
当我查看到这个错误时，我按常见问题的方法解决出错
![image](https://user-images.githubusercontent.com/73412021/114879499-d476ac80-9e33-11eb-8300-f4c634b0316a.png)
尝试常见问题中的方法解决后
![image](https://user-images.githubusercontent.com/73412021/114880493-b1003180-9e34-11eb-8c1b-dbf211ea5924.png)

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):v5
- PHP 版本 (Version of PHP):80
- Apache / Nginx:Nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):Ms Edge https://skin.lancex.top/setup
- 使用手动构建
- 安装日志 https://api.lancex.top/files/skinserver-installlog.txt

**Comment by g-plane** [comment]
这不是已经说明怎么解决了吗？
