### ISSUE TITLE
维护第三方更新源 来自GitLat自建更新源

### ISSUE THREAD

**Issue by YuxiangWang0525** [bs-community/blessing-skin-server#290]
平台:GitLat(自建站点)  
Json地址:https://gitlat.shifanglink.top/YuxiangWang_0525/Blessing-Skin-Server/raw/commit/8bcf8cbba1994bd43cae3497fcbbc259f655a169/update.json

**Comment by g-plane** [comment]
你给的链接是固定在某个 commit，这以后怎么更新？

**Comment by 8MiYile** [comment]
https://gitlat.shifanglink.top/YuxiangWang_0525/Blessing-Skin-Server/src/branch/master/update.json

**Comment by g-plane** [comment]
长时间未收到回复，现关闭。
