### ISSUE TITLE
请问有没有一个服务端插件或者服务端功能可以让玩家使用Blessing Skin Server的皮肤站进入服务器

### ISSUE THREAD

**Issue by TGCyrus** [bs-community/blessing-skin-server#292]
## The Problem 问题描述
请问有没有一个服务端插件或者服务端功能可以让玩家使用Blessing Skin Server的皮肤站进入服务器

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):6.0.0 beta2
- PHP 版本 (Version of PHP):7.4
- Apache / Nginx:apache
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):Google Chrome (letusskin.bloker.top)

## Steps to Reproduce 重现步骤
没有重现步骤，请见问题描述

**Comment by g-plane** [comment]
请提供具体信息或详细的过程。

**Comment by BecodReyes** [comment]
请在写完之后自行阅读一下看看句子达不达意
你的问题应该是
`是否能够让玩家使用自建Blessing Skin Server皮肤站的皮肤`
或者
`是否能够让玩家使用自建Blessing Skin Server皮肤站的账号登录到服务器`

如果仅仅是使用皮肤站的皮肤，详见[配置皮肤 Mod](https://blessing.netlify.app/mod.html)
如果是使用账号登录到服务器，详见[yggdrasil-api](https://blessing.netlify.app/yggdrasil-api/introduction.html)

**Comment by TGCyrus** [comment]
我指的是“是否能让玩家只能使用正版登录或者Blessing Skin Server登录到服务器”

**Comment by g-plane** [comment]
使用 Yggdrasil API 就可以了。

**Comment by BecodReyes** [comment]
> 使用 Yggdrasil API 就可以了。

只使用Yggdrasil API不一定能够实现正版登录和皮肤站登录共存
还是要外挂一些东西才行
[YggdrasilOfficialProxy](https://github.com/YggdrasilOfficialProxy/YggdrasilOfficialProxy)
[MultiLogin](https://github.com/CaaMoe/MultiLogin)

**Comment by tnqzh123** [comment]
@BecodReyes 所以你为什么要做「正版和第三方验证服务器共存」这种**脑瘫**操作？

BS 安装正版验证插件之后，只需要在皮肤站网页端使用正版账号直接登录一次就会自动创建账户和角色，为什么不直接让他们先登录一次？

**Comment by BecodReyes** [comment]
> @BecodReyes 所以你为什么要做「正版和第三方验证服务器共存」这种**脑瘫**操作？
> 
> BS 安装正版验证插件之后，只需要在皮肤站网页端使用正版账号直接登录一次就会自动创建账户和角色，为什么不直接让他们先登录一次？

> 是否能让玩家只能使用正版登录或者Blessing Skin Server登录到服务器

题主的语句一直有语病，故我对此的理解是`正版和第三方验证服务器共存`，所以提出了以上的**建议**

不是所有玩家都能够将自己的账号密码交付给一个第三方网站做验证，不论它声称用户信息保护得再怎么安全，加密再怎么难以破解

所以这些插件的存在也不是没有道理的，我相信像我这样**脑瘫**操作的腐竹应该也有不少，至少它能减少很多传统正版验证时需要多开台服务器，需要在聊天框内输入正版密码之类的这些劝退验证的问题

**Comment by tnqzh123** [comment]
@BecodReyes

> > 是否能让玩家只能使用正版登录或者Blessing Skin Server登录到服务器
> 
> 
> 
> 题主的语句一直有语病，故我对此的理解是`正版和第三方验证服务器共存`，所以提出了以上的**建议**
> 
> 
> 
> 不是所有玩家都能够将自己的账号密码交付给一个第三方网站做验证，不论它声称用户信息保护得再怎么安全，加密再怎么难以破解
> 
> 
> 
> 所以这些插件的存在也不是没有道理的，我相信像我这样**脑瘫**操作的腐竹应该也有不少，至少它能减少很多传统正版验证时需要多开台服务器，需要在聊天框内输入正版密码之类的这些劝退验证的问题

**爱玩玩不玩滚**，就是这么个道理

我说话不好听，但是我觉得话糙理不糙，有的时候语气什么的太软了反而容易被用户当软柿子捏

是玩家自己要来玩服务器，不是服主求着玩家来玩，这是一个双向的选择

同时使用多个验证服务器会存在角色重名和 UUID 重复的问题，这些问题可不是一天两天就能处理完的，而且一旦出现就有可能造成毁灭性的后果

我知道一刀切可能不会是最好的解决方案，但是在考虑问题的解决方案的时候最好顺带考虑一下这个解决方案会不会带来更多麻烦，很显然这个解决方案带来的麻烦和解决这些麻烦的代价完全不是一般服务器的运营人员能承受的

Anyway，在更好的、能够解决角色名和 UUID 重复问题的解决方案出现之前，我不推荐任何人使用这种「多验证服务器共存」的解决方案

「不明就里」是我和 authlib-injector 作者讨论这类产品后得到的唯一结论

**Comment by TGCyrus** [comment]
我觉得两位可能对我的理解有些问题，我语文的功底不好，请见谅
目前我**不再打算**：
**正版**进入服务器√
**Blessing Skin Server皮肤站**进入服务器√
**离线**登录×

感谢您们的回帖，希望Blessing Skin Server（下面简称BSS）能够更好吧。这几天我也想了想，我觉得角色名重复是个好的问题。我想解释一下，我做这个**脑瘫**行为的原因主要有下面几点：
1.减少服务器作弊率：避免玩家换个离线名称就可以重新进入服务器，相当于无限次封号又解封
2.去掉AuthMe这个插件：玩家每次都要进行登录，而BSS不是，只需登录一次，后续只需隔一段时间验证即可。
3.提升皮肤站使用率：我的皮肤站现今只有37个注册用户。我希望能提高注册率

但是！我也想通了几个问题：
1.玩家数据丢失：虽然说我这个服务器还没开几周，但是SkyBlock和生存的一些重要数据会丢失，如果再手动找回的话就“没内味”了。
2.过于麻烦：我开的是群组服，可想而知
3.反作弊过于硬核：至今没有找到合适的反作弊插件，我明白一分钱一分货的道理，但是实在抽不开资金去购买插件了

**再次感谢您们的回复！**

**Comment by TGCyrus** [comment]
我还有最后一个问题，就是http://bss.com/csl的这个CSL API是**自带**的吗？
如果不是自带的，请问CSL API在哪里下载并安装？

**Comment by g-plane** [comment]
> CSL API 是自带的吗？

是的。
