### ISSUE TITLE
使用Oauth2授权后无法返回code

### ISSUE THREAD

**Issue by LazyCreeper** [bs-community/blessing-skin-server#294]
## The Problem 问题描述

第三方网站[https://live.lazy.ink](https://live.lazy.ink)使用Oauth2授权后无法返回code

## Environment 运行环境

- Blessing Skin 版本 (v5.2.0):
- PHP 版本 (PHP-73):
- Apache / Nginx: Nginx 1.19.6
- Google Chrome 版本 90.0.4430.93

## Error Message 错误信息
![1.PNG](https://imgs.lovpass.cn/img/2021/05/12/df669e7460a1320210512.png)
![2.PNG](https://imgs.lovpass.cn/img/2021/05/12/6c07330c63b3420210512.png)
授权后返回空白，url也没有跳转
## Steps to Reproduce 重现步骤
 1.打开[https://live.lazy.ink](https://live.lazy.ink)
 2.点击登录按钮
 3.授权登录

**Comment by vlssu** [comment]
呦，真巧，这遇见你，我论坛也出现这种情况

**Comment by LazyCreeper** [comment]
> ## The Problem 问题描述
> 第三方网站https://live.lazy.ink使用Oauth2授权后无法返回code
> 
> ## Environment 运行环境
> * Blessing Skin 版本 (v5.2.0):
> * PHP 版本 (PHP-73):
> * Apache / Nginx: Nginx 1.19.6
> * Google Chrome 版本 90.0.4430.93
> 
> ## Error Message 错误信息
> ![1.PNG](https://camo.githubusercontent.com/d027e17546e678401995dea66825888095e8402662e93dc32259d51dd0c7852d/68747470733a2f2f696d67732e6c6f76706173732e636e2f696d672f323032312f30352f31322f6466363639653734363061313332303231303531322e706e67)
> ![2.PNG](https://camo.githubusercontent.com/aed368920c2e07d92d60249e6118655019db302623cb07432bd9e663534b6dad/68747470733a2f2f696d67732e6c6f76706173732e636e2f696d672f323032312f30352f31322f3663303733333063363362333432303231303531322e706e67)
> 授权后返回空白，url也没有跳转
> 
> ## Steps to Reproduce 重现步骤
> 1.打开https://live.lazy.ink
> 2.点击登录按钮
> 3.授权登录
