### ISSUE TITLE
Web API POST请求登录返回异常

### ISSUE THREAD

**Issue by Widayn** [bs-community/blessing-skin-server#302]
## The Problem 问题描述

POST登录返回异常
email,password,Accept 均已填写

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): 6.0.0-beta.2
- PHP 版本 (Version of PHP): 7.4
- Apache / Nginx: Nginx

## Error Message 错误信息

返回:
{
    "message": "",
    "exception": true,
    "trace": [
        {
            "file": "app/Http/Middleware/DetectLanguagePrefer.php",
            "line": 30
        },
        {
            "file": "app/Http/Middleware/ConvertEmptyStringsToNull.php",
            "line": 23
        }
    ]
}

## Steps to Reproduce 重现步骤

POST请求/api/auth/login

**Comment by g-plane** [comment]
v6 不支持基于 JWT 的登录方式，所以该 API 也已经被移除。

**Comment by Widayn** [comment]
好吧。。
那有别的方法可以验证玩家在网页输入的个人信息是否正确吗
我用的是SHA256, 但是authme的加密方式属实把我整懵了
String encryptedPassword = "$SHA$" + salt + "$" + sha256(sha256(password) + salt);
这里的salt是指什么？

**Comment by Asnxthaony** [comment]
```php
function computeHash($password, $salt)
{
    $password = hash('sha256', $password);
    $password = hash('sha256', $password.$salt);
    return $password;
}

$password = explode('$', $password); // encryptedPassword

if ($password[3] == computeHash($inputPassword, $password[2])) {
    // 登录成功
} else {
    // 登录失败
}
```

**Comment by Widayn** [comment]
感谢！
