### ISSUE TITLE
请将 Web 根目录设为当前目录下的 public 目录。

### ISSUE THREAD

**Issue by MCkevin688** [bs-community/blessing-skin-server#304]
## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):
- PHP 版本 (Version of PHP):
- Apache / Nginx:
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):

**Comment by g-plane** [comment]
请认真阅读文档再进行操作。
