### ISSUE TITLE
请增加对 xenforo 的支持

### ISSUE THREAD

**Issue by Meteorpc** [bs-community/blessing-skin-server#305]
## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):
- PHP 版本 (Version of PHP):
- Apache / Nginx:
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):

**Comment by g-plane** [comment]
不考虑。如果它支持 OAuth2，那么请自行用 OAuth 进行对接。
