### ISSUE TITLE
Yggdrasil API 运行异常

### ISSUE THREAD

**Issue by Meteorpc** [bs-community/blessing-skin-server#307]
从v5.6以后都是这样

![QQ截图20210703233620](https://user-images.githubusercontent.com/60288144/124359456-abf29780-dc57-11eb-8ddd-91012a1411a0.png)

**Comment by g-plane** [comment]
Duplicate of https://github.com/bs-community/blessing-skin-plugins/issues/109 .

你为什么要重复开 issue？

**Comment by Meteorpc** [comment]
抱歉有延迟 我这里只显示5个issue 点进去你的链接就显示12个了 抱歉

**Comment by Meteorpc** [comment]
移动issue 没有提示
