### ISSUE TITLE
没有插件

### ISSUE THREAD

**Issue by chengyufei** [bs-community/blessing-skin-server#31]
## The Problem 问题描述

插件市场里没插件？

## Environment 运行环境

请填写以下内容 / Please tell us about your environment.

- Blessing Skin 版本 / 4.0beta1
- 虚拟主机还是 VPS / 自己的电脑
- PHP 版本 / 7.3.3
- 什么 Web 服务器，Apache 还是 Nginx / apache
- 什么浏览器，出现错误时的地址栏 URL 是什么 / bs.localhost/admin/plugins/market

## Error Message 错误信息

No data for table

## Steps to Reproduce 重现步骤

点击插件市场，没有任何插件

## Attachments 附件

如果有需要，请在这里附上你的日志文件（如果日志很长，请上传至某处并提供链接）/ Attach your log file here if necessary.

**Comment by g-plane** [comment]
v4 的插件市场还在建设中。

**Comment by chengyufei** [comment]
就是说v4没有插件？

**Comment by g-plane** [comment]
有，但没有发布到市场中。

**Comment by chengyufei** [comment]
那怎么安装

**Comment by g-plane** [comment]
https://github.com/bs-community/blessing-skin-plugins

部分插件需要您自行构建。另外，有少数插件未完成对新版本的适配。

**Comment by tnqzh123** [comment]
下载插件源码，手动安装依赖并编译即可在管理面板中启用

**Comment by g-plane** [comment]
如果您不知道如何自行构建，可以等待 Blessing Skin RC。按计划 RC 发布时将会有插件市场。

**Comment by tnqzh123** [comment]
> 另外，有少数插件未完成对新版本的适配。

其实除了数据对接插件之外的官方插件应该都已经适配了 v4 了，还有很多插件已经被整合进 BS 核心，不需要另外安装

**Comment by chengyufei** [comment]
好的
