### ISSUE TITLE
6.0.0-beta.3 邮件发送失败

### ISSUE THREAD

**Issue by ghost** [bs-community/blessing-skin-server#310]
The Problem 问题描述

升级至 v6.0.0-beta.3 版本后，新注册或更换邮箱时，邮件发送失败.用户也亦无法验证邮箱（无邮件发送）

 Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): 6.0.0-beta.3
- PHP 版本 (Version of PHP):7.4.20
- Apache / Nginx: nginx[1.20.1]
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):https://skin.nebulacabinet.com/auth/forgot

Error Message 错误信息

找回密码:[
邮件发送失败，详细信息：Connection could not be established with host :stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known
]
![image](https://user-images.githubusercontent.com/85435446/125791502-2848a254-cd13-4a19-8128-643e2c2621fc.png)

邮箱验证:[
邮件发送失败，详细信息：Connection could not be established with host :stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known]
![image](https://user-images.githubusercontent.com/85435446/125791783-54952e80-dcd3-48a7-8a87-361c4c632fae.png)

Steps to Reproduce 重现步骤

 找回密码/邮箱验证

**Comment by g-plane** [comment]
`.env` 配置文件关于邮件部分是怎样的？
