### ISSUE TITLE
PHP 8 导致皮肤预览出错: Image source not readable

### ISSUE THREAD

**Issue by RealHeart** [bs-community/blessing-skin-server#311]
## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): 6.0.0-beta3
- PHP 版本 (Version of PHP): 8.0.7
- Apache / Nginx: Nginx 1.19
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): Edge https://skin.zhenxin.xyz/preview/379?height=150

## Error Message 错误信息

Intervention\Image\Exception\NotReadableException
Image source not readable

app/Http/Controllers/TextureController.php:74

## Steps to Reproduce 重现步骤
上传皮肤 直接访问预览链接

**Comment by g-plane** [comment]
是个别图片有这样的问题还是所有都是这样？

**Comment by RealHeart** [comment]
> 是个别图片有这样的问题还是所有都是这样？

都这样

**Comment by g-plane** [comment]
这个我也没法弄清楚是什么问题……

**Comment by 10935336** [comment]
遇到了同样的问题，头像和预览均无法显示。
`/preview/xxx`  显示：500 Internal Server Error  详细信息：Image source not readable
`/avatar/xxx`  显示：500 Internal Server Error  详细信息：Image source not readable
`/xxx.json` 正常
`/textures/xxx` 正常

Environment 运行环境
----
- Blessing Skin 版本 (Version of Blessing Skin): 6.0.0-beta3
- PHP 版本 (Version of PHP): 8.0.5
- Apache / Nginx: Nginx 1.19.10

**Comment by wangwang-code** [comment]
@10935336 @RealHeart **请尝试将php版本更改为7.4，两个都是在php8中出问题**

_还有个不靠谱的猜测，权限不足，可以尝试将blessing-skin整个目录777权限递归_

**Comment by Big-Cake-jpg** [comment]
冒个泡，防止Issue被关（贴吧行为）

**Comment by tnqzh123** [comment]
请将 PHP 降级到 7。

**Comment by mochaaP** [comment]
> 冒个泡，防止Issue被关（贴吧行为）

@Big-Cake-jpg 該 Issue 已經打上了 bug label，不會被自動關閉。
