### ISSUE TITLE
用户验证邮箱时，浏览器返回405 Method Not Allowed

### ISSUE THREAD

**Issue by LazyCreeper** [bs-community/blessing-skin-server#312]
## The Problem 问题描述

新用户验证邮箱、玩家绑定正版账号时，会出现405错误

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):`v5.2.0`
- PHP 版本 (Version of PHP):`7.4`
- Apache / Nginx:`Nginx 1.21.0`
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): `Microsoft Edge 90.0.818.51`、`Google Chrome 91.0.4472.77`；URL：`https://www.fxcraft.cn/mojang/verify`、`https://www.fxcraft.cn/auth/verify/2`

## Error Message 错误信息

前台报错：`405 Method Not Allowed`
![img](https://s1.imlazy.ink:233/img/QQ%E6%88%AA%E5%9B%BE20210719090651.jpg)
错误日志：无，只有`[19/Jul/2021:09:17:51 +0800] "POST /user HTTP/1.1" 405 837 "https://www.fxcraft.cn/user" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36 Edg/90.0.818.51"`之类的`POST`方法才会出现405

## Steps to Reproduce 重现步骤

 1.进入仪表盘
 2.在下边的正版绑定页面随便输入，然后提交
 3.浏览器返回405

---

 1.点击链接验证邮箱
 2.输入邮箱地址然后提交
 3.浏览器返回405

**Comment by SketchySketch** [comment]
A similar problem occurs for me:

```
Failed to authenticate on SMTP server with username "apikey" using 2 possible authenticators. Authenticator LOGIN returned Expected response code 250 but got an empty response. Authenticator PLAIN returned Expected response code 250 but got an empty response.
```

**Comment by g-plane** [comment]
@SketchySketch Your problem isn't related to this issue.

**Comment by 9965086** [comment]
![image](https://user-images.githubusercontent.com/85790323/154661663-e698c3c2-ea4a-4461-8dea-a7c0968307dd.png)
新用户验证邮箱出现这个有知道的吗
