### ISSUE TITLE
关于修改角色名的问题

### ISSUE THREAD

**Issue by lidashuai-li** [bs-community/blessing-skin-server#314]
可以请问下我想要禁止用户修改自己的角色名
那么可以怎么修改皮肤站，或者在singleplayer插件里面加入这个选项
或者可否有偿帮我定制这样一个插件

**Comment by g-plane** [comment]
如果你会编写插件，可以利用 Filters API 对 `can_rename_player` 这个钩子返回一个 Rejection 即可。
