### ISSUE TITLE
Apache无法正常重定向&js无法加载

### ISSUE THREAD

**Issue by SkyTeamWater** [bs-community/blessing-skin-server#316]
## The Problem 问题描述

无法正常重定向到index.php js无法加载

![1.png](https://i.loli.net/2021/07/24/FHsEz168ktDqcrL.png)
![2.png](https://i.loli.net/2021/07/24/iWAucHRY6xjqsSt.png)
![3.png](https://i.loli.net/2021/07/24/yDpZEw2Md1i9okv.png)

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):5.2.0
- PHP 版本 (Version of PHP):7.4
- Apache / Nginx:Apache
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): 新Microsoft Edge Dev & Firefox http://unraid.zyczy.com.cn:7741/index.php/auth/login

## Error Message 错误信息

![4.png](https://i.loli.net/2021/07/24/L7HqGWPxy2urV5Q.png)

## Steps to Reproduce 重现步骤

点击登录

**Comment by g-plane** [comment]
路径不要加 index.php。

**Comment by bradfordzhang** [comment]
不加index.php的话正常访问 可以，但是点击任何一个按钮比如登录

**Comment by g-plane** [comment]
你 Apache 的 mod_rewrite 模块有没有开？

**Comment by bradfordzhang** [comment]
稍等我去确认一下，正常访问主页

**Comment by SkyTeamWater** [comment]
开了
![7.png](https://i.loli.net/2021/07/24/U1bZSBhcPYEMTHQ.png)

**Comment by g-plane** [comment]
不带 index.php 能访问其它页面吗？

**Comment by SkyTeamWater** [comment]
其他所有都不能，包括auth/login，/auth/register，/skinlib

**Comment by g-plane** [comment]
我觉得是「重写」功能没有正常工作导致的。

**Comment by SkyTeamWater** [comment]
那么麻烦您指点一下如何解决问题

**Comment by SkyTeamWater** [comment]
那么麻烦您指点一下如何使重写功能正常工作

**Comment by g-plane** [comment]
我不了解 Apache……

**Comment by SkyTeamWater** [comment]
额那我现在换一下nginx

**Comment by SkyTeamWater** [comment]
这样设置之后直接403了

![8.png](https://i.loli.net/2021/07/24/AnS5UC2mJcPVYTu.png)

**Comment by SkyTeamWater** [comment]
劳烦大佬指点一下哪里出了问题

**Comment by g-plane** [comment]
不是不想帮，是因为我也不知道……用户的服务器环境可以是千差万别的，我不保证所有问题都能解答。

**Comment by SkyTeamWater** [comment]
解决了，在`apache2.conf`中我误将`AllowOverride`设置为`None`，改为`All`正常了，谢谢大佬这么晚还在回复

**Comment by g-plane** [comment]
解决了就好。

**Comment by SkyTeamWater** [comment]
OK谢谢大佬
