### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'xxx' of undefined

### ISSUE THREAD

**Issue by KJZH001** [bs-community/blessing-skin-server#317]
### Which version of Blessing Skin are you using?

6.0.0-beta 3

### Which version of PHP are you using?

7.4

### What browsers are you seeing the problem on?

Chrome

### Which web server are you using?

Nginx

### What happened?

在登录界面点击登录会返回Uncaught (in promise) TypeError: Cannot read property 'login_fails' of undefined，没有后续响应
![4qlf.png](https://img.loliloli.moe/images/2021/08/02/4qlf.png)
刷新后会转跳到仪表盘，但是无法正常加载内容，并且在用户中心和后台管理任何一个页面几乎都有类似的报错（详情请见图片和log）

具体表现为签到卡23小时，积分/角色数永远为0

其他页面加载动画结束后主体内容会消失不见

![4Vai.png](https://img.loliloli.moe/images/2021/08/02/4Vai.png)
![4nIp.png](https://img.loliloli.moe/images/2021/08/02/4nIp.png)

### Error Logs

```text
登录界面的错误

2175.1fb2fd9.js:11 Uncaught (in promise) TypeError: Cannot read property 'login_fails' of undefined
    at onSubmit (175.1fb2fd9.js:11)
onSubmit @ 175.1fb2fd9.js:11
async function (async)
onSubmit @ 175.1fb2fd9.js:11
vi @ react-dom.production.min.js:202
ui @ react-dom.production.min.js:32
xi @ react-dom.production.min.js:32
zg @ react-dom.production.min.js:55
rg @ react-dom.production.min.js:56
(anonymous) @ react-dom.production.min.js:66
(anonymous) @ react-dom.production.min.js:240
ti @ react-dom.production.min.js:30
hg @ react-dom.production.min.js:59
be @ react-dom.production.min.js:46
he @ react-dom.production.min.js:45
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
(anonymous) @ react-dom.production.min.js:240
Ki @ react-dom.production.min.js:44
```
BS的日志（这看起来和前端的报错没啥关系..）
```
[2021-08-02 13:49:01] production.WARNING: Received unexpected HTTP status code from Mojang server: 403  
[2021-08-02 13:49:05] production.WARNING: Received unexpected HTTP status code from Mojang server: 403  
[2021-08-02 13:49:08] production.WARNING: Received unexpected HTTP status code from Mojang server: 403  
[2021-08-02 13:49:15] production.WARNING: Received unexpected HTTP status code from Mojang server: 403  
[2021-08-02 13:49:25] production.WARNING: Received unexpected HTTP status code from Mojang server: 403  
[2021-08-02 13:49:28] production.WARNING: Received unexpected HTTP status code from Mojang server: 403  
[2021-08-02 13:49:31] production.WARNING: Received unexpected HTTP status code from Mojang server: 403  
```
```


### Steps to Reproduce


在**外网**情况下（内网中正常）

在登录页面正确的输入账户密码点击登录后即可触发

或者访问任意一个用户中心的界面

地址 https://skin.moeworld.top

**Comment by KJZH001** [comment]
顺带提一下...

这个issue我在使用中文版的模板提交时发生了HTTP Error 404（网页无法正常运作）的错误

并且使用多台设备尝试也是这样，请尽快修复，谢谢！

**Comment by KJZH001** [comment]
从网上找到的资料来看，这似乎是因为js异步加载提前浏览器绘制元素造成的

不过我的js水平真的很烂，自己修不好，所以最后还是发到这里来寻求帮助了

**Comment by PAKingdom** [comment]
签到卡23小时，积分/角色数永远为0

**Comment by PAKingdom** [comment]
签到卡23小时，积分/角色数永远为0
这边查看你使用了cdn，怀疑是缓存了不该缓存的东西

**Comment by KJZH001** [comment]
> 签到卡23小时，积分/角色数永远为0
> 这边查看你使用了cdn，怀疑是缓存了不该缓存的东西

确实使用了CDN没错，不过这个CDN实际上只是起到个反代的作用（回源非80/443端口）
本身应该是不会缓存什么东西的，不过也感谢你的提醒，我现在去检查一下是不是CDN造成的问题

**Comment by PAKingdom** [comment]
我之所以怀疑是cdn是因为我也使用cdn，然后发现你网页多处地方似乎跳转异常。貌似跟cdn的某项技术“cdn回源跟随”有关
希望帮到你

**Comment by g-plane** [comment]
@KJZH001 不能用中文版的模板？是什么样的问题？可以截图吗？

**Comment by KJZH001** [comment]
> 我之所以怀疑是cdn是因为我也使用cdn，然后发现你网页多处地方似乎跳转异常。貌似跟cdn的某项技术“cdn回源跟随”有关
> 希望帮到你

把CDN去掉以后正常了，谢谢！

**Comment by KJZH001** [comment]
> @KJZH001 不能用中文版的模板？是什么样的问题？可以截图吗？

我刚刚去试了一下，发现又可以提交了...有点奇怪....

 #318

**Comment by KJZH001** [comment]
> @KJZH001 不能用中文版的模板？是什么样的问题？可以截图吗？

就是返回一个HTTP ERROR 404的错误（浏览器的，不是github服务器的页面）
详细的错误信息显示为网页无法正常运作
当时因为没有截图，刚刚尝试了也无法复现，所以抱歉了
