### ISSUE TITLE
php artisan migrate

### ISSUE THREAD

**Issue by 10935336** [bs-community/blessing-skin-server#32]
## The Problem 问题描述

简要描述一下你碰到的问题 / Briefly describe the issue you are experiencing.

## Environment 运行环境

请填写以下内容 / Please tell us about your environment.

- Blessing Skin 版本 /   
4.0.0-beta.1
- 虚拟主机还是 VPS /    
物理机
- PHP 版本 /
7.3.2
- 什么 Web 服务器，Apache 还是 Nginx / 
Nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 / 
尚未访问

## Error Message 错误信息

出现错误时的提示，请把它贴上来（截图或文本）/ Paste the error message or a screenshot here.

php artisan migrate --force

In PluginManager.php line 443:
                                                  
  Call to a member function getVersion() on null 

## Steps to Reproduce 重现步骤

详细描述你出错前的操作步骤 / Tell us how to reproduce this issue.

按照WIKI所述从3.5.0升级到4.0.0 
5. 在终端或 PowerShell 中依次执行以下命令

## Attachments 附件

如果有需要，请在这里附上你的日志文件（如果日志很长，请上传至某处并提供链接）/ Attach your log file here if necessary.

**Comment by g-plane** [comment]
能贴出您的 `storage/logs/laravel.log` 吗？（请用 `<details></details>` 将日志内容包起来）

**Comment by g-plane** [comment]
我想我大概知道原因了。

**Comment by 10935336** [comment]
还需要log吗，因为现在退回到了老版本所以log我没有保存

**Comment by g-plane** [comment]
我想原因是：数据库中有一项记录了已开启了哪些插件，但由于在升级的过程中，BS v4 对该数据项进行更新的时候，因为 `plugins` 目录已被清空，所以不能正常读取信息，进而导致这个 bug 出现。
