### ISSUE TITLE
防止使用5分钟邮箱注册

### ISSUE THREAD

**Issue by Shapaper** [bs-community/blessing-skin-server#323]
### 出现了什么问题？

有人使用5分钟邮箱注册，刷小号：
建议在后台添加**按钮**，新用户注册后要过10分钟才能验证邮箱

**Comment by XieXiLin158** [comment]
@Shapaper 功能推荐也来issue……

**Comment by tnqzh123** [comment]
@Shapaper 你加个验证码不就行了吗

BS 又不是没有内置 reCAPTCHA

**Comment by XieXiLin158** [comment]
@tnqzh123 确实

**Comment by XieXiLin158** [comment]
@Shapaper 最主要是能防熊就可以了 recaptcha可以去Google申请 不行挂代理 免费的 申请需要v2

**Comment by g-plane** [comment]
请考虑使用「邮箱域名限制」插件。
