### ISSUE TITLE
无法连接至阿里云 OSS，请检查你的配置。 错误信息：: RequestId:

### ISSUE THREAD

**Issue by Abandoned9** [bs-community/blessing-skin-server#324]
### Blessing Skin 版本

6.0.0 Beta3

### PHP 版本

8.0

### 出现问题时所使用的浏览器

Chrome

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

无法连接至阿里云 OSS，请检查你的配置。
错误信息：: RequestId:

### 错误日志

```text
"} 
[2021-08-09 21:59:00] production.ERROR: :  RequestId:  {"exception":"[object] (OSS\\Core\\OssException(code: 0): :  RequestId:  at /usr/share/nginx/html/plugins/textures-aliyun-oss/vendor/aliyuncs/oss-sdk-php/src/OSS/Result/Result.php:97)
[stacktrace]
```

### 重现步骤

在.env里添加完OSS信息后就这样了

**Comment by XieXiLin158** [comment]
@Abandoned9 确认信息无误

**Comment by XieXiLin158** [comment]
@Abandoned9 确认信息无误，检查能否链接到阿里云

**Comment by XieXiLin158** [comment]
以上没问题就等回复吧

**Comment by Abandoned9** [comment]
> 以上没问题就等回复吧

OSS_ACCESS_ID是AccessKey ID
OSS_ACCESS_KEY是AccessKey Secret吧
如果是的话那就没填错，全都是复制粘贴的

**Comment by XieXiLin158** [comment]
@Abandoned9

**Comment by XieXiLin158** [comment]
@Abandoned9 看了插件说明么

**Comment by XieXiLin158** [comment]
admin/plugins/readme/refresh-ali-cdn

**Comment by Abandoned9** [comment]
> admin/plugins/readme/refresh-ali-cdn

使用方法吗？看了，就是按照使用方法配置的

**Comment by XieXiLin158** [comment]
> > admin/plugins/readme/refresh-ali-cdn
> 
> 使用方法吗？看了，就是按照使用方法配置的

ALICDN_SITE_BASE_URL - 您的阿里云 CDN 的基础 URL，不能 以斜杠结尾。
这个有写好么

**Comment by Abandoned9** [comment]
> > > admin/plugins/readme/refresh-ali-cdn
> > 
> > 
> > 使用方法吗？看了，就是按照使用方法配置的
> 
> ALICDN_SITE_BASE_URL - 您的阿里云 CDN 的基础 URL，不能 以斜杠结尾。
> 这个有写好么
我没有填写ALICDN_SITE_BASE_URL
按照插件的说明，我只填写了
OSS_ACCESS_ID
OSS_ACCESS_KEY
OSS_BUCKET
OSS_ENDPOINT
OSS_SSL

**Comment by Abandoned9** [comment]
> > > > admin/plugins/readme/refresh-ali-cdn
> > > 
> > > 
> > > 使用方法吗？看了，就是按照使用方法配置的
> > 
> > 
> > ALICDN_SITE_BASE_URL - 您的阿里云 CDN 的基础 URL，不能 以斜杠结尾。
> > 这个有写好么
> > 我没有填写ALICDN_SITE_BASE_URL
> > 按照插件的说明，我只填写了
> > OSS_ACCESS_ID
> > OSS_ACCESS_KEY
> > OSS_BUCKET
> > OSS_ENDPOINT
> > OSS_SSL

不是CDN哦，是OSS

**Comment by XieXiLin158** [comment]
下面还有两个配置

**Comment by Abandoned9** [comment]
> 下面还有两个配置

我并没有填写另外的两个配置，没有填写自定义CDN也没有填写自定义域名

**Comment by XieXiLin158** [comment]
一般来说配置写正确了就可以 插件出错概率非常小 网络问题也是个原因 其他等待回复

**Comment by XieXiLin158** [comment]
吧

**Comment by XieXiLin158** [comment]
还有版本问题()

**Comment by Abandoned9** [comment]
> 吧

网络应该没有问题，服务器能够正常ping通阿里的OSS中心域，版本问题...我是应该回去用5.2吗...

**Comment by XieXiLin158** [comment]
@Abandoned9 ……不是吧

**Comment by XieXiLin158** [comment]
啊 还有个 如果是RAM子账号检查是否有权限

**Comment by g-plane** [comment]
其实如果是插件的问题，那也是正常的，因为插件所使用的 OSS SDK 上游已经长时间没有更新，未必支持新版本的 Laravel。

**Comment by XieXiLin158** [comment]
也是。

**Comment by XieXiLin158** [comment]
要是解决了，建议close这个issue。
