### ISSUE TITLE
检查更新后,提示错误,刷新后看版本到V6了,但是中英混乱

### ISSUE THREAD

**Issue by nikissXI** [bs-community/blessing-skin-server#325]
### Blessing Skin 版本

v6.0.0-beta.3

### PHP 版本

7.4

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Apache

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

已经设置为简体中文了,但有些东西显示还是英文
![image](https://user-images.githubusercontent.com/31379266/128983313-bfd227cf-8e2f-48da-895c-d9a9c455dcc4.png)

### 重现步骤
![image](https://user-images.githubusercontent.com/31379266/128994762-090e68ab-c844-4c14-8032-134302220ea7.png)

原来应该是V5,然后点检查更新,更新提示错误,然后刷新,发现到v6了,但是语言错误

**Comment by XieXiLin158** [comment]
@nikissXI 一般不可能发生，检查你的语言文件。

**Comment by g-plane** [comment]
清空浏览器缓存试试？

**Comment by nikissXI** [comment]
> @nikissXI 一般不可能发生，检查你的语言文件。

怎么检查，不太懂，我直接下载源码覆盖还是这样，用V5.2和V6.0的源码都试过了

**Comment by nikissXI** [comment]
> 清空浏览器缓存试试？

没用，手机电脑都这样，我点了检查更新之后弹个错误，再回来就这样了

**Comment by XieXiLin158** [comment]
@nikissXI 删除

**Comment by XieXiLin158** [comment]
最简单方法

**Comment by nikissXI** [comment]
> @nikissXI 删除

删啥

**Comment by nikissXI** [comment]
没人吗

**Comment by g-plane** [comment]
> 会自动联网重新下载

不会的，所以不要这样做。

---

@nikissXI 你打开浏览器的开发者工具，切换到 Network/网络 标签页，看看里面有没有什么 JS 文件请求出错的。

**Comment by nikissXI** [comment]
> > 会自动联网重新下载
> 
> 不会的，所以不要这样做。
> 
> @nikissXI 你打开浏览器的开发者工具，切换到 Network/网络 标签页，看看里面有没有什么 JS 文件请求出错的。

我去后台看zh_CN.js文件,发现只有几个词汉化了，于是我去找以前V5的备份，把里面的zh_CN.js拉过来就好，不过少数位置还是英文的

**Comment by g-plane** [comment]
什么意思？那问题是解决还是没解决？

**Comment by nikissXI** [comment]
> 什么意思？那问题是解决还是没解决？

![image](https://user-images.githubusercontent.com/31379266/130165983-48758c13-2f41-492e-a394-229b0d0d93b3.png)
shengxi剩下举报位置是英文的，其他正常

**Comment by g-plane** [comment]
还是不懂你的意思。另外把 v5 的文件拿到 v6 里用，会导致一些翻译丢失。

**Comment by nikissXI** [comment]
> 还是不懂你的意思。另外把 v5 的文件拿到 v6 里用，会导致一些翻译丢失。

那在哪里找V6的，我是从V5升级到V6丢失的

**Comment by g-plane** [comment]
正常地更新是不需要你手动去找的，如果有问题请尝试从 https://github.com/bs-community/blessing-skin-server/releases 里拿。

**Comment by nikissXI** [comment]
> 正常地更新是不需要你手动去找的，如果有问题请尝试从 https://github.com/bs-community/blessing-skin-server/releases 里拿。

我之前就是在里面没找到zh_CN.js，所以不知道咋办
![image](https://user-images.githubusercontent.com/31379266/130170782-b65cdde0-d67f-44f4-bb1b-a1174eb3434c.png)

**Comment by g-plane** [comment]
哦不对，它会自动生成的。

**Comment by nikissXI** [comment]
> 哦不对，它会自动生成的。

我是把V6最新版解压,然后覆盖上去,发现没用

**Comment by g-plane** [comment]
你试试把 public/lang 目录下的 .js 文件都删掉，然后访问一个页面，看看能不能生成。

**Comment by nikissXI** [comment]
> 你试试把 public/lang 目录下的 .js 文件都删掉，然后访问一个页面，看看能不能生成。

试过了,生成的还是有毛病的

**Comment by g-plane** [comment]
「有毛病的」是怎样的？

**Comment by nikissXI** [comment]
> 「有毛病的」是怎样的？

就是没中文

**Comment by g-plane** [comment]
全部都没中文还是具体到哪一部分没中文。说详细点。

**Comment by nikissXI** [comment]
blessing.i18n = {"auth":{"login":"Log In","loggingIn":"Logging In","tooManyFails":{"captcha":"You fails too many times! Please enter the CAPTCHA.","recaptcha":"You fails too many times! Please pass the reCAPTCHA challenge."},"emptyEmail":"Empty email address.","invalidConfirmPwd":"Confirming password is not equal with password.","emptyNickname":"Empty nickname.","register":"Register","registering":"Registering","send":"Send","sending":"Sending","reset":"Reset","resetting":"Resetting","nickname":"Nickname","player-name":"Minecraft player name","email":"Email","identification":"Email or player name","password":"Password","captcha":"CAPTCHA","change-captcha":"Click to change CAPTCHA image.","login-link":"Already registered? Log in here.","forgot-link":"Forgot password?","keep":"Remember me","repeat-pwd":"Repeat your password","nickname-intro":"Whatever you like expect special characters","player-name-intro":"Player name in Minecraft, can be changed later","forgot":{"login-link":"I do remember it"}},"skinlib":{"private":"Private","anonymous":"Please login first.","reset":"Reset Filter","addToCloset":"Add to closet","removeFromCloset":"Remove from closet","setItemName":"Set a name for this texture","applyNotice":"You can apply it to player at your closet","emptyItemName":"Empty texture name.","setNewTextureName":"Please enter the new texture name:","emptyNewTextureName":"Empty new texture name.","seeMyUpload":"My Uploads","apply":"Apply","filter":{"skin":"(Any Model)","steve":"(Steve)","alex":"(Alex)","cape":"(Cape)","uploader":"User (UID = :uid) Uploaded","allUsers":"All Users"},"sort":{"title":"Sort","time":"Latest","likes":"Most Likes"},"emptyTextureName":"Empty texture name.","emptyUploadFile":"You have not uploaded any file.","fileExtError":"Error: Textures should be PNG files.","uploading":"Uploading","setAsPrivate":"Set as Private","setAsPublic":"Set as Public","setPublicNotice":"Sure to set this as public texture?","setPrivateNotice":"Sure to set this as private texture?","deleteNotice":"Are you sure to delete this texture?","setNewTextureModel":"Please select a new texture model:","upload":{"texture-name":"Texture Name","texture-type":"Texture Type","select-file":"Select File","privacy-notice":"Prevent it from being visible at skin library.","set-as-private":"Make it Private","button":"Upload","cost":"It costs you about :score score.","award":"You'll be awarded :score score(s) by uploading public texture."},"show":{"anonymous":"You must login to use closets","likes":"People who like this","detail":"Details","name":"Texture Name","edit":"Edit","model":"Applicable Model","size":"File Size","uploader":"Uploader","upload-at":"Upload At","download":"Download","delete-texture":"Delete Texture","manage-notice":"The texture which was deleted or setted to private will be removed from the closet of everyone who had favorited it."},"report":{"title":"Report","reason":"Tell us reason please.","positive":"To encourage positive contributions to the skinlib, we will reward who reported inappropriate content with :score scores. However, if any malicious reporting behaviors were found, all scores rewarded will be taken back.","negative":"To mitigate the impact of malicious reports, we will require :score scores for submitting a texture report. Don't worry. The suspended scores and additional reward will be sent to your account after your report reviewed by administrators."}},"user":{"signRemainingTime":"Available after :time :unit","timeUnitHour":"h","timeUnitMin":"min","emptyClosetMsg":"<p>Nothing in your closet...<\/p><p>Why not explore the <a href=\":url\">Skin Library<\/a> for a while?<\/p>","renameItem":"Rename item","removeItem":"Remove from closet","setAsAvatar":"Set as avatar","viewInSkinlib":"View in skin library","switch2dPreview":"Switch to 2D Preview","switch3dPreview":"Switch to 3D Preview","removeFromClosetNotice":"Sure to remove this texture from your closet?","emptySelectedTexture":"No texture is selected.","renameClosetItem":"Set a new name for this item:","changePlayerName":"Please enter the player name:","emptyPlayerName":"Empty player name.","deletePlayer":"Sure to delete this player?","deletePlayerNotice":"It's permanent. No backups.","chooseClearTexture":"Choose texture types you want to clear","noClearChoice":"You haven't choose any types","setAvatar":"Sure to set this as your avatar?","setAvatarNotice":"The head segment of skin will bu used.","resetAvatarConfirm":"Are you sure to reset your avatar?","typeToSearch":"Type to search","useAs":"Apply...","resetSelected":"Clear selected","closet":{"upload":"Upload Texture","use-as":{"title":"Which player should be applied to?","empty":"It seems that you own no player..."}},"used":{"title":"Resources Used","players":"Registered players","storage":"Storage used"},"cur-score":"Current Score","score-notice":"Click the score to show introduction.","sign":"Sign","player":{"operation":"Operations","edit-pname":"Edit Name","delete-texture":"Clear Textures","delete-player":"Delete","add-player":"Add new player","texture-empty":"Nothing"},"verification":{"title":"Verify Your Account","message":"You must verify your email address before using the skin hosting service. Haven't received the email?","resend":"Click here to send again.","sending":"Sending..."},"oauth":{"id":"Client ID","name":"App Name","secret":"Client Secret","redirect":"Callback URL","modifyName":"Modify app name.","modifyUrl":"Modify callback URL.","create":"Create New App","confirmRemove":"Are you sure to delete this app? You won't be able to undo this."}},"admin":{"operationsTitle":"Operations","permission":"Permission","deleteUser":"Delete","changeEmail":"Edit Email","newUserEmail":"Please enter the new email:","verification":"Email Verification","toggleVerification":"Toggle Verification Status","changeNickName":"Edit Nickname","newUserNickname":"Please enter the new nickname:","changePassword":"Edit Password","newUserPassword":"Please enter the new password:","changeScore":"Edit Score","newScore":"Please enter the new score:","changePermission":"Change permission","newPermission":"Please select new permission:","deleteUserNotice":"Are you sure to delete this user? It' permanent.","banned":"Banned","normal":"Normal","admin":"Admin","superAdmin":"Super Admin","unverified":"Unverified","verified":"Verified","pidNotice":"Please enter the tid of texture. Inputing 0 can clear texture of this player.","changeTexture":"Change Textures","changePlayerName":"Change Player Name","changeOwner":"Change Owner","textureType":"Texture Type","deletePlayer":"Delete","changePlayerOwner":"Please enter the id of user which this player should be transferred to:","deletePlayerNotice":"Are you sure to delete this player? It' permanent.","changePlayerNameNotice":"Please input new player name:","emptyPlayerName":"Player name cannot be empty.","configurePlugin":"Configure","deletePlugin":"Delete","noDependencies":"No Dependencies","pluginTitle":"Plugin","pluginAuthor":"Author","pluginVersion":"Version","pluginReadme":"Read Me","pluginDescription":"Description","pluginDependencies":"Dependencies","installPlugin":"Install","pluginInstalling":"Installing...","updatePlugin":"Update","pluginUpdating":"Updating...","confirmUpdate":"Are you sure to update \":plugin\" from :old to :new?","enablePlugin":"Enable","disablePlugin":"Disable","confirmDeletion":"Are you sure to delete this plugin?","uploadArchive":"Upload Archive","uploadArchiveNotice":"Install a plugin by uploading a Zip archive.","downloadRemote":"Download From Remote","downloadRemoteNotice":"Install a plugin by downloading a Zip archive from remote URL.","updateButton":"Update Now","downloading":"Downloading...","i18n":{"group":"Group","key":"Key","text":"Text","empty":"(Empty)","modify":"Modify","delete":"Delete","updating":"Please type new text:","confirmDelete":"Are you sure? This is irreversible."}},"report":{"tid":"Texture ID","reporter":"Reporter","reason":"Reason","status-title":"Status","status":["Pending","Resolved","Rejected"],"time":"Report Time","delete":"Delete","ban":"Ban","reject":"Reject"},"general":{"skin":"Skin","cape":"Cape","fatalError":"Fatal Error","confirmLogout":"Sure to log out?","confirm":"OK","cancel":"Cancel","submit":"Submit","close":"Close","more":"More","tip":"Tip","noResult":"No result.","texturePreview":"Texture Preview","walk":"Walk","run":"Run","rotation":"Rotation","pause":"Pause","reset":"Reset","skinlib":"Skin Library","wait":"Please wait...","csrf":"This page is out-dated. Please refresh it.","user":{"email":"Email","nickname":"Nick Name","score":"Score","register-at":"Registered At"},"player":{"owner":"Owner","player-name":"Player Name","previews":"Texture Previews","last-modified":"Last Modified"}},"colors":{"black":"Black","white":"White","gray":"Gray","prev":"Previous Background","next":"Next Background"},"vendor":{"datatable":{"search":"Search","prev":"Prev","next":"Next"}},"hitokoto":"Hitokoto::front-end","invitation-codes":{"placeholder":"邀请码"},"mcstaralliance":"mcstaralliance::front-end","mojang-verification":{"registration":{"notice":"Mojang 正版用户可直接登录，无需注册。"}},"sakura":"::front-end","single-player-limit":{"bindNewPlayer":"您现在需要创建一个角色，才能继续使用我们的服务。这个角色将与您的账号绑定。","bindExistedPlayer":"您现在需要选择一个角色，才能继续使用我们的服务。这个角色将与您的账号绑定。其它角色将被删除。"},"yggdrasil-api":{"key-generated":"成功生成了一个新的 4096 bit OpenSSL RSA 私钥","copied":"已复制"}}

**Comment by nikissXI** [comment]
这就是删掉后自动生成的

**Comment by g-plane** [comment]
大段的内容请用代码块包起来或放在 pastebin。

**Comment by g-plane** [comment]
不过就目前的情况看，我无法判断出是哪里出了问题。

**Comment by nikissXI** [comment]
> 不过就目前的情况看，我无法判断出是哪里出了问题。

那先不管了，现在能用，我这边也不懂前端
