### ISSUE TITLE
验证邮件 Title 内站点名称缺失

### ISSUE THREAD

**Issue by DreamUniverse843** [bs-community/blessing-skin-server#326]
### Blessing Skin 版本

6.0.0-beta 3

### PHP 版本

7.4

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Apache

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

以站点名为 DreamCraft Skin 为例：
当请求邮件验证时，标题应为“验证您在DreamCraft Skin上的账户邮箱”，但实际操作收到的邮件标题是“验证您在上的账户邮箱”。
![IMG_20210812_224447](https://user-images.githubusercontent.com/53889721/129217581-2c79ba7b-0385-4ab8-92a8-189934426441.jpg)
图 1 为现在的验证邮件标题，站点名称缺失。
![IMG_20210812_224515](https://user-images.githubusercontent.com/53889721/129217615-eab6d572-481f-41ae-bafa-8271c61a7f85.jpg)
图 2 为先前的邮件标题。

### 重现步骤

请求进行邮件验证即可。

**Comment by XieXiLin158** [comment]
我也同样遇到此问题。
![万年一解](https://user-images.githubusercontent.com/55585872/129231634-dd5f8df6-c9ae-4cfe-ae36-9c7a17d4a425.jpg)

**Comment by g-plane** [comment]
暂未能复现。
