### ISSUE TITLE
拉取并构建d98beae提交后统计表异常

### ISSUE THREAD

**Issue by wangwang-code** [bs-community/blessing-skin-server#333]
### Blessing Skin 版本

dev开发版本（d98beae）

### PHP 版本

7.4

### 出现问题时所使用的浏览器

Chrome

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

![image](https://user-images.githubusercontent.com/64469117/130342265-aa7e8f12-9d0f-472d-a193-40705f1d6b30.png)
8/22只有一名用户注册，以及材质上传统计同样数据错误
统计表数据在拉取并构建d98beae之前正常

### 错误日志

```text
没有与问题相关的错误日志
```

### 重现步骤

拉取d98beae2 commit
先执行 yarn，然后执行  pwsh ./tools/build.ps1

**Comment by wangwang-code** [comment]
且每次刷新网页后表格统计的数据都会变化

**Comment by g-plane** [comment]
我的锅，当时是用随机数作测试，后来忘记去掉。

**Comment by wangwang-code** [comment]
> 我的锅，当时是用随机数作测试，后来忘记去掉。

草

**Comment by wangwang-code** [comment]
还以为出特性了
