### ISSUE TITLE
安装完成后，登录界面没有显示框

### ISSUE THREAD

**Issue by liang-cha-200907** [bs-community/blessing-skin-server#346]
### Blessing Skin 版本

5.2

### PHP 版本

7.3

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

按登录按钮进入登录界面没有输入框（发不了图片我直接把网址发出来：http://www.fi-studio.fun:40188/index.php/auth/login）

### 重现步骤

按下登录按钮进入登录界面找不到输入框

**Comment by liang-cha-200907** [comment]
[laravel-2021-11-05.log](https://github.com/bs-community/blessing-skin-server/files/7480027/laravel-2021-11-05.log)

**Comment by Big-Cake-jpg** [comment]
请不要让URL里包含 index.php
