### ISSUE TITLE
材质内容策略显示为[object Object]

### ISSUE THREAD

**Issue by August7** [bs-community/blessing-skin-server#360]
### Blessing Skin 版本

6.0.0-RC1

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Apache

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

在上传皮肤的页面本应该显示材质内容策略的位置显示为[object Object]
日志中目前没有发现异常
环境：windows apache2.4 php8.1.1 mariadb10.6
![01](https://user-images.githubusercontent.com/8176495/150512080-10caff13-48b5-4434-8367-054213040581.png)

### 重现步骤

点击皮肤库
点击上传新皮肤

**Comment by mochaaP** [comment]
@August7 Dev 分支已修复
https://github.com/bs-community/blessing-skin-server/commit/11a2c602eee727c5fa8be997445d99e527b1302e

**Comment by Big-Cake-jpg** [comment]
> @August7 Dev 分支已修复
> [11a2c60](https://github.com/bs-community/blessing-skin-server/commit/11a2c602eee727c5fa8be997445d99e527b1302e)

问题是什么时候能推送更新呢（

**Comment by mochaaP** [comment]
<https://github.com/bs-community/blessing-skin-server/milestone/1>
