### ISSUE TITLE
更新后语言包缺失

### ISSUE THREAD

**Issue by mtr-static-official** [bs-community/blessing-skin-server#363]
### Which version of Blessing Skin are you using?

 v6.0.0-rc.1

### Which version of PHP are you using?

8.0

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Which web server are you using?

Nginx

### What happened?

中文简体
![image](https://user-images.githubusercontent.com/64729760/150926236-665abbff-3907-472f-a9b6-e5f0d203422a.png)
其他语言均正常

### Steps to Reproduce

切换php版本、更新，发生错误

**Comment by mtr-static-official** [comment]
补充：数据库：MySQL 5.6.50

**Comment by vlssu** [comment]
你可以先覆盖beta4版本的文件用着，，，我就是这样

**Comment by mtr-static-official** [comment]
> 你可以先覆盖beta4版本的文件用着，，，我就是这样

原来如此
