### ISSUE TITLE
提供透明材质预览支持

### ISSUE THREAD

**Issue by hempflower** [bs-community/blessing-skin-server#368]
### Blessing Skin 版本

6.0.0-dev (commit: 1cfbbd6967370ddf4457e93c1aa1f8dcc057b0bb)

### PHP 版本

8.0

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

## 问题
当选择全透明材质预览时，预览材质(2D/3D)显示成纯黑色，如下图所示。
![2D与3D预览透明皮肤](https://user-images.githubusercontent.com/22955496/153133956-ced22a45-2967-407c-b044-741fcfc57888.png)

## 预期效果
应该与MC行为保持一致，在预览中显示为透明，如下图（仅修改了3D预览）。

![透明效果演示](https://user-images.githubusercontent.com/22955496/153134576-69509824-1bc7-4ddd-bf82-9b83b9d6d6df.png)

测试所用的材质:
https://mcskin.cn/textures/6109c5c72c153ac8415553a7038fd06aa2fdcc0842479bf9f4220af4de0c14ef

### 重现步骤

试图预览透明材质。

**Comment by hempflower** [comment]
用原版测试了一下，确实不支持。应该是我跟皮肤mod搞混了。    
但是建议保留一个允许全部透明的选项。

**Comment by yushijinhun** [comment]
> 但是希望保留一个允许全部透明的选项

透明内层皮肤有什么使用场景？如果没有合理的需求则不会考虑。

**Comment by hempflower** [comment]
> > 但是希望保留一个允许全部透明的选项
> 
> 透明内层皮肤有什么使用场景？如果没有合理的需求则不会考虑。

我在为皮肤站修改开发皮肤预览功能时有这样一个需求：   
当检测到用户仅预览披风时，自动将皮肤设置为透明，以便用户更清楚的查看披风的外观。   
这应该是一个小众需求，不过有时还是很有用的。

**Comment by yushijinhun** [comment]
在 skinview3d 中隐藏皮肤即可：
```js
skinViewer.loadSkin(null);
```
