### ISSUE TITLE
无法正常显示“我的衣柜”等界面

### ISSUE THREAD

**Issue by ConstasJ** [bs-community/blessing-skin-server#369]
### Blessing Skin 版本

6.0.0-rc.1

### PHP 版本

8.0

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

在打开皮肤站的“我的衣柜”界面时，应当正常显示衣柜内容。
但是实际情况却是什么也没有显示。
![image](https://user-images.githubusercontent.com/61967203/153324217-0fb26b91-858e-4afe-9926-2b198b6ce8b8.png)

### 重现步骤

1. 正常安装皮肤站
2. 打开“我的衣柜”界面
3. 出现问题

**Comment by Big-Cake-jpg** [comment]
@ConstasJ 请在「我的衣柜」页面打开 F12 Console 并查看是否有无法加载的资源文件。

**Comment by ConstasJ** [comment]
DevTools 无法加载源映射： 无法加载chrome-extension://popomkonnjgcdagdhgcpcekbdeoibglc/js/xl-content.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_UNKNOWN_URL_SCHEME
DevTools 无法加载源映射： 无法加载chrome-extension://pgjjikdiikihdfpoppgaidccahalehjh/webspeed.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_UNKNOWN_URL_SCHEME
DevTools 无法加载源映射： 无法加载chrome-extension://popomkonnjgcdagdhgcpcekbdeoibglc/js/xl-content.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_UNKNOWN_URL_SCHEME
DevTools 无法加载源映射： 无法加载chrome-extension://pgjjikdiikihdfpoppgaidccahalehjh/webspeed.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_UNKNOWN_URL_SCHEME
DevTools 无法加载源映射： 无法加载https://cdn.jsdelivr.net/npm/@blessing-skin/admin-lte@3.1.1/dist/bootstrap.bundle.min.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载源映射： 无法加载https://cdn.jsdelivr.net/npm/@blessing-skin/admin-lte@3.1.1/dist/bootstrap.bundle.min.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载源映射： 无法加载chrome-extension://popomkonnjgcdagdhgcpcekbdeoibglc/js/xl-content.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_UNKNOWN_URL_SCHEME
DevTools 无法加载源映射： 无法加载chrome-extension://pgjjikdiikihdfpoppgaidccahalehjh/webspeed.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_UNKNOWN_URL_SCHEME
DevTools 无法加载源映射： 无法加载https://cdn.jsdelivr.net/npm/@blessing-skin/admin-lte@3.1.1/dist/bootstrap.bundle.min.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载源映射： 无法加载chrome-extension://popomkonnjgcdagdhgcpcekbdeoibglc/js/xl-content.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_UNKNOWN_URL_SCHEME
DevTools 无法加载源映射： 无法加载chrome-extension://pgjjikdiikihdfpoppgaidccahalehjh/webspeed.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_UNKNOWN_URL_SCHEME
DevTools 无法加载源映射： 无法加载https://cdn.jsdelivr.net/npm/@blessing-skin/admin-lte@3.1.1/dist/bootstrap.bundle.min.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载源映射： 无法加载chrome-extension://popomkonnjgcdagdhgcpcekbdeoibglc/js/xl-content.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_UNKNOWN_URL_SCHEME
DevTools 无法加载源映射： 无法加载chrome-extension://pgjjikdiikihdfpoppgaidccahalehjh/webspeed.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_UNKNOWN_URL_SCHEME
DevTools 无法加载源映射： 无法加载https://cdn.jsdelivr.net/npm/@blessing-skin/admin-lte@3.1.1/dist/bootstrap.bundle.min.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载源映射： 无法加载chrome-extension://popomkonnjgcdagdhgcpcekbdeoibglc/js/xl-content.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_UNKNOWN_URL_SCHEME
DevTools 无法加载源映射： 无法加载chrome-extension://pgjjikdiikihdfpoppgaidccahalehjh/webspeed.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_UNKNOWN_URL_SCHEME
16.4a034ba.js:2 
        
       THREE.WebGLRenderer: Error creating WebGL context.
ma @ 16.4a034ba.js:2
constructor @ 16.4a034ba.js:2
ec @ 16.4a034ba.js:2
(匿名) @ 997.cb56530.js:17
Tj @ react-dom.production.min.js:179
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
Ra @ react-dom.production.min.js:178
(匿名) @ react-dom.production.min.js:178
R @ react.production.min.js:16
ua.port1.onmessage @ react.production.min.js:22
react-dom.production.min.js:141 
        
       Error: Error creating WebGL context.
    at new ma (16.4a034ba.js:2:367040)
    at new constructor (16.4a034ba.js:2:614061)
    at new ec (16.4a034ba.js:2:620510)
    at 997.cb56530.js:17:388
    at Tj (react-dom.production.min.js:179:399)
    at unstable_runWithPriority (react.production.min.js:24:26)
    at Za (react-dom.production.min.js:73:8)
    at Ra (react-dom.production.min.js:178:368)
    at react-dom.production.min.js:178:275
    at R (react.production.min.js:16:298)
Ye @ react-dom.production.min.js:141
Mh.c.callback @ react-dom.production.min.js:141
dh @ react-dom.production.min.js:80
Bj @ react-dom.production.min.js:145
Qj @ react-dom.production.min.js:176
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
eb @ react-dom.production.min.js:170
gf @ react-dom.production.min.js:162
(匿名) @ react-dom.production.min.js:73
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
$g @ react-dom.production.min.js:73
ja @ react-dom.production.min.js:73
Tj @ react-dom.production.min.js:180
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
Ra @ react-dom.production.min.js:178
(匿名) @ react-dom.production.min.js:178
R @ react.production.min.js:16
ua.port1.onmessage @ react.production.min.js:22
react-dom.production.min.js:141 
        
       TypeError: Cannot read properties of null (reading 'loadSkin')
    at 997.cb56530.js:17:750
    at Tj (react-dom.production.min.js:179:399)
    at unstable_runWithPriority (react.production.min.js:24:26)
    at Za (react-dom.production.min.js:73:8)
    at Ra (react-dom.production.min.js:178:368)
    at react-dom.production.min.js:178:275
    at R (react.production.min.js:16:298)
    at MessagePort.ua.port1.onmessage (react.production.min.js:22:360)
Ye @ react-dom.production.min.js:141
Mh.c.callback @ react-dom.production.min.js:141
dh @ react-dom.production.min.js:80
Bj @ react-dom.production.min.js:145
Qj @ react-dom.production.min.js:176
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
eb @ react-dom.production.min.js:170
gf @ react-dom.production.min.js:162
(匿名) @ react-dom.production.min.js:73
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
$g @ react-dom.production.min.js:73
ja @ react-dom.production.min.js:73
Tj @ react-dom.production.min.js:180
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
Ra @ react-dom.production.min.js:178
(匿名) @ react-dom.production.min.js:178
R @ react.production.min.js:16
ua.port1.onmessage @ react.production.min.js:22
react-dom.production.min.js:141 
        
       TypeError: Cannot read properties of null (reading 'resetCape')
    at 997.cb56530.js:17:885
    at Tj (react-dom.production.min.js:179:399)
    at unstable_runWithPriority (react.production.min.js:24:26)
    at Za (react-dom.production.min.js:73:8)
    at Ra (react-dom.production.min.js:178:368)
    at react-dom.production.min.js:178:275
    at R (react.production.min.js:16:298)
    at MessagePort.ua.port1.onmessage (react.production.min.js:22:360)
Ye @ react-dom.production.min.js:141
Mh.c.callback @ react-dom.production.min.js:141
dh @ react-dom.production.min.js:80
Bj @ react-dom.production.min.js:145
Qj @ react-dom.production.min.js:176
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
eb @ react-dom.production.min.js:170
gf @ react-dom.production.min.js:162
(匿名) @ react-dom.production.min.js:73
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
$g @ react-dom.production.min.js:73
ja @ react-dom.production.min.js:73
Tj @ react-dom.production.min.js:180
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
Ra @ react-dom.production.min.js:178
(匿名) @ react-dom.production.min.js:178
R @ react.production.min.js:16
ua.port1.onmessage @ react.production.min.js:22
react-dom.production.min.js:141 
        
       TypeError: Cannot read properties of null (reading 'animations')
    at 997.cb56530.js:17:1166
    at Tj (react-dom.production.min.js:179:399)
    at unstable_runWithPriority (react.production.min.js:24:26)
    at Za (react-dom.production.min.js:73:8)
    at Ra (react-dom.production.min.js:178:368)
    at react-dom.production.min.js:178:275
    at R (react.production.min.js:16:298)
    at MessagePort.ua.port1.onmessage (react.production.min.js:22:360)
Ye @ react-dom.production.min.js:141
Mh.c.callback @ react-dom.production.min.js:141
dh @ react-dom.production.min.js:80
Bj @ react-dom.production.min.js:145
Qj @ react-dom.production.min.js:176
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
eb @ react-dom.production.min.js:170
gf @ react-dom.production.min.js:162
(匿名) @ react-dom.production.min.js:73
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
$g @ react-dom.production.min.js:73
ja @ react-dom.production.min.js:73
Tj @ react-dom.production.min.js:180
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
Ra @ react-dom.production.min.js:178
(匿名) @ react-dom.production.min.js:178
R @ react.production.min.js:16
ua.port1.onmessage @ react.production.min.js:22
react-dom.production.min.js:141 
        
       TypeError: Cannot read properties of null (reading 'animations')
    at 997.cb56530.js:17:1236
    at Tj (react-dom.production.min.js:179:399)
    at unstable_runWithPriority (react.production.min.js:24:26)
    at Za (react-dom.production.min.js:73:8)
    at Ra (react-dom.production.min.js:178:368)
    at react-dom.production.min.js:178:275
    at R (react.production.min.js:16:298)
    at MessagePort.ua.port1.onmessage (react.production.min.js:22:360)
Ye @ react-dom.production.min.js:141
Mh.c.callback @ react-dom.production.min.js:141
dh @ react-dom.production.min.js:80
Bj @ react-dom.production.min.js:145
Qj @ react-dom.production.min.js:176
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
eb @ react-dom.production.min.js:170
gf @ react-dom.production.min.js:162
(匿名) @ react-dom.production.min.js:73
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
$g @ react-dom.production.min.js:73
ja @ react-dom.production.min.js:73
Tj @ react-dom.production.min.js:180
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
Ra @ react-dom.production.min.js:178
(匿名) @ react-dom.production.min.js:178
R @ react.production.min.js:16
ua.port1.onmessage @ react.production.min.js:22
react-dom.production.min.js:141 
        
       TypeError: Cannot read properties of null (reading 'loadBackground')
    at 997.cb56530.js:17:1295
    at Tj (react-dom.production.min.js:179:399)
    at unstable_runWithPriority (react.production.min.js:24:26)
    at Za (react-dom.production.min.js:73:8)
    at Ra (react-dom.production.min.js:178:368)
    at react-dom.production.min.js:178:275
    at R (react.production.min.js:16:298)
    at MessagePort.ua.port1.onmessage (react.production.min.js:22:360)
Ye @ react-dom.production.min.js:141
Mh.c.callback @ react-dom.production.min.js:141
dh @ react-dom.production.min.js:80
Bj @ react-dom.production.min.js:145
Qj @ react-dom.production.min.js:176
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
eb @ react-dom.production.min.js:170
gf @ react-dom.production.min.js:162
(匿名) @ react-dom.production.min.js:73
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
$g @ react-dom.production.min.js:73
ja @ react-dom.production.min.js:73
Tj @ react-dom.production.min.js:180
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
Ra @ react-dom.production.min.js:178
(匿名) @ react-dom.production.min.js:178
R @ react.production.min.js:16
ua.port1.onmessage @ react.production.min.js:22
react.production.min.js:22 
        
       Uncaught Error: Error creating WebGL context.
    at new ma (16.4a034ba.js:2:367040)
    at new constructor (16.4a034ba.js:2:614061)
    at new ec (16.4a034ba.js:2:620510)
    at 997.cb56530.js:17:388
    at Tj (react-dom.production.min.js:179:399)
    at unstable_runWithPriority (react.production.min.js:24:26)
    at Za (react-dom.production.min.js:73:8)
    at Ra (react-dom.production.min.js:178:368)
    at react-dom.production.min.js:178:275
    at R (react.production.min.js:16:298)
ma @ 16.4a034ba.js:2
constructor @ 16.4a034ba.js:2
ec @ 16.4a034ba.js:2
(匿名) @ 997.cb56530.js:17
Tj @ react-dom.production.min.js:179
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
Ra @ react-dom.production.min.js:178
(匿名) @ react-dom.production.min.js:178
R @ react.production.min.js:16
ua.port1.onmessage @ react.production.min.js:22
DevTools 无法加载源映射： 无法加载https://cdn.jsdelivr.net/npm/@blessing-skin/admin-lte@3.1.1/dist/bootstrap.bundle.min.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by Windelight** [comment]
> 我估计是网络问题导致无法加载 jsDelivr 上的文件？

最后一个不是jsdelive的问题，因为我看npm的库上根本就没有这个文件

**Comment by g-plane** [comment]
那个没有是不会影响的。
