### ISSUE TITLE
[建议]在FAQ里增加open_basedir restriction in effect一节

### ISSUE THREAD

**Issue by HeartyYF** [bs-community/blessing-skin-server#37]
自从root改到public下，好像各种问题不断（笑
1.如果是php的问题，修改php.ini中open_basedir= ；若php.ini中此项未设置（已留空），则请往下看；
2.对于apache用户，httpd.conf中去掉所有open_basedir有关的行；
3.对于nginx用户，fastcgi.conf中去掉所有open_basedir有关的行。
可能会出问题吧（

**Comment by g-plane** [comment]
Laravel 本来是要求使用 public 目录的，但在 v3 为了照顾虚拟主机，所以通过一些手段改了。现在的结果就是，“宠坏”一堆用户。

**Comment by g-plane** [comment]
另外我也不清楚 `open_basedir` 有什么作用。

**Comment by KatyushaScarlet** [comment]
十分赞同，
今天花了很多时间排查错误，最后在懂php的朋友的帮助下，才知道是open_basedir的问题。
在FAQ中，当服务器出现http500错误且没有日志时，仅提到了“说明是您文件权限设置错误，请设置正确的文件权限。”
这行文字有些误导，可能导致用户花费很多时间精力去研究文件的权限是否有问题，但那并不一定是真正的错误所在。

我的建议：

当出现 500 Internal Server Error 错误时，应当修改php.ini中的“display_errors”为On，再根据页面找到具体的问题

**Comment by g-plane** [comment]
没有必要。首先，遇到错误就应该把调试模式打开（把 `APP_DEBUG` 设为 `true`），这一点在手册是有提到的。其次，`open_basedir` 问题在手册也有提到，并且 Blessing Skin v5 中在安装时会自动检测。

**Comment by KatyushaScarlet** [comment]
个人认为非常有必要。
首先，这个问题是我在初次安装时遇到的，若不注释掉open_basedir，连setup页面都打不开，更不会进入“自动检测”过程。

然而，即使我将APP_DEBUG设置为true，此时也不会输出任何log，错误表现和FAQ中提到的“文件权限错误”一模一样，即使文件权限是完全正确。

在我遇到的错误场景中，打开.env中的APP_DEBUG选项无济于事，只有开启php.ini中的"display_errors"才能发现错误。而这一点在手册中完全没有提及。

若不是启用了php.ini中的"display_errors"，甚至连“require: open_basedir restriction in effect. File is not within the allow path(s).”这行错误都不会见到，更使得用户无从下手。

最后，“open_basedir”字样不仅可能出现于php.ini中，也可能出现于vhost目录下的.user.ini文件中，而我是在nginx的"fastcgi.conf"文件中才找到。

希望能够加以改进，谢谢！

注：安装环境为lnmp.org，并非使用面板产品

**Comment by KatyushaScarlet** [comment]
附上我的log：

https://paste.ubuntu.com/p/ZMh3p8VGWx/

**Comment by g-plane** [comment]
手册是不打算改的，因为造成 500 的原因实在太多，把各种不同的原因都加在一起是不合理的。

开启 display_errors 倒是可以考虑。

**Comment by tnqzh123** [comment]
@KatyushaScarlet 如果要用一键包，这边建议 [OneinStack](https://oneinstack.com)，稳定好用，LittleSkin 从建站起就在用，几乎没有因为运行环境出过问题。

**Comment by KatyushaScarlet** [comment]
> @KatyushaScarlet 如果要用一键包，这边建议 [OneinStack](https://oneinstack.com)，稳定好用，LittleSkin 从建站起就在用，几乎没有因为运行环境出过问题。

感谢，我会去看看的

**Comment by KatyushaScarlet** [comment]
> 手册是不打算改的，因为造成 500 的原因实在太多，把各种不同的原因都加在一起是不合理的。
> 
> 开启 display_errors 倒是可以考虑。

谢谢，希望手册能够越来越完善
