### ISSUE TITLE
在访问时出现前端乱码问题

### ISSUE THREAD

**Issue by Cinnamoroll-cat** [bs-community/blessing-skin-server#375]
### Blessing Skin 版本

6.0

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Safari

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

界面排版错乱
![6AF0AD1B-8BBC-4EAE-9D38-C45FCE1A6D8D](https://user-images.githubusercontent.com/61970096/154230521-3d478a97-1272-45cb-9c55-9972dd8c2cb5.jpeg)

### 重现步骤

1. 打开网站
2. 出现问题

**Comment by Big-Cake-jpg** [comment]
jsDelivr 的锅，请考虑刷新或者使用代理或者手动写插件替换 AdminLTE 使用的 CDN

**Comment by Cinnamoroll-cat** [comment]
补一张图
![76936881-FDBF-4F89-97B0-D32112C60D7E](https://user-images.githubusercontent.com/61970096/154232320-6c3b5ff0-cd61-4878-933b-1c2be1d1a650.jpeg)

**Comment by Cinnamoroll-cat** [comment]
> jsDelivr 的锅，请考虑刷新或者使用代理或者手动写插件替换 AdminLTE 使用的 CDN

我刷新了整整10次，没有任何用处。
使用代理？我朋友是不可能的。
手动写插件太麻烦，而且更新完会自动恢复。最好是把前端和后端打包在一起，如果需要使用CDN或者jsDelivr，在资源配置中可以选择

**Comment by Big-Cake-jpg** [comment]
> > jsDelivr 的锅，请考虑刷新或者使用代理或者手动写插件替换 AdminLTE 使用的 CDN
> 
> 我刷新了整整10次，没有任何用处。 使用代理？我朋友是不可能的。 手动写插件太麻烦，而且更新完会自动恢复。最好是把前端和后端打包在一起，如果需要使用CDN或者jsDelivr，在资源配置中可以选择

插件会对皮肤站的一些地方进行覆盖，而且不会因为更新而失效。从目前来讲，这是最合适有效的手断了
g-plane 也在 Telegram 里提到，可以写插件来覆盖

**Comment by Cinnamoroll-cat** [comment]
> > > jsDelivr 的锅，请考虑刷新或者使用代理或者手动写插件替换 AdminLTE 使用的 CDN
> > 
> > 
> > 我刷新了整整10次，没有任何用处。 使用代理？我朋友是不可能的。 手动写插件太麻烦，而且更新完会自动恢复。最好是把前端和后端打包在一起，如果需要使用CDN或者jsDelivr，在资源配置中可以选择
> 
> 插件会对皮肤站的一些地方进行覆盖，而且不会因为更新而失效。从目前来讲，这是最合适有效的手段了 g-plane 也在 Telegram 里提到，可以写插件来覆盖

@Big-Cake-jpg 那插件开发文档作者好像没写

**Comment by Restent** [comment]
@Cinnamoroll-cat 目前 AdminLTE 已经不再使用 CDN 了，尝试更新然后再看看有没有相同的问题出现

**Comment by Cinnamoroll-cat** [comment]
请问为什么提示是最新版本？
