### ISSUE TITLE
Illegal string offset 'name'

### ISSUE THREAD

**Issue by 10935336** [bs-community/blessing-skin-server#38]
## The Problem 问题描述

从3.5.0更新到4.0.4后出现问题

## Environment 运行环境

- 4.0.4
- 7.3.2
- Nginx
- Chrome  https://10935336.moe/

## Error Message 错误信息

![image](https://user-images.githubusercontent.com/32383605/56469990-544f2380-6473-11e9-924d-0fb63ce5b1a9.png)

## Steps to Reproduce 重现步骤

从3.5.0更新到4.0.4后 出现Noinput file specified. 将网站目录用户设置为www:www后正常访问并进入主页，进入控制面板后又出现Noinput file specified. 刷新后成功进入，打开插件面板后安装一个插件之后彻底变成上图。

laravel.log文件中的记录：https://paste.ubuntu.com/p/tSxQYKNBMD/

**Comment by g-plane** [comment]
有没有把 web server 的根目录改为 `public` 目录？

**Comment by 10935336** [comment]
已经改过了
        root  /home/wwwroot/10935336.moe/public;

**Comment by g-plane** [comment]
了解，这应该是个与插件系统有关的 bug。

**Comment by 10935336** [comment]
那我还有救吗。

**Comment by g-plane** [comment]
临时的解决方法，进入数据库，打开 `options` 表，找到 `plugins_enabled` 一项，把它的值改为空字符串。

**Comment by 10935336** [comment]
清空后 皮肤站可以访问 
尝试安装yggdrasil-api后出现server error
然后皮肤站变为

![image](https://user-images.githubusercontent.com/32383605/56470829-73eb4980-647d-11e9-95c6-4a66aebc33b0.png)

**Comment by g-plane** [comment]
你安装了哪些插件？

**Comment by g-plane** [comment]
请确保所有插件都是最新版本。

**Comment by 10935336** [comment]
之前安装了
`["yggdrasil-api","report-texture","hello-dolly",{"name":"avatar-api","version":"1.1.1"},"batch-import","skin-utilities","bs-super-cache","redis","seo-meta-tags","get-score-by-sharing","config-generator","multi-index-style","register-email-validation"]`

清除数据库后安装了`更多首页样式`和`yggdrasil-api`

**Comment by g-plane** [comment]
「首页样式」并不支持 v4。

**Comment by g-plane** [comment]
v4 的市场没有「更多首页样式」，你是不是哪里搞错了？

**Comment by 10935336** [comment]
我这有....是源错了吗
![image](https://user-images.githubusercontent.com/32383605/56470898-579bdc80-647e-11e9-95cc-a6447d736b18.png)

**Comment by g-plane** [comment]
显然你的源是不对的。

**Comment by 10935336** [comment]
忘记了之前改过源地址，现已无问题 。感谢作者！

**Comment by g-plane** [comment]
能具体说说这个错误是发生在什么操作的时候吗？

**Comment by 10935336** [comment]
完成在终端的操作后，访问网页显示Noinput file specified. 
然后用chown -R www:www ./ 把网站目录改成了www用户
然后皮肤站可以正常访问了
进入管理面板，弹出一个错误。内容没有注意 。
进入插件市场，安装了一个插件（老版本源）
然后就像之前那样了，我觉得可能就是老版本的源的问题。

**Comment by g-plane** [comment]
这个是什么时候出现的？

![image](https://user-images.githubusercontent.com/32383605/56469990-544f2380-6473-11e9-924d-0fb63ce5b1a9.png)

**Comment by 10935336** [comment]
就是安装插件之后刷新几次显示Noinput file specified. 后来就彻底500了

**Comment by g-plane** [comment]
我是说上图的那个错误，那个不是 `No input file specified.`。

**Comment by 10935336** [comment]
我刷新了几次就变成这个了![image](https://user-images.githubusercontent.com/32383605/56469990-544f2380-6473-11e9-924d-0fb63ce5b1a9.png)

**Comment by g-plane** [comment]
行吧。
