### ISSUE TITLE
登录界面消失

### ISSUE THREAD

**Issue by ChengZhiNB** [bs-community/blessing-skin-server#385]
### Blessing Skin 版本

5.2.0

### PHP 版本

7.3

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [x] 是

### 出现了什么问题？

登录界面和注册界面没有输入框和登录或注册按钮
![Uploading YV7J@LA$DQGVYFNTD~CLV]O.png…]()

### 重现步骤

打开登录或注册界面

**Comment by Big-Cake-jpg** [comment]
你的日志呢？
> “在没有错误日志的情况下诊断问题无异于闭眼开车”
> ----- Apache 官方文档 Getting Start 篇章
