### ISSUE TITLE
无法正常使用URL获取头像

### ISSUE THREAD

**Issue by HIM049** [bs-community/blessing-skin-server#389]
### Blessing Skin 版本

 v6.0.0-rc.2

### PHP 版本

8.0

### 出现问题时所使用的浏览器

Chrome, Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [x] 是

### 出现了什么问题？

无法使用 WebAPI ` GET /avatar/player/{name} `获取正确的头像。无论用户是否存在均返回为默认头像（请求的对象存在并且有皮肤）

### 错误日志

此处为当日log文件
[laravel-2022-04-13.log](https://github.com/bs-community/blessing-skin-server/files/8477626/laravel-2022-04-13.log)

### 重现步骤

请求API便会发生该问题

**Comment by mochaaP** [comment]
cannot reproduce

**Comment by mochaaP** [comment]
我這裡是正常的，請確認你傳入的是「角色名」非「用戶名」。

**Comment by HIM049** [comment]
> 我這裡是正常的，請確認你傳入的是「角色名」非「用戶名」。

确实是发送了角色名的

**Comment by HIM049** [comment]
皮肤站以及数据库是从旧版本升级上来的，不知道是否有关联
