### ISSUE TITLE
对角色的修改或删除加以限制

### ISSUE THREAD

**Issue by hsiachihMain** [bs-community/blessing-skin-server#399]
是否能够给予后台更多的管理功能，例如
禁止修改角色id或修改角色id需要积分花费或需要冷却时间，禁止删除角色或删除需要积分花费之类的

因为我正在使用此皮肤站搭建服务器的外置登录，但是有一些熊孩子利用blessingskin无法在后台操控禁止修改id的问题疯狂更改id再加入游戏，然后就导致很多id都被挤占（我的服务器设置了id和验证方式共存，这些熊占用的id导致其他验证方式（如正版）无法再使用此id登入游戏）

**Comment by g-plane** [comment]
这些是也许能考虑的：

- 修改角色名需要积分

这些是不会去考虑的：

- 禁止修改角色名
- 修改角色名需要冷却时间
- 禁止删除角色
- 删除角色需要积分

虽然我不会去考虑，但是这些都能通过插件实现。

**Comment by hsiachihMain** [comment]
那作者大大能否考虑帮忙写一下这种插件加入插件市场qwq，，，我不会写，，，，谢谢，，，


当然不行也可以理解，，，总之谢谢作者大大了

**Comment by g-plane** [comment]
不能，「能通过插件实现」意思是可以自己写插件。
