### ISSUE TITLE
API 应用场景调查

### ISSUE THREAD

**Issue by g-plane** [bs-community/blessing-skin-server#40]
最近我们正在为 Blessing Skin 添加开放 API。如果您对此有兴趣，不妨参与这个调查，只需按下面的模板回复这个 issue 就行。

**应用需求和场景（简短描述）：**
**可能用到的编程语言：**

---

考虑到本 issue 太长，不方便讨论，建议各位如果有需求，可以开新的 issue 进行讨论。

---

已经在 v5 中实现的 API：

- [x] 创建角色、修改角色信息、删除角色
- [x] 操作衣柜
- [x] 获取当前用户基本信息
- [x] 读取通知、管理员发送通知
- [x] 管理员管理用户
- [x] 管理员对用户的角色进行管理
- [x] 管理员对用户的衣柜进行管理（暂不支持重命名物品）
- [x] 管理员管理举报

明确不会实现的 API：

- 签到并获取积分（会被滥用）
- 注册账号、找回密码

**Comment by xfl03** [comment]
应用需求和场景（简短描述）：游戏内/启动器更新角色皮肤
可能用到的编程语言：Java

**Comment by Colinwood11** [comment]
应用需求和场景（简短描述）：启动器更新角色皮肤/角色信息
可能用到的编程语言：易语言 233333

**Comment by zhzRedstone** [comment]
应用需求和场景（简短描述）：启动器更新角色皮肤/角色信息
可能用到的编程语言：C++

**Comment by zhzRedstone** [comment]
## 应用需求和场景（简短描述）：QQ机器人签到和积分互联
## 可能用到的编程语言：~~java~~ 易语言

**Comment by g-plane** [comment]
@zhzRedstone 你是想提供一个「签到」的 API？

**Comment by tnqzh123** [comment]
@zhzRedstone
> 应用需求和场景（简短描述）：QQ机器人签到和积分互联
> 可能用到的编程语言：易语言
我觉得这种场景直接操作数据库就好，API 有被滥用的风险（每日自动签到等）。

**Comment by zhzRedstone** [comment]
> @zhzRedstone
> 
> > 应用需求和场景（简短描述）：QQ机器人签到和积分互联
> > 可能用到的编程语言：易语言
> 
> 我觉得这种场景直接操作数据库就好，API 有被滥用的风险（每日自动签到等）。

err，，虚拟主机咋办？？

**Comment by zhzRedstone** [comment]
> > @zhzRedstone
> > > 应用需求和场景（简短描述）：QQ机器人签到和积分互联
> > > 可能用到的编程语言：易语言
> > 
> > 
> > 我觉得这种场景直接操作数据库就好，API 有被滥用的风险（每日自动签到等）。
> 
> err，，虚拟主机咋办？？

没法Remote MySQL 。。。写BS插件？？

**Comment by g-plane** [comment]
虚拟主机还玩什么 BS v4？

**Comment by tnqzh123** [comment]
@zhzRedstone 

> err，，虚拟主机咋办？？
没法Remote MySQL 。。。写BS插件？？

问 IDC 客服能不能从外部连接数据库，对 MC 服务端所在的服务器的 IP 加白什么的

@g-plane 

> 虚拟主机还玩什么 BS v4？

就是有些人想要在虚机上跑 v4 啊，难不成我们直接告诉他们不支持虚机吗

**Comment by xfl03** [comment]
看上去“更新角色皮肤/角色信息”呼声挺高呀，是否考虑先做这个？

**Comment by g-plane** [comment]
https://github.com/bs-community/blessing-skin-server/commit/122477c5c33f03516eb1962de5b18965f4347ba3
https://github.com/bs-community/blessing-skin-server/commit/d8bec1d1fb2d1ecd1a6460baae18cd5e052d7d93

**Comment by xfl03** [comment]
应用需求和场景（简短描述）：检测皮肤站是否使用BS API，只需要使用json或者纯文本输出一句“Proudly Powered by Blessing Skin”
可能用到的编程语言：Java

**Comment by g-plane** [comment]
不过文档还没写。

**Comment by g-plane** [comment]
> 应用需求和场景（简短描述）：检测皮肤站是否使用BS API，只需要使用json或者纯文本输出一句“Proudly Powered by Blessing Skin”
> 可能用到的编程语言：Java

已经有这个计划。

**Comment by xfl03** [comment]
> 应用需求和场景（简短描述）：检测皮肤站是否使用BS API，只需要使用json或者纯文本输出一句“Proudly Powered by Blessing Skin”
> 可能用到的编程语言：Java

我的想法是CSL会通过检测版权文本的方式来识别是否为BS，如果用户强行修改了版权文本，恕不提供服务。

**Comment by g-plane** [comment]
可以啊，我在 JSON 中加一个字段，如何？

**Comment by xfl03** [comment]
> 可以啊，我在 JSON 中加一个字段，如何？（根 endpoint）

请问可以看一下修改后的根endpoint内容有什么吗？

**Comment by g-plane** [comment]
还没实现，大概是这样的：

```json
{
  "blessing-skin": "(BS 版本)",
  "spec": "（API 版本）",
  "copyright": "（版权信息）"
}
```

**Comment by xfl03** [comment]
@g-plane 感觉没什么问题

**Comment by g-plane** [comment]
API 文档：https://bs-community.github.io/blessing-skin-api-docs/

**Comment by 1871847400** [comment]
应用需求和场景（简短描述）：启动器注册账号，找回账号
可能用到的编程语言：Java

**Comment by g-plane** [comment]
> 应用需求和场景（简短描述）：启动器注册账号，找回账号
> 可能用到的编程语言：Java

这个不考虑去实现。

**Comment by xfl03** [comment]
应用需求和场景（简短描述）：允许皮肤站管理员自由选择是否加入CustomSkinLoader数据统计计划，提供开启/关闭/公开三个选项，默认关闭，公开会直接进入数据统计计划的排行榜中，开启后用户可以通过皮肤站地址查看皮肤站在CustomSkinLoader用户中的占有率。此过程不需要BlessingSkin主动上传任何数据。
可能用到的编程语言：Java

**Comment by hempflower** [comment]
应用需求和场景（简短描述）：加入后台管理API（如用户封禁，积分修改等）可方便与其他程序联动（如反作弊可直接封禁用户账户，或在游戏内获得皮肤站积分奖励）
可能用到的编程语言：Any

**Comment by xixikudo** [comment]
虽然好像和API没什么关系……我在想，能不能加入使用邀请码才可以注册这种方式

**Comment by tnqzh123** [comment]
@xixikudo 这种问题应该开一个新的 Issue 来询问，而不是在现有的毫不相关的 Issues 下直接回复提问。

对于你的问题，请在插件市场中下载并安装「注册邀请码」插件（插件唯一标识符 `invitation-code`）。

**Comment by Simba98** [comment]
应用需求和场景（简短描述）：（背景）服务器允许正版用户登陆及YGG本地登陆；并且
1.正版登陆默认加载原版皮肤站，【且绑定本皮肤站后，可以加载自定义皮肤及披风】
2.本站注册用户可以在服务器内登陆，加载本站皮肤披风
可能用到的编程语言：Java PHP(?)

**Comment by tnqzh123** [comment]
@Simba98 这种需求我觉得应该交给 Yggdrasil API 插件来处理。

1. 想法很美好，也不是没有人提出过，但是实现起来基本不可能。Minecraft 有对材质进行签名校验，每个皮肤站签名时使用的 RSA 密钥对都不一样。原版 Minecraft 内只有 Mojang 的公钥，没有皮肤站的公钥（皮肤站的公钥是由 authlib-injector 在获取 Yggdrasil API 元数据时从服务端响应中取得的），所以无法使用来自皮肤站的材质（除非使用 CustomSkinLoader 并更改加载列表，但是很显然这样就不算是「原版」了）。
2. 这就是 BS 的 Yggdrasil API 的基本功能。

**Comment by Simba98** [comment]
> @Simba98 这种需求我觉得应该交给 Yggdrasil API 插件来处理。
> 
> 想法很美好，也不是没有人提出过，但是实现起来基本不可能。Minecraft 有对材质进行签名校验，每个皮肤站签名时使用的 RSA 密钥对都不一样。原版 Minecraft 内只有 Mojang 的公钥，没有皮肤站的公钥（皮肤站的公钥是由 authlib-injector 在获取 Yggdrasil API 元数据时从服务端响应中取得的），所以无法使用来自皮肤站的材质（除非使用 CustomSkinLoader 并更改加载列表，但是很显然这样就不算是「原版」了）。
> 这就是 BS 的 Yggdrasil API 的基本功能。

@tnqzh123 好像是的，Ygg API插件可以转发Mojang登陆请求；不过我也提到了我注意到了YGG插件支持了，所以说，要达成我的想法其实已经存在，只需要：
1 服务端加载authlib和（另一个服务端加载）Blessing Skin的Yggdrasil插件
2 客户端加载authlib和CustomSkinLoader

然而仅通过BS是没有可能实现的。

**Comment by tnqzh123** [comment]
@Simba98

> 好像是的，Ygg API插件可以转发Mojang登陆请求；不过我也提到了我注意到了YGG插件支持了，所以说，要达成我的想法其实已经存在，只需要：  
  1 服务端加载authlib和（另一个服务端加载）Blessing Skin的Yggdrasil插件  
  2 客户端加载authlib和CustomSkinLoader
  
  然而仅通过BS是没有可能实现的。

我不明白你的意思…

1. 两个服务端？你不是所有玩家都加入同一 Minecraft 服务器的吗？「另一个服务端

**Comment by Colinwood11** [comment]
> > @Simba98 这种需求我觉得应该交给 Yggdrasil API 插件来处理。
> > 想法很美好，也不是没有人提出过，但是实现起来基本不可能。Minecraft 有对材质进行签名校验，每个皮肤站签名时使用的 RSA 密钥对都不一样。原版 Minecraft 内只有 Mojang 的公钥，没有皮肤站的公钥（皮肤站的公钥是由 authlib-injector 在获取 Yggdrasil API 元数据时从服务端响应中取得的），所以无法使用来自皮肤站的材质（除非使用 CustomSkinLoader 并更改加载列表，但是很显然这样就不算是「原版」了）。
> > 这就是 BS 的 Yggdrasil API 的基本功能。
> 
> @tnqzh123 好像是的，Ygg API插件可以转发Mojang登陆请求；不过我也提到了我注意到了YGG插件支持了，所以说，要达成我的想法其实已经存在，只需要：
> 1 服务端加载authlib和（某一个服务器的）Blessing Skin的Yggdrasil插件
> 2 客户端加载authlib和CustomSkinLoader
> 
> 然而仅通过BS是没有可能实现的。

通过BS  改YGG插件如果用户名不存在就取原版皮肤，理论上是OK的叭？
而正版登入就不知道了

**Comment by Simba98** [comment]
应该是OK的吧？
https://github.com/bs-community/yggdrasil-api/issues/4#issuecomment-511339345
这里说已经实现了。
尽管我暂时没想明白怎么实现的（逃
总之，我旨在参与本次小调查，并向开发组提供我的需求想法。

**Comment by Colinwood11** [comment]
> > @Simba98 这种需求我觉得应该交给 Yggdrasil API 插件来处理。
> > 想法很美好，也不是没有人提出过，但是实现起来基本不可能。Minecraft 有对材质进行签名校验，每个皮肤站签名时使用的 RSA 密钥对都不一样。原版 Minecraft 内只有 Mojang 的公钥，没有皮肤站的公钥（皮肤站的公钥是由 authlib-injector 在获取 Yggdrasil API 元数据时从服务端响应中取得的），所以无法使用来自皮肤站的材质（除非使用 CustomSkinLoader 并更改加载列表，但是很显然这样就不算是「原版」了）。
> > 这就是 BS 的 Yggdrasil API 的基本功能。
> > @tnqzh123 好像是的，Ygg API插件可以转发Mojang登陆请求；不过我也提到了我注意到了YGG插件支持了，所以说，要达成我的想法其实已经存在，只需要：
> > 1 服务端加载authlib和（某一个服务器的）Blessing Skin的Yggdrasil插件
> > 2 客户端加载authlib和CustomSkinLoader
> > 然而仅通过BS是没有可能实现的。
> > 通过BS  改YGG插件如果用户名不存在就取原版皮肤，理论上是OK的叭？
> > 而正版登入就不知道了
> 
> 应该是OK的吧？
> [bs-community/yggdrasil-api#4 (comment)](https://github.com/bs-community/yggdrasil-api/issues/4#issuecomment-511339345)
> 这里说已经实现了。
> 尽管我暂时没想明白怎么实现的（逃
> 总之，我旨在参与本次小调查，并向开发组提供我的需求想法。
> @Colinwood11

哈哈哈  稍微有点尴尬

**Comment by Simba98** [comment]
@Colinwood11 
没什么啊，互相交流嘛。
@tnqzh123 所以我上面说的好像有点多余，客户端应该只需要加载authlib就可以了吧？

**Comment by 1925473403** [comment]
应用需求和场景（简短描述）：启动器内注册，管理角色，皮肤
可能用到的编程语言：易语言

**Comment by 8MiYile** [comment]
应用场景和需求(简单描述):对接8Mi统一验证系统
可能用到的编程语言:PHP

**Comment by tnqzh123** [comment]
@8MiYile 
> 应用场景和需求(简单描述):对接8Mi统一验证系统
> 可能用到的编程语言:PHP

你这应用场景和需求描述地也太简单了吧？至少说清楚“8Mi 统一验证系统”的一些具体细节，或者提供文档啊。

**Comment by pentyum** [comment]
应用场景和需求(简单描述):支持使用JASIG CAS登录，地址https://apereo.atlassian.net/wiki/spaces/CASC/pages/103252517/phpCAS
可能用到的编程语言:PHP

**Comment by g-plane** [comment]
@pentyum 如果能使用 OAuth2，尽量用 OAuth2。不过我没有了解过那个应用，不太清楚。

**Comment by WC12366** [comment]
@1925473403 这垃圾语言谁用？和你在C里面define几个宏是一模一样的

**Comment by g-plane** [comment]
@WC12366 请文明用语。

**Comment by WC12366** [comment]
> @WC12366 请文明用语。

主要是我觉得这个语言开发效率太低而且还要钱

**Comment by zhzRedstone** [comment]
使用http post发送bs通知
可能用到的编程语言: python

**Comment by longhuan1999** [comment]
> @zhzRedstone
> 
> > 应用需求和场景（简短描述）：QQ机器人签到和积分互联
> > 可能用到的编程语言：易语言
> 
> 我觉得这种场景直接操作数据库就好，API 有被滥用的风险（每日自动签到等）。

我其实并不在意用户使用自动签到脚本，或者说我期望有能力的人这么做

**Comment by tnqzh123** [comment]
@longhuan1999 

> 我其实并不在意用户使用自动签到脚本，或者说我期望有能力的人这么做

你不在意，但是别人在意。

如果真的有这方面的需求，可以自己写插件。

**Comment by longhuan1999** [comment]
> > 应用需求和场景（简短描述）：启动器注册账号，找回账号
> > 可能用到的编程语言：Java
> 
> 这个不考虑去实现。

其实，如果有能力的化，我自己可以去实现

**Comment by longhuan1999** [comment]
> > 应用需求和场景（简短描述）：启动器注册账号，找回账号
> > 可能用到的编程语言：Java
> 
> 这个不考虑去实现。

其实，如果有能力的化，我们自己可以去实现

**Comment by g-plane** [comment]
讨论前请先阅读本 Issue 上面写了哪些已经实现、哪些明确不会实现。此 Issue 已经很长了，不要进行不必要的讨论。谢谢合作。

**Comment by g-plane** [comment]
考虑到本 issue 太长，不方便讨论，建议各位如果有需求，可以开新的 issue 进行讨论。
