### ISSUE TITLE
维护第三方更新源

### ISSUE THREAD

**Issue by Blank038** [bs-community/blessing-skin-server#400]
### 维护第三方更新源
程序自动 clone 仓库文件(Blessing Skin Server)
最新版(拉取到的)：https://cdn.mc9y.com/bs/update.json
旧版(曾经被拉取过的)：https://cdn.mc9y.com/bs/{version}/update.json
(此项未完工本地 update.json 文件生成，有空了修改下程序代码)

之前发在：https://github.com/bs-community/blessing-skin-server/discussions/345
似乎没有人理会，所以来提交一下 issue

**Comment by Big-Cake-jpg** [comment]
what
你开错地方了，请去 bs-community/blessing-skin-manual 仓库
发在这里无法合并

**Comment by Blank038** [comment]
> what 你开错地方了，请去 bs-community/blessing-skin-manual 仓库 发在这里无法合并

抱歉，之前没有注意到手册的仓库。
