### ISSUE TITLE
/vendor/twig/twig/src/Environment.php宝塔查杀报webshell

### ISSUE THREAD

**Issue by xbebhxx3** [bs-community/blessing-skin-server#404]
### Blessing Skin 版本

v6.0.0-rc.2

### PHP 版本

8.0

### 出现问题时所使用的浏览器

Chrome

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

/vendor/twig/twig/src/Environment.php宝塔查杀报webshell

### 重现步骤

n

**Comment by vlssu** [comment]
我觉得他们不会理你。
