### ISSUE TITLE
使用反向代理时皮肤站向导不能正常工作

### ISSUE THREAD

**Issue by shacha086** [bs-community/blessing-skin-server#406]
### Blessing Skin 版本

rc2

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Firefox, Chrome, Safari, Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

使用反代时皮肤站向导不能正常工作（因为无法完成向导，所以暂时不知道是否有其他影响）
![AEO 1XQYVB{1QEQH`LGAOMP](https://user-images.githubusercontent.com/50512232/168464928-bf1c1f37-9c4c-4308-930d-953c9fbb80dc.png)
↑向导页面
↓点击下一步后
![G5BJ3HRC(Y (QVMARR4P733](https://user-images.githubusercontent.com/50512232/168464960-2e205468-21e7-4483-8e1a-e15e4a532fdd.png)

这里网站被重定向至代理域名，无法正常访问

### 错误日志

```text
没有错误日志
```

### 重现步骤

正常安装，打开<域名>/setup，点击下一步

**Comment by MBRjun** [comment]
#407
