### ISSUE TITLE
网页图片、样式消失

### ISSUE THREAD

**Issue by WillowKoishi** [bs-community/blessing-skin-server#408]
### Blessing Skin 版本

6.0.0beta

### PHP 版本

8.0

### 出现问题时所使用的浏览器

Chrome

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

网页已稳定运行半年，在今天出事
网页几乎只有文本，无法正常使用，MC服务器也无法正常获取用户数据[https://s1.ax1x.com/2022/05/17/O4dlBd.png](url)

### 错误日志

```text
DEBUG设为true，没有日志输出
```

### 重现步骤

访问皮肤站即可http://skin.fairingstudio.top/

**Comment by shacha086** [comment]
使用代理即可，jsdelivr被大陆墙了

**Comment by WillowKoishi** [comment]
> 使用代理即可，jsdelivr被大陆墙了

服务端ping了一下都能ping到的，ping不到也转成了 jsdelivr.map.fastly.net

**Comment by shacha086** [comment]
> > 使用代理即可，jsdelivr被大陆墙了
> 
> 服务端和本地电脑ping了一下都能ping到的，ping不到也转成了 jsdelivr.map.fastly.net

你开f12看一下就知道了x挂梯子秒开
