### ISSUE TITLE
用户无法加载cdn.jsdelivr.net的js与css

### ISSUE THREAD

**Issue by xiamo070091** [bs-community/blessing-skin-server#410]
### Blessing Skin 版本

6.0.0 RC2

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Chrome

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

用户无法正确的获取到css样式与js脚本，导致页面排版错乱
![QQ图片20220518220330](https://user-images.githubusercontent.com/30163365/169063922-d87e7443-1169-40b8-ad57-6a4e957b61b2.png)
![QQ图片20220518220159](https://user-images.githubusercontent.com/30163365/169063963-755b7a29-f6bd-4b81-a07a-19c2a22a699b.png)

### 错误日志

```text
没有错误日志
```

### 重现步骤

用户在某些网络情况下，使用谷歌浏览器（我测试版本 101.0.4951.67（正式版本） （64 位））无法正常打开

**Comment by zhichengYang-GitHub** [comment]
同上

**Comment by ColdTearsYY** [comment]
同上

**Comment by WeiMiao-Xin** [comment]
可以把皮肤站的文件拉下使用“Visual Studio Code”或者其他工具
把：“https://cdn.jsdelivr.net/npm/react@17.0.1/umd/”替换为“../skin/”
在下载[skin.zip](https://github.com/bs-community/blessing-skin-server/files/8746095/skin.zip)上传至网站根目录中的public解压
确保你的路径是“网站根目录\public\skin\”这个目录是存在的

**Comment by WeiMiao-Xin** [comment]
可以把皮肤站的文件下载下来使用“Visual Studio Code”或者其他工具
把：“文件前的链接”替换为“/skin/”
如：https://cdn.jsdelivr.net/npm/react@17.0.1/umd/react.production.min.js 替换：/skin/react.production.min.js
再下载
[skin.zip](https://github.com/bs-community/blessing-skin-server/files/8746123/skin.zip)
上传至网站根目录中的public解压
确保你的路径是“网站根目录\public\skin\”这个目录是存在的
重新上传覆盖，这只能暂时性的解决问题

**Comment by Big-Cake-jpg** [comment]
jsDelivr 在中国大陆境内已经开始受到 DNS 污染与 TCP 连接重置了。最新的开发版本已经将 jsDelivr 替换为了 UNPKG，去 Actions 找 Artifact 就行

**Comment by MuYouYuanNing** [comment]
> jsDelivr 在中国大陆境内已经开始受到 DNS 污染与 TCP 连接重置了。最新的开发版本已经将 jsDelivr 替换为了 UNPKG，去 Actions 找 Artifact 就行

就是说新版本可以解决吗？

**Comment by Big-Cake-jpg** [comment]
@MuYouYuanNing 自己手动改twig模版也可以解决

**Comment by 12skoko** [comment]
> 

能直接改一个地方的吗，我是用的文件查找把所有带jsDelivr的链接全手动替换了

**Comment by 12skoko** [comment]
> @MuYouYuanNing 自己手动改twig模版也可以解决

能直接改一个地方的吗，我是用的文件查找把所有带jsDelivr的链接全手动替换了

**Comment by Big-Cake-jpg** [comment]
@12skoko 你改 header.twig（还是 head.twig 来着我忘了）就行了，保存以后刷新即可

**Comment by 12skoko** [comment]
> @12skoko 你改 header.twig（还是 head.twig 来着我忘了）就行了，保存以后刷新即可

喔喔好的谢谢

**Comment by Big-Cake-jpg** [comment]
@12skoko 注意，你得先将原模版复制一份，丢到 overrides 文件夹（还是 override 来着）。不然以后更新你的更改会被覆盖

**Comment by xqzr** [comment]
nginx.conf
```conf
server {
  ...
  sub_filter 'cdn.jsdelivr.net' 'fastly.jsdelivr.net';
  sub_filter_once off;
  sub_filter_types *;
  ...
}
```

**Comment by MuYouYuanNing** [comment]
> @MuYouYuanNing 自己手动改twig模版也可以解决

我想问问这应该怎么修改，纯小白qwq

**Comment by MuYouYuanNing** [comment]
> nginx.conf
> 
> ```
> server {
>   ...
>   sub_filter 'cdn.jsdelivr.net' 'fastly.jsdelivr.net';
>   sub_filter_once off;
>   sub_filter_types *;
>   ...
> }
> ```

您好，我想问下是直接在配置里新加就可以吗
![image](https://user-images.githubusercontent.com/105966926/169675369-7f111bdc-30cd-40cd-b676-7ccd4ed15430.png)

**Comment by xqzr** [comment]
> 
> 您好，我想问下是直接在配置里新加就可以吗 ![image](https://user-images.githubusercontent.com/105966926/169675369-7f111bdc-30cd-40cd-b676-7ccd4ed15430.png)

❌

**Comment by MuYouYuanNing** [comment]
> 

我想问问应该怎么弄呢，求教一下

**Comment by xqzr** [comment]
> 
> 我想问问应该怎么弄呢，求教一下

存在 `include` 情况就不一样了。
在皮肤站的 `server` 区块里添加。

**Comment by R3Or7eN** [comment]
> @12skoko 你改 header.twig（还是 head.twig 来着我忘了）就行了，保存以后刷新即可

不行呀 还是最好把shared文件夹里的有的都改改 要不还是有些页面显示不出

**Comment by MuYouYuanNing** [comment]
> > 我想问问应该怎么弄呢，求教一下
> 
> 存在 `include` 就可能不是改 nginx.conf 了。 在皮肤站的 `server` 区块里添加。

皮肤站的配置文件里吗？大佬我用的是宝塔皮肤站的配置文件是这样子的，应该加到哪里啊
![image](https://user-images.githubusercontent.com/105966926/169804445-df4265a4-7885-40cb-a0e9-913a0ee9e13a.png)

**Comment by MuYouYuanNing** [comment]
> > 我想问问应该怎么弄呢，求教一下
> 
> 存在 `include` 就可能不是改 nginx.conf 了。 在皮肤站的 `server` 区块里添加。

大佬我将你给的配置这样子写进去了，似乎可以了，这样子写是正确的吗？
![image](https://user-images.githubusercontent.com/105966926/169805977-eb94db4a-2f75-42e6-b13c-391e6057cb47.png)

**Comment by xqzr** [comment]
> 
> 大佬我将你给的配置这样子写进去了，似乎可以了，这样子写是正确的吗？ ![image](https://user-images.githubusercontent.com/105966926/169805977-eb94db4a-2f75-42e6-b13c-391e6057cb47.png)

~~能用就好~~

**Comment by lvtenghui** [comment]
可以写一下apache的配置嘛！感谢

**Comment by zxj199884** [comment]
同上，可以写一下apache的配置嘛，或者尽快更新出新的版本，谢谢！

**Comment by moligod** [comment]
> include

![image](https://user-images.githubusercontent.com/89651085/170836715-ffb86277-cd06-4ca7-bd17-03f4a1aab309.png)
设置后依旧还是刷不出来大佬

**Comment by NiuBoss123** [comment]
cdn.jsdelivr.net炸了啊，我好些文档网站都用不了（应该是炸了）

**Comment by moligod** [comment]
> cdn.jsdelivr.net 炸了啊，我好些文档网站都用不了（应该是炸了）

你昨天炸的还是今天，我昨天开始炸的

**Comment by NiuBoss123** [comment]
> > cdn.jsdelivr.net 炸了啊，我好些文档网站都用不了（应该是炸了）
> 
> 你昨天炸的还是今天，我昨天开始炸的

一个星期了吧，我住校没注意网站，今天回家一看都傻眼了

**Comment by moligod** [comment]
我在我的博客写了一个修改cdn.jsdelivr的教程如果有小白不懂得可以看这个教程https://moligod.com/jsdelivr1/

**Comment by Big-Cake-jpg** [comment]
@zxj199884 换成 fastly 并不能长久解决问题，最好的办法是更换为国内速度好的 CDN，如 npm.elemecdn.com 或者直接使用 unpkg 作为替代

**Comment by ZhaoZuohong** [comment]
补一个Apache的替换方法：
```
AddOutputFilterByType SUBSTITUTE text/html
Substitute "s/cdn.jsdelivr.net/fastly.jsdelivr.net/ni"
```

**Comment by Abandoned9** [comment]
fastly.jsdelivr.net最近也开始阵亡了，建议nginx里直接替换成unpkg
nginx替换如下

`sub_filter 'https://cdn.jsdelivr.net/npm/' 'https://unpkg.com/';
    sub_filter_once off;
    sub_filter_types *;`

**Comment by Big-Cake-jpg** [comment]
这个 Issue 可以关了，`cdn.jsdelivr.net` 已经恢复了

如果有些人不想再出问题，皮肤站目录 `/resources/views/shared/head.twig` 复制一份，放到 `/resources/views/overrides/shared/` 下，将 `cdn.jsdelivr.net` 改为 `unpkg.com` 或 `npm.elemecdn.com`
