### ISSUE TITLE
无法加载图片

### ISSUE THREAD

**Issue by Icetebe** [bs-community/blessing-skin-server#411]
### Which version of Blessing Skin are you using?

v6.0.0-rc.2

### Which version of PHP are you using?

8.0

### What browsers are you seeing the problem on?

Chrome

### Which web server are you using?

Apache

### What happened?

![image](https://user-images.githubusercontent.com/47298124/169840417-6a28f4cd-8a23-43a3-895a-143a67188dd4.png)
Apache 2.4.52
页面排版混乱只有文字，缓存出错

### Steps to Reproduce

在国内访问皮肤站

**Comment by xqzr** [comment]
#410

**Comment by mochaaP** [comment]
closing as dup of #410
