### ISSUE TITLE
绑定角色UI显示错误无法正常绑定

### ISSUE THREAD

**Issue by vlssu** [bs-community/blessing-skin-server#413]
### Blessing Skin 版本

Jun 3, 2022 663d9120b660681df13bb17b229ee550ebbfd6c1

### PHP 版本

8.0

### 出现问题时所使用的浏览器

Chrome

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

启用单角色插件时（并且开启了正版验证）登录时需要绑定角色，但ui显示不全导致不能绑定，并一直循环
![CI6D15S Q6KNS2DT~YEVF_V](https://user-images.githubusercontent.com/43847794/172275978-35078913-85cd-4c89-a6a5-e40e15e4ca32.png)

### 错误日志

```text
这是网页错误，没有报错
```

### 重现步骤

1. 启用单角色插件
2. 开启了正版验证
3. 直接用正版账户登录即可复现

**Comment by graytoowolf** [comment]
https://unpkg.com/react@17/umd/react.production.min.js
https://unpkg.com/react-dom@17/umd/react-dom.production.min.js
 
是缺了这2个JS文件。

**Comment by syrrro** [comment]
> https://unpkg.com/react@17/umd/react.production.min.js https://unpkg.com/react-dom@17/umd/react-dom.production.min.js
> 
> 是缺了这2个JS文件。

我也遇到了这种情况
请问有解决方法吗

**Comment by graytoowolf** [comment]
> > https://unpkg.com/react@17/umd/react.production.min.js https://unpkg.com/react-dom@17/umd/react-dom.production.min.js
> > 是缺了这2个JS文件。
> 
> 我也遇到了这种情况 请问有解决方法吗

1.
<script src="https://unpkg.com/react@18/umd/react.production.min.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js" crossorigin></script>
添加上面这两行到“ resources/views/shared/head.twig”这个文件。这样做每个页面都添加这2个JS了
![QQ截图20220609211035](https://user-images.githubusercontent.com/57069542/172855036-2d874eac-042d-43c0-a538-bfbf660b603a.png)

2：
下载这两个JS文件放到插件“plugins/single-player-limit/assets”下面，添加
    Hook::addScriptFileToPage($plugin->assets('react.js'), ['user/player/bind']);
    Hook::addScriptFileToPage($plugin->assets('react-dom.js'), ['user/player/bind']);

“plugins/single-player-limit/bootstrap.php”到这个文件。
![QQ截图20220609210934](https://user-images.githubusercontent.com/57069542/172854878-06f484bf-daaf-44a5-a2e0-3724850db739.png)

**Comment by vlssu** [comment]
> > > https://unpkg.com/react@17/umd/react.production.min.js https://unpkg.com/react-dom@17/umd/react-dom.production.min.js
> > > 是缺了这2个JS文件。
> > 
> > 
> > 我也遇到了这种情况 请问有解决方法吗
> 
> 
> <script src="https://unpkg.com/react@18/umd/react.production.min.js" crossorigin></script> <script src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js" crossorigin></script>
> 添加上面这两行到“ resources/views/shared/head.twig”这个文件。这样做每个页面都添加这2个JS了 ![QQ截图20220609211035](https://user-images.githubusercontent.com/57069542/172855036-2d874eac-042d-43c0-a538-bfbf660b603a.png)
> 
> 2： 下载这两个JS文件放到插件“plugins/single-player-limit/assets”下面，添加 Hook::addScriptFileToPage($plugin->assets('react.js'), ['user/player/bind']); Hook::addScriptFileToPage($plugin->assets('react-dom.js'), ['user/player/bind']);
> 
> “plugins/single-player-limit/bootstrap.php”到这个文件。 ![QQ截图20220609210934](https://user-images.githubusercontent.com/57069542/172854878-06f484bf-daaf-44a5-a2e0-3724850db739.png)

![image](https://user-images.githubusercontent.com/43847794/174323634-0b8583ec-b27d-47bf-92bd-0d2b8ddf1991.png)
依旧出现了问题。

**Comment by vlssu** [comment]
> 最新开发版已经修复这个问题了

![image](https://user-images.githubusercontent.com/43847794/174327397-c56f20cf-296f-4fcd-a144-c20334fb162d.png)

好了，虽然有文字缺失，，，（文字缺失可能是我的问题。。
