### ISSUE TITLE
启用插件后提示Call to undefined method Event::listen()

### ISSUE THREAD

**Issue by sunlogo-soto** [bs-community/blessing-skin-server#415]
### Blessing Skin 版本

6.0.0-rc2

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [x] 是

### 出现了什么问题？

在插件市场下载并在插件管理中**启用某些插件后Blessing Skin提示Call to undefined method Event::listen()。**
**已知会引起问题的插件**包括：
1. 配置生成（config-generator）
2. OAuth客户端核心（OAuth）
3. 邮箱域名限制（restricted-email-domains）
4. 单角色限制（single-player-limit）
5. 材质描述（texture-description）
6. Universal Skin API（usm-api）
7. 以及最重要的Yggdrasil API（yggdrasil-api）

### 错误日志

```text
日志太长了无法粘贴，点击这里查看：https://leaphorizon.libreserver.xyz:1234/down/tR2TvnvWLNGL
抱歉＞︿＜
```

### 重现步骤

在插件市场里**下载了**上述会引起问题的插件（**此时并无异常**）
在插件管理里**启用了**上述会引起问题的插件（**表面上**仍无异常）
点击其它插件的启用开关或刷新或进入任意界面提示**Call to undefined method Event::listen()**
【注：在后台删去插件文件夹便可恢复正常，但因为影响了最核心的Yggdrasil API，故来反馈】

**Comment by mochaaP** [comment]
看不到 log
請貼到 <https://fars.ee>
