### ISSUE TITLE
我的衣柜页面打开为空白等 [V6.0.0]

### ISSUE THREAD

**Issue by DeepFal** [bs-community/blessing-skin-server#419]
### Blessing Skin 版本

V6.0.0

### PHP 版本

8.0

### 出现问题时所使用的浏览器

Chrome

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [x] 是

### 出现了什么问题？

我的衣柜页面打开为空白
角色管理页面资源加载不正常
后台举报管理页面有如图报错
仪表盘页面有如图报错
![1655601056488.png](https://cc.deepfal.cn/2022/06/19/62ae77a1e6e9a.png)
![1655601067796.png](https://cc.deepfal.cn/2022/06/19/62ae77ad95399.png)
![1655601076938.png](https://cc.deepfal.cn/2022/06/19/62ae77b67e55f.png)
![1655601108698.png](https://cc.deepfal.cn/2022/06/19/62ae77d65a755.png)
服务器信息如下
![1655601179393.png](https://cc.deepfal.cn/2022/06/19/62ae781cd6da7.png)

### 错误日志

```text
未生成日志文件
```

### 重现步骤

之前没注意 更新6.0.0之后检查功能发现

**Comment by graytoowolf** [comment]
15号的开发版有这个问题.17号的版本就修复了.看看你是什么时候编译的

**Comment by DeepFal** [comment]
> 15号的开发版有这个问题.17号的版本就修复了.看看你是什么时候编译的

我是从rc版本自动更新的

**Comment by DeepFal** [comment]
> 15号的开发版有这个问题.17号的版本就修复了.看看你是什么时候编译的

需要重新手动更新一下吗

**Comment by graytoowolf** [comment]
你要么安装正式版6.0的.开发版需要自己编译才行. 使用开发版是有风险的.

**Comment by mochaaP** [comment]
清除快取後重試。

**Comment by DeepFal** [comment]
> 清除快取後重試。

我没有使用CDN服务 浏览器缓存也刷新了

**Comment by DeepFal** [comment]
> 去后台删除public文件夹。再重新解压最新的

我尝试了你说的方法 但是报错并没有变化 我清理了浏览器缓存

**Comment by mochaaP** [comment]
fixed in <https://github.com/bs-community/blessing-skin-server/commit/68701d1b3c9665bf47039a2bedd8b0a440fa43b1>
