### ISSUE TITLE
提交BS公共更新源

### ISSUE THREAD

**Issue by LHY2355** [bs-community/blessing-skin-server#42]
地址https://bs-cdn.minttang.cn/update.json
名称:MintTang-BS-UP

**Comment by tnqzh123** [comment]
@LHY2355 描述呢？

**Comment by tnqzh123** [comment]
![Screenshot_20190427-065619_Chrome.png](https://i.loli.net/2019/04/27/5cc38cab0f2a3.png)
看起来不能正常访问？检查你的 Web 服务器配置

**Comment by g-plane** [comment]
现在能访问了，但还是 v3 的更新信息。

**Comment by tnqzh123** [comment]
@g-plane 我这还是无法访问（`ERR_SPDY_PROTOCOL_ERROR`），不知道是不是我的问题
Close 是误操作，sry :-(

**Comment by g-plane** [comment]
![图片](https://user-images.githubusercontent.com/17216317/56844057-e5435600-68dc-11e9-86fa-a2ff994b2580.png)

**Comment by LHY2355** [comment]
V4的暂时不知道怎么写。哪个updatetime不知道在那获取，所以没敢写

**Comment by LHY2355** [comment]
> @ LHY2355描述呢？
> （虽然描述不是必需的，但是我觉得还是问一下比较好，不想添加描述就直接回复“没有”就好

没有也可以把

**Comment by g-plane** [comment]
官方怎么写，你就怎么写。实际上，官方那里是一个 Git 仓库，你可以直接 clone 下来然后把 URL 修改就行。

**Comment by LHY2355** [comment]
> @g-plane 我这还是无法访问（`ERR_SPDY_PROTOCOL_ERROR`），不知道是不是我的问题
> Close 是误操作，sry :-(
可能你开了代理？

**Comment by tnqzh123** [comment]
@LHY2355 不是代理的问题，不过我现在也能访问了🤔

**Comment by LHY2355** [comment]
@tnqzh123 有点神奇，不过V4更新源写法我还是不会，有没有例子参考下

**Comment by tnqzh123** [comment]
@LHY2355 官方源怎么写你就怎么写
v4 的官方源把很多不必要的信息都精简了

**Comment by g-plane** [comment]
https://dev.azure.com/blessing-skin/_git/Blessing%20Skin%20Server

**Comment by LHY2355** [comment]
@tnqzh123 我没看到官方源....

**Comment by LHY2355** [comment]
@g-plane 好的

**Comment by g-plane** [comment]
可以直接 clone 那个仓库。

**Comment by LHY2355** [comment]
已更改，
V3:https://bs-cdn.minttang.cn/updatev3.json
V4:https://bs-cdn.minttang.cn/update.json

**Comment by g-plane** [comment]
已添加。
