### ISSUE TITLE
上传材质时发生 Unsupported operand types: float + string 严重错误

### ISSUE THREAD

**Issue by ilworkcn** [bs-community/blessing-skin-server#423]
### Blessing Skin 版本

6.0.1

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

![QQ截图20220623114603](https://user-images.githubusercontent.com/34296329/175205890-b95a77c0-a951-4594-92f4-3a1d25711ff5.png)
![QQ截图20220623115034](https://user-images.githubusercontent.com/34296329/175205898-0bb5f31b-ccfc-4f26-be7a-ffffef01afb6.png)
![QQ截图20220623115239](https://user-images.githubusercontent.com/34296329/175205904-29f0b2c6-8fe4-4ae2-8e59-2eef59b158fc.png)

### 错误日志

```text
日志过长 已上传至pastebin
https://pastebin.com/iwVEwaGw
```

### 重现步骤

上传材质时候发生错误

**Comment by mochaaP** [comment]
@ilworkcn 檢查自己 score_per_closet_item 的設定

**Comment by ilworkcn** [comment]
> 

已解决 感谢
