### ISSUE TITLE
管理员仪表板的图表卡片的字体渲染出错

### ISSUE THREAD

**Issue by Big-Cake-jpg** [bs-community/blessing-skin-server#435]
### Blessing Skin 版本

6.0.2 (commit: 2786626)

### PHP 版本

8.0

### 出现问题时所使用的浏览器

Safari

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [x] 是

### 出现了什么问题？

管理员仪表板的图表卡片，字体在黑暗模式下有一些渲染问题，即字体颜色不会改为浅色，而是保持不变。

图一会儿通过 GitHub 客户端上传，网页版老上传不上去

### 重现步骤

1. 登录管理员账号
2. 打开 https://skin.cakemc.top/admin
3. 翻到图表卡片
4. 打开暗黑模式

**Comment by Big-Cake-jpg** [comment]
![image](https://user-images.githubusercontent.com/76810494/178310746-f4a06218-f2d3-4ccf-a4fa-f282508c5b33.png)

**Comment by mochaaP** [comment]
Fixed in <https://github.com/bs-community/blessing-skin-server/commit/73e308f15aabd86508351b2ca6a20dc2d3e945d3>
