### ISSUE TITLE
添加TrustProxies.php

### ISSUE THREAD

**Issue by qibao07** [bs-community/blessing-skin-server#437]
### Blessing Skin 版本

6.0.2

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Chrome

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

添加TrustProxies.php，可参考[configuring-trusted-proxies](https://laravel.com/docs/8.x/requests#configuring-trusted-proxies)
blessing-skin本身是http的，经过nginx反向代理后转换成https。https://github.com/bs-community/blessing-skin-server/blob/5fb4240a4714937444d78671b26f60c70f3bd261/app/Http/Middleware/Authenticate.php#L13
问题就是这个地方获取地址变成http，导致浏览器跳转到http地址上。

### 重现步骤

[清除浏览器后登录会跳到http
](https://github.com/bs-community/blessing-skin-server/discussions/434)

**Comment by mochaaP** [comment]
https://github.com/bs-community/blessing-skin-plugins/tree/master/plugins/trust-proxies
