### ISSUE TITLE
请移除有关open_basedir的限制

### ISSUE THREAD

**Issue by qwq233** [bs-community/blessing-skin-server#440]
### Blessing Skin 版本

latest (manual build from git)

### PHP 版本

8.0

### 出现问题时所使用的浏览器

Chrome

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

open_basedir是一个很重要的安全措施。
本人认为，考虑到php堪忧的安全性，且只要设置妥当，完全可以正常使用(本人在注释相关代码后正常运行)，请移除该限制。

**Comment by mochaaP** [comment]
暫時不考慮。這種需求請使用 AppArmor。

以及，沒有報錯並不代表沒有出現問題。

**Comment by qwq233** [comment]
> 暫時不考慮。這種需求請使用 AppArmor。
> 
> 以及，沒有報錯並不代表沒有出現問題。

事实上我确实已经设置了，我只是认为这不是十分合理，毕竟一部分用户的配置错误不能代表大部分，这显然是一种一刀切的解决方案
![image](https://user-images.githubusercontent.com/20317838/178814410-fb026e3b-c3bc-4d9d-98d2-ce9ef28c5bcd.png)

**Comment by mochaaP** [comment]
想了一下，還是移除了環境檢查。
用戶應該為自己的環境負責。

fixed in <https://github.com/bs-community/blessing-skin-server/commit/ec790b41f1b269af7f2a70ed7d509f62054fd406>
