### ISSUE TITLE
An error occurred.

### ISSUE THREAD

**Issue by IMHFX** [bs-community/blessing-skin-server#451]
服务器系统：CentOs8
地址：192.168.1.5/setup（局域网）
浏览器：edge
服务器没有报错，也没有日志
<img width="960" alt="屏幕截图 2022-07-26 183208" src="https://user-images.githubusercontent.com/110028134/180985954-3238f91c-fa0d-49f5-80ed-8f004baef20d.png">
[nginx.conf.txt](https://github.com/bs-community/blessing-skin-manual/files/9188998/nginx.conf.txt)

**Comment by g-plane** [comment]
请仔细、认真按手册的指引进行搭建。PHP 环境搭建相关的资料请自行在其它地方搜索。

**Comment by IMHFX** [comment]
😅好像什么都说了，又好像什么都没说
