### ISSUE TITLE
插件市场无法打开

### ISSUE THREAD

**Issue by matrix-a11y** [bs-community/blessing-skin-server#456]
### Blessing Skin 版本

6.0.2

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Chrome

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

插件市场报错：Undefined array key"packages"

### 重现步骤

后台打开管理面板然后打开插件市场

**Comment by mochaaP** [comment]
duplicate of #454
