### ISSUE TITLE
【建议】提一些建议

### ISSUE THREAD

**Issue by AndyChuck** [bs-community/blessing-skin-server#46]
提一些建议，完善v4版
1. 恢复原3.5版的单角色限制插件
2. 在 普通玩家-角色管理 页面里默认显示第一个用户的皮肤，因为有一些用户看不到这么小的字
![A](https://user-images.githubusercontent.com/23419265/57076710-dd404780-6d1c-11e9-984a-05f95e7ea8c3.png)

希望开发员大大能采纳建议

**Comment by g-plane** [comment]
1. 你在平时情况下没必要进行单角色限制。因为多角色支持是 Blessing Skin 的特色；如果需要数据对接，单角色限制的功能会被自动开启。
2. 这对拥有多个角色的用户而言可能会感到奇怪，但我长期会考虑这个建议。
