### ISSUE TITLE
使用 `Yggdrasil` 插件时皮肤站 `Yggdrasil` 插件未按照预期正常工作

### ISSUE THREAD

**Issue by Krysztal112233** [bs-community/blessing-skin-server#472]
### Blessing Skin 版本

6.0.2

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Firefox

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

#### 启动器方面

在正确加载Yggdrasil地址并且正确输入用户名时提示`无法连接认证服务器，可能是网络问题。`
但是使用错误的用户却正常提示`用户xx不存在`

#### BlessingSkin与Yggdrasil插件方面

日志文件中已经成功记录错误，见下文

#### 额外描述

不仅仅是管理员用户，普通新注册的用户也产生该问题.

使用CloudFlare，并且已经根据文档中进行配置。在CloudFlare开发模式中依然产生该问题。

### 错误日志

一共产生三份日志

- [yggdrasil.log](https://paste.ubuntu.com/p/tpgTR6ZR6h/)
- [laravel.log](https://paste.ubuntu.com/p/Dqd6584mNh/)
- [HMCL's log](https://paste.ubuntu.com/p/Dz28tkPqkR/)

### 重现步骤

- 正确配置皮肤站，确认可以正常登录。
- 安装Yggdrasil插件，并且按要求配置皮肤站与HMCL。
- 产生异常。

若需要测试，则测试账号为如下
- 皮肤站地址: [OakMemory Skin](https://skin.krysztal.dev)
- 用户邮件: test123@example.com
- 用户名: test123
- 密码: 11223344

**Comment by Big-Cake-jpg** [comment]
如果是 Yggdrasil API 插件的问题，那么不应该在这个仓库提 Issue。请前往 bs-community/blessing-skin-plugins 仓库
