### ISSUE TITLE
插件市场服务器错误

### ISSUE THREAD

**Issue by Loft-xiaolen** [bs-community/blessing-skin-server#476]
### Blessing Skin 版本

v6.0.2

### PHP 版本

8.0

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Apache

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

在此之前已按照https://t.me/blessing_skin_news/781的提示进行了操作，在下载前几页的插件时是正常的，但在最后一页下载外置登录插件Yggdrasil API时显示，插件也没有成功下载。

严重错误
The GET method is not supported for this route. Supportedmethods: POST.

[1] appHttpMiddlewareDetect anguagePrefer.php#L30

[2] applHttpMiddlewareConvertEmptyStringsToNull.php#L23

然后再刷新进入插件市场时已经不能正常访问并显示

严重错误
×
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at admin@example.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

### 错误日志

```text
日志并没有纪录相关信息
```

### 重现步骤

正常下载插件，到最后一页下载外置登录插件Yggdrasil API时出错，插件也没有下载成功。

**Comment by mochaaP** [comment]
這是您伺服器的配置問題，與我們無關。
