### ISSUE TITLE
开发者选项对普通用户可见，且功能尚未完成。

### ISSUE THREAD

**Issue by Asnxthaony** [bs-community/blessing-skin-server#48]
## The Problem 问题描述

开发者选项对普通用户可见，且功能尚未完成。

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): 4.1.3
- PHP 版本 (Version of PHP): 7.3.4
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version): Nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): https://[private]/user/oauth/manage

## Error Message 错误信息

![1.png](https://i.loli.net/2019/05/04/5ccc996a39746.png)

## Steps to Reproduce 重现步骤

无

**Comment by g-plane** [comment]
功能是完成的，不知道是不是你在升级过程出了什么差错导致数据库没能成功创建表。
手动执行 `php artisan migrate` 来完成数据表的创建。

另外你说的对普通用户可见，这个功能不是管理员专属的，必然要对所有用户开放。
