### ISSUE TITLE
插件市场无法打开

### ISSUE THREAD

**Issue by zzj2039** [bs-community/blessing-skin-server#483]
### Blessing Skin 版本

6.0.2

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [X] 是

### 出现了什么问题？

打开插件市场提示致命错误：
`cURL error 35: Peer reports incompatible or unsupported protocol version. (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://git.qvq.network/bs-community/plugins-dist/-/raw/master/registry_zh_CN.json`

### 重现步骤

进入插件市场报错

**Comment by Big-Cake-jpg** [comment]
@zzj2039 请确保 PHP 使用的 OpenSSL 版本在 1.1.1 以上且已开启 TLS 1.3 支持

**Comment by zzj2039** [comment]
> @zzj2039 请确保 PHP 使用的 OpenSSL 版本在 1.1.1 以上且已开启 TLS 1.3 支持

已经确认openssl版本在1.1.1+
如何检查tls1.3是否支持？

**Comment by Big-Cake-jpg** [comment]
@zzj2039 不是服务器使用的 OpenSSL，是 PHP 使用的 OpenSSL，可以看一下 phpinfo

**Comment by zzj2039** [comment]
> @zzj2039 不是服务器使用的 OpenSSL，是 PHP 使用的 OpenSSL，可以看一下 phpinfo

![image](https://user-images.githubusercontent.com/98182517/193812594-00787acc-d46e-4fe4-b56b-7752ef4723fa.png)

**Comment by Big-Cake-jpg** [comment]
@zzj2039 应该是有 TLS 1.3 是否启用的显示项

**Comment by zzj2039** [comment]
> @zzj2039 应该是有 TLS 1.3 是否启用的显示项

![image](https://user-images.githubusercontent.com/98182517/193813236-3d9b0e87-a6e0-4bf7-a0e3-c5f30c16ad4a.png)
应该已经启用

**Comment by Jerry12228** [comment]
Hello， 所以您解决了吗？
我遇到了同样的问题……

**Comment by mochaaP** [comment]
dup of #456

**Comment by zzj2039** [comment]
@Big-Cake-jpg No, developers are not active, v3 is recommended

**Comment by mochaaP** [comment]
`php -i | grep OpenSSL`
If not above 1.1.1, reinstall PHP properly.
