### ISSUE TITLE
无法以 JWT 的方式登录皮肤站

### ISSUE THREAD

**Issue by Broken-Deer** [bs-community/blessing-skin-server#487]
### Blessing Skin 版本

6.0.2

### PHP 版本

8.0

### 出现问题时所使用的浏览器

Firefox, Chrome, Microsoft Edge

### 您正在使用的 Web Server

Apache

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

假设皮肤站的地址为https://example.com

按照“https://blessing.netlify.app/api/auth.html#%E7%99%BB%E5%BD%95”的说明，用POST方法向https://example.com/api/auth/login 发送了邮箱和用户名，得到返回值404

![image](https://user-images.githubusercontent.com/64290747/197239528-b60cec07-04d6-47af-9311-f3c28de17291.png)

### 错误日志

```text
在Chrome的Devtools中：
POST https://bs.btlcraft.top/api/auth/login 404
send	@	jquery.js:3413
ajax	@	jquery.js:3238
S.<computed>	@	jquery.js:3307
login	@	auth.js:39
onclick	@	auth:1
```

### 重现步骤

javascript中用post方法向皮肤站的 /api/auth/login 发送自己的账号和密码

下图是用了jQuery

![image](https://user-images.githubusercontent.com/64290747/197240150-6f2b126b-5232-4073-96fc-745134aedf28.png)

**Comment by Broken-Deer** [comment]
那个api的地址是不是变成其他的了

**Comment by Broken-Deer** [comment]
直接对源ip这么干会多出一行报错：

![image](https://user-images.githubusercontent.com/64290747/197311476-66ab5ad4-65d9-4fc6-8469-bb5481a2f1bf.png)

**Comment by Big-Cake-jpg** [comment]
参考 Blessing Skin News 频道，g-plane 因 `jwt-auth` 包更新过于缓慢导致其他依赖无法更新，所以移除了 JWT 登录功能。

**Comment by Broken-Deer** [comment]
好的，谢谢

**Comment by Broken-Deer** [comment]
有没有其他替代的方法实现单点登录（比如在服务器官网登录账号皮肤站也同时登录）

**Comment by Broken-Deer** [comment]
已经有个好办法实现单点登录了（虽然我感觉是自己给皮肤站造了个后门。。。
