### ISSUE TITLE
打不开了插件市场。

### ISSUE THREAD

**Issue by 2623684696** [bs-community/blessing-skin-server#492]
### Blessing Skin 版本

6.0.2

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Chrome

### 您正在使用的 Web Server

Apache

### 您正在使用宝塔吗？

- [X] 是

### 出现了什么问题？

Undefined array key "packages"
我现在一打开插件市场就会有这个问题。
翻过文档了
百度说是语法问题，但我又不敢乱动配置文件。

### 重现步骤

就打开了一下插件市场。

**Comment by Jerry12228** [comment]
#480

**Comment by 2623684696** [comment]
Ok


从 Windows 版邮件发送

发件人: Jerry
发送时间: 2022年10月29日 16:53
收件人: bs-community/blessing-skin-server
抄送: 2623684696; Author
主题: Re: [bs-community/blessing-skin-server] 打不开了插件市场。 (Issue #492)

#480
