### ISSUE TITLE
按说明修改了.env后仍无法进入插件市场

### ISSUE THREAD

**Issue by qilaoshi219** [bs-community/blessing-skin-server#516]
### Blessing Skin 版本

 v6.0.2

### PHP 版本

8.0

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [X] 是

### 出现了什么问题？

已经按照说明在.env添加了PLUGINS_REGISTRY=https://git.qvq.network/bs-community/plugins-dist/-/raw/master/registry_{lang}.json
但是仍然无法进入插件市场
![image](https://user-images.githubusercontent.com/56624923/209712933-3cfc2658-ca9a-4b9c-9a39-9c233a60abd1.png)

### 错误日志

```text
严重错误
cURL error 35: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://git.qvq.network/bs-community/plugins-dist/-/raw/master/registry_zh_CN.json
详细信息
[1] app/Http/Controllers/MarketController.php#L88
[2] app/Http/Controllers/MarketController.php#L95
[3] app/Http/Controllers/MarketController.php#L20
[4] app/Http/Middleware/CheckRole.php#L22
[5] app/Http/Middleware/FireUserAuthenticated.php#L15
[6] app/Http/Middleware/EnsureEmailFilled.php#L17
[7] app/Http/Middleware/RejectBannedUser.php#L23
[8] app/Http/Middleware/RedirectToSetup.php#L28
[9] app/Http/Middleware/EnforceEverGreen.php#L23
[10] app/Http/Middleware/DetectLanguagePrefer.php#L30
[11] app/Http/Middleware/ConvertEmptyStringsToNull.php#L23
```

### 重现步骤

更新版本后按说明在.env添加PLUGINS_REGISTRY=https://git.qvq.network/bs-community/plugins-dist/-/raw/master/registry_{lang}.json后点击插件市场即可复现

**Comment by Big-Cake-jpg** [comment]
请在 phpinfo 中确认是否启用了 PHP 的 TLS 1.3 支持

**Comment by qilaoshi219** [comment]
> 请在 phpinfo 中确认是否启用了 PHP 的 TLS 1.3 支持

如何启用php的tls1.3支持？我在搜索引擎找不到相关信息

**Comment by fred913** [comment]
> > 请在 phpinfo 中确认是否启用了 PHP 的 TLS 1.3 支持
> 
> 如何启用php的tls1.3支持？我在搜索引擎找不到相关信息

实测能找到。
[腾讯云开发者论坛上有](https://cloud.tencent.com/developer/ask/sof/1587125)

**Comment by JerrySimple** [comment]
可能是系统的 libcurl 版本太低（libcurl 从 v7.52.0 开始支持 TLS 1.3）。

**Comment by JerrySimple** [comment]
可能是系统的 libcurl 版本太低（libcurl 从 v7.52.0 开始支持 TLS 1.3）。

**Comment by hempflower** [comment]
https://github.com/bs-community/blessing-skin-server/issues/524#issuecomment-1435659134

**Comment by ghost** [comment]
我的镜像站：http://blessing-plugin.star-cloud.eu.org/1.json
在配置文件“.env”中添加如下内容：
PLUGINS_REGISTRY=http://blessing-plugin.star-cloud.eu.org/1.json
官方爬的内容

**Comment by mcmineleng** [comment]
试试这个：PLUGINS_REGISTRY=https://moeluoyu.xyz/api/plugins-dist/registry_zh_CN.json
