### ISSUE TITLE
Incompatible with PHP 8.2

### ISSUE THREAD

**Issue by Simba98** [bs-community/blessing-skin-server#517]
### Which version of Blessing Skin are you using?

v6.0.2

### Which version of PHP are you using?

8.1

### What browsers are you seeing the problem on?

Microsoft Edge

### Which web server are you using?

None

### What happened?

In PHP8.2, using ${var} in strings is deprecated
```
Throw error:
Uncaught Whoops\Exception\ErrorException: Using ${var} in strings is deprecated, use {$var} instead in /web/blessing-skin-server/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
```
In PHP8.1 it works well.
We should let users know it.

### Error Logs

```text
Symfony\Component\ErrorHandler\Error\FatalError

  Uncaught Whoops\Exception\ErrorException: Using ${var} in strings is deprecated, use {$var} instead in /web/blessing-skin-server/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
```

### Steps to Reproduce

Run blessing skin in PHP 8.2+

**Comment by g-plane** [comment]
It was fixed in latest code.
