### ISSUE TITLE
按要求修改了.env并且确认php有tls1.3支持，插件市场仍然无法

### ISSUE THREAD

**Issue by qilaoshi219** [bs-community/blessing-skin-server#519]
### Blessing Skin 版本

 v6.0.2

### PHP 版本

8.0

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [X] 是

### 出现了什么问题？

按要求修改了.env并且确认php有tls1.3支持，插件市场仍然无法进入
![image](https://user-images.githubusercontent.com/56624923/210173313-59ec4410-7b2d-4403-8876-b5c25afd772b.png)

![image](https://user-images.githubusercontent.com/56624923/210173352-b4d09b46-50e8-47ce-8f4a-51742b2ca1f4.png)
![image](https://user-images.githubusercontent.com/56624923/210173371-198a8a82-1b08-460e-b36f-54f5874365aa.png)

### 错误日志

```text
cURL error 35: Peer reports incompatible or unsupported protocol version. (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://git.qvq.network/bs-community/plugins-dist/-/raw/master/registry_zh_CN.json
详细信息
[1] app/Http/Controllers/MarketController.php#L88
[2] app/Http/Controllers/MarketController.php#L95
[3] app/Http/Controllers/MarketController.php#L20
[4] app/Http/Middleware/CheckRole.php#L22
[5] app/Http/Middleware/FireUserAuthenticated.php#L15
[6] app/Http/Middleware/EnsureEmailFilled.php#L17
[7] app/Http/Middleware/RejectBannedUser.php#L23
[8] app/Http/Middleware/RedirectToSetup.php#L28
[9] app/Http/Middleware/EnforceEverGreen.php#L23
[10] app/Http/Middleware/DetectLanguagePrefer.php#L30
[11] app/Http/Middleware/ConvertEmptyStringsToNull.php#L23
```

### 重现步骤

更新版本后按说明在.env添加PLUGINS_REGISTRY=[https://git.qvq.network/bs-community/plugins-dist/-/raw/master/registry_{lang}.json后点击插件市场即可复现

**Comment by TennousuAthena** [comment]
尝试 
```
curl https://git.qvq.network/bs-community/plugins-dist/-/raw/master/registry_zh_CN.json
```
看看能否成功
````
php -i | grep OpenSSL
````
可以查看一下openssl的版本
我在OpenSSL 3.0.5下也会出现同样的问题

**Comment by hempflower** [comment]
https://github.com/bs-community/blessing-skin-server/issues/524#issuecomment-1435659134

**Comment by ghost** [comment]
我的镜像站：http://blessing-plugin.star-cloud.eu.org/1.json
在配置文件“.env”中添加如下内容：
PLUGINS_REGISTRY=http://blessing-plugin.star-cloud.eu.org/1.json
官方爬的内容

**Comment by jdnjk** [comment]
可以试着把这一坨代码下载到本地的一处，再指向
