### ISSUE TITLE
安装最后一步SQL报错

### ISSUE THREAD

**Issue by ImJingLan** [bs-community/blessing-skin-server#529]
### Blessing Skin 版本

6.0.2

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Firefox

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [X] 是

### 出现了什么问题？

安装最后一步SQL报错

```SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes. (SQL: alter table `notifications` add index `notifications_notifiable_type_notifiable_id_index`(`notifiable_type`, `notifiable_id`)) ```

### 重现步骤

输入管理员信息后点击“开始安装”，加载片刻后报错

**Comment by CharCaius** [comment]
您使用的MySQL版本号为？

**Comment by ImJingLan** [comment]
8.1

**Comment by ImJingLan** [comment]
> 您使用的MySQL版本号为？
PHP 8.1

**Comment by CharCaius** [comment]
> > 您使用的MySQL版本号为？
> > PHP 8.1

我希望您告诉我您的数据库的版本而不是PHP的版本

**Comment by Broken-Deer** [comment]
这是MySQL的问题吧

**Comment by Minecraft-Gtb520** [comment]
我也遇到了这个问题，使用的是MYSQL5
