### ISSUE TITLE
插件市场报错

### ISSUE THREAD

**Issue by QianMo0721** [bs-community/blessing-skin-server#535]
### Blessing Skin 版本

6.0.2

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Firefox, Chrome, Safari, Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [X] 是

### 出现了什么问题？

插件市场严重报错，但是直接执行curl https://git.qvq.network/bs-community/plugins-dist/-/raw/master/registry_zh-cn.json是没问题的，php支持tls1.3 系统是centos8stream
但在Windows系统上修改env后可以正常打开

我希望更新版本修复BUG 而且这个bug貌似在v5就已经存在了 所有浏览器均以试过
![Uploading 04419C3F-68FD-48CA-9EF8-E4C8F0DF6F21.png…]()

### 重现步骤

按照置顶Issue的方法修改了.env 内的PLUGINS_REGISTRY=https://git.qvq.network/bs-community/plugins-dist/-/raw/master/registry_{lang}.json

**Comment by MoeLuoYu** [comment]
原官方插件库链接无法正常工作或提示不支持的TLS版本可以使用我的镜像站
请在配置文件“.env”中添加如下内容：
PLUGINS_REGISTRY=https://moeluoyu.xyz/api/plugins-dist/registry_zh_CN.json
注：本镜像站为纯手工更新，更新可能存在延迟，本站承诺所有镜像内容均为原版不存在任何风险代码
