### ISSUE TITLE
管理员导航栏的管理面板指向不正确

### ISSUE THREAD

**Issue by vlssu** [bs-community/blessing-skin-server#544]
### Blessing Skin 版本

1698f1162e531630b8e4f139a78c63a72c1eb9c3

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Chrome

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

管理员导航栏的管理面板指向不正确
![image](https://user-images.githubusercontent.com/43847794/218372573-fac63191-2647-4530-bbbb-83a810a5b5ab.png)

### 错误日志

```text
无
```

### 重现步骤

编译出最新开发板 1698f1162e531630b8e4f139a78c63a72c1eb9c3 并覆盖升级

**Comment by Asnxthaony** [comment]
已確認由 https://github.com/bs-community/blessing-skin-server/commit/bebdea9c206237fb4e7b8c30408bce483edc9bc4 引入此問題

系重複的路由名稱導致生成鏈接指向異常，`route()` 函數會生成出路由表中同名路由中較為靠後的一項。

備註：
可通過 `php artisan route:list --name admin.` 查看路由表

由於上述改動，「Web CLI」現可在任意頁面打開。
https://github.com/bs-community/blessing-skin-server/blob/dev/resources/assets/src/index.tsx#L9-L15

參考:
https://laravel.com/docs/7.x/upgrade#unique-route-names
https://laravel.com/docs/9.x/routing#named-routes

**Comment by vlssu** [comment]
清除 `/framework/views/twig` 缓存后暂时解决了这个问题

材质描述插件，貌似不支持开发板的更改，会导致 上传材质 页无法正常访问，找了半天才找到
