### ISSUE TITLE
点击“上传新皮肤时出现错误”

### ISSUE THREAD

**Issue by zzzdajb** [bs-community/blessing-skin-server#548]
### Blessing Skin 版本

6.0.2

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [X] 是

### 出现了什么问题？

点击“上传新皮肤”时，上传材质一页是空的。
![QQ截图20230309183845](https://user-images.githubusercontent.com/122362831/224000785-aac43b88-8f6f-4480-aa66-f6a897d29b35.png)
这个问题难以描述，所以我附上了一张图。

### 错误日志

```text
bless skin似乎并不认为这是一个错误，里面没有当天的日志。
```

### 重现步骤

1.以管理员身份登录网站。
2.点击“上传皮肤”。

**Comment by SRY-CTB** [comment]
我也这样，但感觉是部分人打不开，因为还是由资源上传的人的

**Comment by EpicNose** [comment]
我也情况相同

**Comment by graytoowolf** [comment]
是不是打开了
材质描述
