### ISSUE TITLE
安装时,使用SQL情况下,请在写入.env中添加' ' 

### ISSUE THREAD

**Issue by Illusionika** [bs-community/blessing-skin-server#552]
### Blessing Skin 版本

6.0.2

### PHP 版本

8.0

### 出现问题时所使用的浏览器

Chrome

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

我的数据库密码带有 # 井号
但是在.env中#代表注释,需要用' '把密码框起来表示是字符串

不然在安装的时候输入数据库那个页面可以通过,并把#写到.env中.让后第二步点击完成直接报错SQLSTATE[HY000] [1045] Access denied for user 

折腾半天我还以为权限炸了

### 重现步骤

使用带有#的数据库密码安装

**Comment by SRY-CTB** [comment]
反向思考一下，我们是不是可以更改数据库密码呢

**Comment by Illusionika** [comment]
> 反向思考一下，我们是不是可以更改数据库密码呢

是能改,但是让牺牲用户来本适配本身的缺陷也太...
再说这个问题修起来也简单 程序写入的时候加' '就行了

**Comment by SRY-CTB** [comment]
> > 反向思考一下，我们是不是可以更改数据库密码呢
> 
> 是能改,但是让牺牲用户来本适配本身的缺陷也太... 再说这个问题修起来也简单 程序写入的时候加' '就行了

我看装了BT，修改也简单。当然加＇＇也很简单。毕竟未完成安装，不存在任何损失。牺牲用户本身来弥补缺陷…倒也算不上😂
