### ISSUE TITLE
删除 yarn.lock

### ISSUE THREAD

**Issue by Stardito** [bs-community/blessing-skin-server#554]
### Blessing Skin 版本

6.0.2

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Chrome

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

在构建过程中，运行 yarn 命令报错，经检查，发现git仓库中存在 yarn.lock 这会导致开发者的 yarn 依赖安装记录导入到使用者的电脑中，经删除后 yarn 运行成功！

### 重现步骤

依次运行

**Comment by mochaaP** [comment]
`yarn.lock` 是**應該**且**必要**存在的，若出錯請提供您的日誌。
