### ISSUE TITLE
修正Wiki链接

### ISSUE THREAD

**Issue by Asnxthaony** [bs-community/blessing-skin-server#56]
链接列表：

# FAQ 常见问题 👈
- Wiki - 快速安装向导 - 下载安装包
- Wiki - 如何配置皮肤 Mod？
- Wiki - 游戏中不显示皮肤的可能原因。
- 报告问题的正确姿势。

# 报告问题的正确姿势
- FAQ - 常见问题[2]
- FAQ - 常见问题[3]
- FAQ - 常见问题[4]

# 快速安装向导
- FAQ - 常见问题
- Wiki - 报告问题的正确姿势
- Wiki - 如何配置皮肤 Mod

# 游戏中不显示皮肤的可能原因
- Wiki - 如何配置皮肤 Mod
- Wiki - 报告问题的正确姿势

**Comment by yushijinhun** [comment]
Fixed.
