### ISSUE TITLE
安装结束提示500 

### ISSUE THREAD

**Issue by SRY-CTB** [bs-community/blessing-skin-server#562]
### Blessing Skin 版本

6.0.2

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Chrome, Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [X] 是

### 出现了什么问题？

在6.0.2 以及 6.0.2 - 2a181c9的安装结束后提示
详细信息: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table scopes add unique，但重新刷新页面后**并无再次出现提示**，并且经过测试，所有功能都能正常工作。
"scopes_ name. unique (name ))"  scopes_ name. unique (name ))
![StarSkin](https://user-images.githubusercontent.com/88585893/236626705-a2e5d3c0-dfbd-447a-b0a9-af51bbe5dae1.png)

### 重现步骤

在不同机器上安装，依旧出现这样的问题
> 安装结束后提示 详细信息: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table scopes add unique，但重新刷新页面后**并无再次出现提示**，并且经过测试，所有功能都能正常工作。

**Comment by mochaaP** [comment]
為資料庫啟用 `innodb_large_prefix` 選項。

**Comment by SRY-CTB** [comment]
这回复也忒快了把！！！
