### ISSUE TITLE
皮肤库只能显示出第一页的内容

### ISSUE THREAD

**Issue by Broken-Deer** [bs-community/blessing-skin-server#566]
### Blessing Skin 版本

6.0.2

### PHP 版本

8.1.19

### 出现问题时所使用的浏览器

Firefox, Chrome, Safari, Microsoft Edge

### 您正在使用的 Web Server

Apache

### 您正在使用宝塔吗？

否 （我讨厌宝塔）

### 出现了什么问题？

![image](https://github.com/bs-community/blessing-skin-server/assets/64290747/26f72a17-98ba-4e40-a3f8-216390ab598e)
![image](https://github.com/bs-community/blessing-skin-server/assets/64290747/be257f99-2133-48dd-9a5a-981fce01b37c)
![image](https://github.com/bs-community/blessing-skin-server/assets/64290747/a1703c6e-c2df-4913-892a-4ab833aef7cf)

点击皮肤库下面翻页按钮后上面内容没变，始终只显示第一页的内容，返回的数据看起来也一直是第一页

### 错误日志

执行此操作时并没有出现新的错误日志

![image](https://github.com/bs-community/blessing-skin-server/assets/64290747/cf45a855-2ae4-471f-ab9f-6449a600bd08)

### 重现步骤

点击皮肤库底部的翻页按钮

**Comment by graytoowolf** [comment]
是不是用了cdn加速. 如果用了记得把参数忽略关闭.

**Comment by Broken-Deer** [comment]
谢谢！参数跟随打开后没问题了，甚至解决了之前没法换语言的问题
