### ISSUE TITLE
git.qvq.network插件registry已失效

### ISSUE THREAD

**Issue by ConstasJ** [bs-community/blessing-skin-server#570]
### Blessing Skin 版本

6.0.2

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

cURL error 7: Failed to connect to git.qvq.network port 443: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://git.qvq.network/bs-community/plugins-dist/-/raw/master/registry_zh_CN.json
（照理来说应该正常加载）

### 重现步骤

直接按照Telegram通知配置Plugin Registry，然后打开插件市场，问题出现。

**Comment by SRY-CTB** [comment]
https://github.com/bs-community/blessing-skin-server/issues/563

**Comment by mochaaP** [comment]
<https://github.com/bs-community/blessing-skin-server/issues/454#issuecomment-1204047629>
