### ISSUE TITLE
插件市场无法下载

### ISSUE THREAD

**Issue by ahmrsys** [bs-community/blessing-skin-server#571]
### Blessing Skin 版本

 6.0.2

### PHP 版本

8.0

### 出现问题时所使用的浏览器

Firefox, Chrome, Safari, Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

插件市场下载错误
cURL error 7: Failed to connect to git.qvq.network port 443: No route to host (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://git.qvq.network/bs-community/plugins-dist/-/raw/master/hitokoto_1.3.0.zip
实测 git.qvq.network 无法正常访问

### 错误日志

```text
详细信息
[1] app/Http/Controllers/MarketController.php#L66
[2] app/Http/Middleware/CheckRole.php#L22
[3] app/Http/Middleware/FireUserAuthenticated.php#L15
[4] app/Http/Middleware/EnsureEmailFilled.php#L17
[5] app/Http/Middleware/RejectBannedUser.php#L23
[6] app/Http/Middleware/RedirectToSetup.php#L28
[7] app/Http/Middleware/EnforceEverGreen.php#L23
[8] app/Http/Middleware/DetectLanguagePrefer.php#L30
[9] app/Http/Middleware/ConvertEmptyStringsToNull.php#L23
```

### 重现步骤

插件市场下载插件 出现报错

**Comment by ahmrsys** [comment]
![1](https://github.com/bs-community/blessing-skin-server/assets/77141706/3d13038c-5197-478d-8133-5c4a56136e25)

**Comment by ghost** [comment]
可以用这个 https://mcskin.mcserverx.com/zh_CN.json 我朋友的，里面用的替换了他的自建git加速 mecdn.mcserverx.com
希望官方也可以把文件更新一下

**Comment by Gu-f** [comment]
> 可以用这个 https://mcskin.mcserverx.com/zh_CN.json 我朋友的，里面用的替换了他的自建git加速 mecdn.mcserverx.com 希望官方也可以把文件更新一下

en：
Thanks for providing the CDN. Can you provide the plugin-server build/deploy/run document, It is necessary to maintain it in Project [blessing-skin-plugins](https://github.com/bs-community/blessing-skin-plugins). This is good for open source projects, It ensures that the project is still available without anyone providing the service.  
Thanks a lot.
zh：
感谢提供CDN，能否提供下plugin-server的搭建文档，或将其维护在项目[blessing-skin-plugins](https://github.com/bs-community/blessing-skin-plugins)中，这对于没有专门plugin-server的开源项目是有益的，它可以确保在没有任何人提供server的情况下，手动构建plugin-server。  
非常感谢。

**Comment by Yue-plus** [comment]
> 

https://github.com/bs-community/plugins-dist

↑直接 clone 一份这个放到 Web 服务器上应该就可以了。

**Comment by Yue-plus** [comment]
> > 可以用这个 https://mcskin.mcserverx.com/zh_CN.json 我朋友的，里面用的替换了他的自建git加速 mecdn.mcserverx.com 希望官方也可以把文件更新一下
> 
> en： Thanks for providing the CDN. Can you provide the plugin-server build/deploy/run document, It is necessary to maintain it in Project [blessing-skin-plugins](https://github.com/bs-community/blessing-skin-plugins). This is good for open source projects, It ensures that the project is still available without anyone providing the service. Thanks a lot. zh： 感谢提供CDN，能否提供下plugin-server的搭建文档，或将其维护在项目[blessing-skin-plugins](https://github.com/bs-community/blessing-skin-plugins)中，这对于没有专门plugin-server的开源项目是有益的，它可以确保在没有任何人提供server的情况下，手动构建plugin-server。 非常感谢。

https://github.com/bs-community/plugins-dist

↑直接 clone 一份这个放到 Web 服务器上应该就可以了。

**Comment by DeepAutumn114514** [comment]
SSL证书好像寄了啊啊啊啊啊啊啊啊

**Comment by mochaaP** [comment]
<https://github.com/bs-community/blessing-skin-server/issues/454#issuecomment-1204047629>

**Comment by DeepAutumn114514** [comment]
THX
