### ISSUE TITLE
处理举报时「封禁上传者」实际会封禁举报人

### ISSUE THREAD

**Issue by g-plane** [bs-community/blessing-skin-server#58]
https://github.com/bs-community/blessing-skin-server/blob/1269fdaa828201fc9b7c8053fcfc070bebdbbc3e/app/Http/Controllers/ReportController.php#L115

**Comment by kotori2** [comment]
我 举 报 我 自 己

**Comment by yushijinhun** [comment]
解 决 提 出 问 题 的 人
