### ISSUE TITLE
500 Internal Server Error报错

### ISSUE THREAD

**Issue by zoe-may** [bs-community/blessing-skin-server#586]
### Blessing Skin 版本

6.0.2

### PHP 版本

8.0

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Apache

### 您正在使用宝塔吗？

- [X] 是

### 出现了什么问题？

出现报错
`500 Internal Server Error
Details: An exception has been thrown during the rendering of a template ("filemtime(): stat failed for /www/wwwroot/skin.tdogmc.top/resources/lang/zh_CN?/front-end.yml").

`

![image](https://github.com/bs-community/blessing-skin-server/assets/71170887/ec6e8a1b-3763-48d1-99bc-5bb78a8ca044)
![image](https://github.com/bs-community/blessing-skin-server/assets/71170887/6f5928e2-e3eb-44fc-a7cc-12e69af3487d)

### 错误日志

```text
https://github.com/615303619/yun/blob/a9156b99e7659c396c90a4e972334ed933c4d9d0/laravel-2023-08-21.log
```

### 重现步骤

说实话我不大清楚发生了什么，只是在某次打开皮肤站就变成了这样，期间也没有什么特别的操作，虽然目前暂时通过重新安装修复了，但是感觉问题依旧存在

**Comment by tnqzh123** [comment]
users 表里 locale 字段最后的 `?` 删掉即可

是 Bug，不要怕.jpg

**Comment by zoe-may** [comment]
已完成
