### ISSUE TITLE
未验证邮箱的用户可以创建 OAuth2 应用

### ISSUE THREAD

**Issue by yushijinhun** [bs-community/blessing-skin-server#59]
我觉得这应该被禁止。

**Comment by g-plane** [comment]
不是特别重要、紧急的别 at 我。

**Comment by yushijinhun** [comment]
我 Google 了一阵子，并没有找到解决方法。

我的想法是，未验证邮箱的用户只是不能创建 client，但 personal-access-token 等功能还是可用的。不知 @g-plane 有何高见？
