### ISSUE TITLE
使用 [正版绑定] 插件后玩家无法使用正版进入

### ISSUE THREAD

**Issue by anxge** [bs-community/blessing-skin-server#590]
### Blessing Skin 版本

6.0.2

### PHP 版本

7.3

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [X] 是

### 出现了什么问题？

使用 [正版绑定] 插件后玩家无法使用正版进入
我希望玩家可以用正版进入并uuid相同

### 重现步骤

绑定正版-使用正版账号-无法进入服务器

**Comment by tnqzh123** [comment]
「正版绑定」插件本来就不是为了这种场景设计的。而且我也不建议这么做，搞不好就会出现玩家数据错乱的问题。

如果一定要这么做，请移步 MultiLogin 或类似方案。
