### ISSUE TITLE
关闭注册时要求填写游戏内角色名不起作用,注册依然提示需要输入用户名

### ISSUE THREAD

**Issue by lizheyo77** [bs-community/blessing-skin-server#596]
### Blessing Skin 版本

6.2

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Firefox, Chrome, Microsoft Edge

### 您正在使用的 Web Server

Apache

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

关闭注册时要求填写游戏内角色名不起作用,注册依然提示需要输入用户名

### 错误日志

```text
关闭注册时要求填写游戏内角色名不起作用,注册依然提示需要输入用户名
```

### 重现步骤

关闭注册时要求填写游戏内角色名不起作用,注册依然提示需要输入用户名

**Comment by tnqzh123** [comment]
nickname != playername

**Comment by lizheyo77** [comment]
> nickname != playername

懂了 感谢
