### ISSUE TITLE
外置登录无法连接到皮肤站

### ISSUE THREAD

**Issue by happytbs** [bs-community/blessing-skin-server#597]
### Blessing Skin 版本

6.0.2

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Firefox, Chrome, Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [X] 是

### 出现了什么问题？

搭建完皮肤组并且正确配置Yggdrasil后，使用所有启动器均报错，无法连接到皮肤站（并非本地和服务器网络问题，多次更换均无效）
![image](https://github.com/bs-community/blessing-skin-server/assets/74001578/fa19339b-92a7-4cfa-afce-348140899edb)
![image](https://github.com/bs-community/blessing-skin-server/assets/74001578/65dde7cd-45e8-4708-b0b6-deb63dead807)
（玄学的是输入错误的账户可以验证是否存在？
![image](https://github.com/bs-community/blessing-skin-server/assets/74001578/315c0ccb-69de-4d7a-94c4-ca2fd3d14153)
）

### 错误日志

```text
https://pastebin.com/tw3jk15f
yggdrasil log https://pastebin.com/reYDWZhW
```

### 重现步骤

打开启动器，添加外置登录，输入账户密码（均正确），点击启动游戏，报错
![image](https://github.com/bs-community/blessing-skin-server/assets/74001578/fa19339b-92a7-4cfa-afce-348140899edb)
![image](https://github.com/bs-community/blessing-skin-server/assets/74001578/65dde7cd-45e8-4708-b0b6-deb63dead807)

**Comment by tnqzh123** [comment]
未设定 `JWT_SECRET`

**Comment by tnqzh123** [comment]
Issue closed due to inactivity (no response).
