### ISSUE TITLE
无法进入插件市场

### ISSUE THREAD

**Issue by matrix-a11y** [bs-community/blessing-skin-server#598]
### Blessing Skin 版本

6.0.2

### PHP 版本

7.3

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

None

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

无法进入插件市场

### 错误日志

cURL error 7: Failed to connect to git.qvq.network port 443: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://git.qvq.network/bs-community/plugins-dist/-/raw/master/registry_zh_CN.json

### 重现步骤

在.env中添加PLUGINS_REGISTRY=https://git.qvq.network/bs-community/plugins-dist/-/raw/master/registry_{lang}.json后打开插件市场

**Comment by mochaaP** [comment]
<https://github.com/bs-community/blessing-skin-server/issues/454#issuecomment-1204047629>

**Comment by matrix-a11y** [comment]
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
