### ISSUE TITLE
取消设置角色模型的功能

### ISSUE THREAD

**Issue by g-plane** [bs-community/blessing-skin-server#6]
考虑到设置角色模型的功能在实际中有可能会产生误用现象，例如设置角色的模型与皮肤对应的模型不同，我们打算删除这个功能。

实现过程：
1. 从 UI 中删除相关功能及对应的测试
2. 对控制器中的代码进行修改

然而考虑到目前数据表（`players` 表）中存在 `preference`、`tid_steve` 和 `tid_alex` 字段，因此需要思考如何尽可能地能让用户平滑升级。

有两种可能的方案：
1. 保留上述三个字段。在用户设置/更新皮肤时，根据所选的皮肤来更新 `preference` 字段及 `tid_steve` 或 `tid_alex` 字段；在获取皮肤时，则像以前一样。
2. 弃用上述三个字段，然后增加新的 `tid_skin`（也可以考虑不增加 `tid_` 前缀，当然还要把 `tid_cape` 的前缀也删掉）。给这个字段设置默认值为 `-1`（原因稍后解释），用户设置皮肤时，就直接更新这个字段。
值得注意的是，我们不能在升级的过程中，根据现有的 `players` 表中那三个字段来为现有用户设置这个字段的值，因为这个过程会十分耗时（尤其像 LittleSkin 这样的大站），而且操作起来麻烦，一旦出现闪失就有可能出现数据问题。所以，我的思路是，给这个字段设置默认值为 `-1`，表示什么都没有，在种情况下，需要根据旧有的 `preference`、`tid_steve` 和 `tid_alex` 字段来写入新值；值为 `0` 表示使用默认皮肤。另外，判断是否为 `-1` 的时机是用户获取皮肤时，因为这个时候，皮肤 TID 一定会被读取，额外的工作仅仅是多了一条 `if` 判断以及在第一次时需要更新数据库，这样不会带来太大在时间损耗。

cc @yushijinhun 

---

**Edit**: 采用方案二

**Comment by printempw** [comment]
LGFM.（诈尸）

**Comment by yushijinhun** [comment]
> 因此需要思考如何尽可能地能让用户平滑升级。

可能没这个必要？既然是主版本号更新，我觉得让用户手动执行一段升级脚本也可以接受。

**Comment by g-plane** [comment]
我觉得这个脚本不好写。

**Comment by yushijinhun** [comment]
> 我觉得这个脚本不好写。

`UPDATE players SET tid_skin=IF(preference='slim',tid_alex,tid_steve) WHERE tid_skin=-1;`

大概这样。旧字段可以保留，以免出问题后数据丢失。

**Comment by g-plane** [comment]
也就是方案二与脚本都用吗？

**Comment by yushijinhun** [comment]
对。但是数据迁移一次性完成，原来的字段保留并且不作用途。
