### ISSUE TITLE
关于项目默认有关https://unpkg.com域名的css资源路径更改问题

### ISSUE THREAD

**Issue by youguo233** [bs-community/blessing-skin-server#603]
### Blessing Skin 版本

lastest

### PHP 版本

7.3

### 出现问题时所使用的浏览器

Chrome

### 您正在使用的 Web Server

None

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

我发现网站加载慢就是因为这个域名资源请求很慢，请问哪里可以配置或者更改代码呢？
我想把这些资源挂到自己的cdn上。
感谢！！！

### 重现步骤

无

**Comment by SRY-CTB** [comment]
在www/wwwroot/blessing.example/resources/views/shared部分，head.twig文件中可以修改加载的地址。若果其他地方的文件加载慢也可以修改，不一定只在/shared下。
注意：这并不是一个很好的办法，不知道升级blessing后是否会被覆盖

**Comment by youguo233** [comment]
谢谢

**Comment by shenyunuoyan** [comment]
请问这个资源文件怎么下载下来

**Comment by PonderFox0643** [comment]
> 请问这个资源文件怎么下载下来

不建议下载，我已经帮你实践过了，直接下载这个并引用后无效，建议使用国内cdn比如
```
https://cdn.bootcdn.net/ajax/libs/font-awesome/5.15.4/css/all.min.css
```
将它替换掉/resources/views/shared/head.twig 中的
```
https://unpkg.com/@fortawesome/fontawesome-free@5.15.4/css/all.min.css
```

部分，亲测有效
不过我可能引用本地的方法不对，如果有人搞出来本地化请踢我一下，我需要学习

**Comment by xqzr** [comment]
https://github.com/bs-community/blessing-skin-server/issues/410#issuecomment-1133609845

**Comment by PonderFox0643** [comment]
> [#410 （评论）](https://github.com/bs-community/blessing-skin-server/issues/410#issuecomment-1133609845)

注意一下，现在
``unpkg.com

也被墙掉了（貌似）
