### ISSUE TITLE
长时间未响应，随后抛出502 Gateway Timeout

### ISSUE THREAD

**Issue by Neuvi-llette** [bs-community/blessing-skin-server#610]
### Blessing Skin 版本

6.0.2

### PHP 版本

8.0

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [X] 是

### 出现了什么问题？

长时间未响应，随后抛出502 Gateway Timeout

### 重现步骤

新搭建一个实例然后用Edge浏览器访问

**Comment by tnqzh123** [comment]
你先想想 502 的时候你执行了什么操作

**Comment by Neuvi-llette** [comment]
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Neuvi-llette** [comment]
> 你先想想 502 的时候你执行了什么操作

未做任何操作
