### ISSUE TITLE
[500错误] TypeError Carbon\Carbon::setLastErrors(): Argument #1 ($lastErrors) must be of type array, bool given

### ISSUE THREAD

**Issue by Aigio1064** [bs-community/blessing-skin-server#617]
### Blessing Skin 版本

6.0.2 & 6.0.0

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

设置运行目录到`public`之后出现了一堆报错，问题都指向了一个叫`setLastErrors()`的玩意，我重新安装以及降级都无法解决这个问题
![image](https://github.com/bs-community/blessing-skin-server/assets/97342833/4ed383ba-9ac6-4d03-ab49-5533946a81e9)
我使用的环境如下
| k | v |
| ---: | :--- |
| 面板 | 1Panel |
| HTTP服务器 | OpenResty |
| PHP版本 | 8.2.15 |
| 浏览器 | Microsoft Edge |

## PHP扩展
```textplant
/www # php -m
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
fileinfo
filter
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
random
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
sysvsem
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]
```

## 错误日志
[laravel-2024-02-29.log](https://github.com/bs-community/blessing-skin-server/files/14443265/laravel-2024-02-29.log)

### 错误日志

```text
在上面的末尾，太长不让开issue
```

### 重现步骤

从GitHub下载压缩包
上传到服务器网站目录
全部解压到index (这是放网站文件的目录)
将 .env.example 改名为 .env
设置APP_KEY为一个长度为32的字符串
设置全部文件的用户、用户组为1000
设置运行目录为 public 并重载
访问网站

**Comment by tnqzh123** [comment]
> ### PHP 版本
> 8.1

> 我使用的环境如下
> | k | v | 
> | ---: | :--- | 
> | PHP版本 | 8.2.15 | 

你到底使用的是哪个版本的 PHP？

**Comment by Aigio1064** [comment]
> > ### PHP 版本
> > 8.1
> 
> > 我使用的环境如下
> > 
> > 
> > 
> > k
> > v
> > 
> > 
> > 
> > 
> > PHP版本
> > 8.2.15
> 
> 你到底使用的是哪个版本的 PHP？

8.2.15，因为打开issue里必须选一个PHP版本，但是没有我使用的版本

**Comment by tnqzh123** [comment]
Blessing Skin 稳定版当前不支持 PHP 8.2。请降级到 PHP 8.1，或自行编译开发版本。

**Comment by Aigio1064** [comment]
> Blessing Skin 稳定版当前不支持 PHP 8.2。请降级到 PHP 8.1，或自行编译开发版本。

行，我明白了
