### ISSUE TITLE
如何关闭验证码

### ISSUE THREAD

**Issue by xycabcd** [bs-community/blessing-skin-server#625]
### Blessing Skin 版本

a

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Firefox

### 您正在使用的 Web Server

None

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

很抱歉打扰各位，但这确实不是一个bug
想问一下要怎样修改代码才可以关闭验证码。
想给自己的服务器关闭一下

### 重现步骤

k

**Comment by tnqzh123** [comment]
No way.

而且这么做很蠢。

**Comment by xycabcd** [comment]
抱歉再次打扰，
可不可以通过修改验证码生成器，实现生成自定义邀请码之类的
（主要是因为这个验证码有点难啊，我平均要试3次）

**Comment by tnqzh123** [comment]
验证码是验证码，邀请码是邀请码。

如果你需要邀请码功能，建议在插件市场中下载对应插件。

**Comment by xycabcd** [comment]
那样的话。。。还是需要关闭验证码啊

**Comment by tnqzh123** [comment]
我不理解你为什么想关闭验证码功能，这真的很蠢，很蠢。而且邀请码和验证码不论是在功能定位还是代码实现上都不存在任何的重复和冲突。

如果是因为觉得现在的图片验证码太难，那我觉得问题不在 Blessing Skin 上。言尽于此。

如果你一定要关闭验证码功能，建议自行修改源码后构建使用。

**Comment by xycabcd** [comment]
感谢您的回复
两个问题啊。一个是为什么“很蠢，很蠢“啊，在一个，控制这部分的代码是在哪里啊

**Comment by gxres042** [comment]
> 感谢您的回复
> 两个问题啊。一个是为什么“很蠢，很蠢“啊，在一个，控制这部分的代码是在哪里啊

1. 如果你认为当下 Blessing Skin 的图片验证码很难，那确实不好说为什么；
2. 请自己搜索一下源码，相信你能找得到的。

**Comment by xycabcd** [comment]
把/app/Rules/Captcha.php 内的return $builder->testPhrase($value); 改成 return 0;
没用。。。

**Comment by xycabcd** [comment]
return 1;现在有用了。但是还是上了专业一点的reCAPTCHA单按钮版，难度为零。
