### ISSUE TITLE
未验证邮箱的用户可以使用皮肤库中的部分功能

### ISSUE THREAD

**Issue by Asnxthaony** [bs-community/blessing-skin-server#64]
## The Problem 问题描述

未验证邮箱的用户可以使用皮肤库中的部分功能
i.e 添加至衣柜、立即使用(会提示严重错误)

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): v4.2.0
- PHP 版本 (Version of PHP): 7.3.5
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version): Nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):

## Error Message 错误信息

![1](https://user-images.githubusercontent.com/12845643/58172323-dd53b780-7cca-11e9-99c8-bdcd5e72c201.png)

{
"message": "你必须验证邮箱后才能访问此页面"
}

**Comment by g-plane** [comment]
> 会提示严重错误

这不表示的确不能用嘛。

**Comment by tnqzh123** [comment]
@g-plane

> 注意看图，提示文本是以 Unicode 而不是汉字输出的

**Comment by g-plane** [comment]
我知道，这是 UX 的问题了。
