### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by happytbs** [bs-community/blessing-skin-server#654]
### Blessing Skin 版本

6.0.2

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Chrome, Microsoft Edge

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

### 出现了什么问题？

![image](https://github.com/user-attachments/assets/776eaa9f-11fe-4eec-b3ca-a6e4ac6c09ad)
log文件如下
[yggdrasil-2024-11-24.log](https://github.com/user-attachments/files/17893377/yggdrasil-2024-11-24.log)

### 重现步骤

迁移完毕皮肤站之后（数据库账户密码均一样）
打开浏览器
就遇到了

**Comment by Azusa-mikan** [comment]
这个错误表明你的应用程序无法连接到数据库服务器。具体来说，这是因为数据库连接被拒绝。

**Comment by happytbs** [comment]
已解决
