### ISSUE TITLE
上传皮肤的问题

### ISSUE THREAD

**Issue by A775566** [bs-community/blessing-skin-server#66]
## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):4.2.0
- PHP 版本 (Version of PHP):7.3.4
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version):apache
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):谷歌浏览器，http://xxx/skinlib/upload

## Error Message 错误信息

Internal Server Error

The server encountered an internal error or
misconfiguration and was unable to complete
your request.

Please contact the server administrator at 
admin@example.com to inform them of the time this error occurred,
and the actions you performed just before this error.

More information about this error may be available
in the server error log.

## Steps to Reproduce 重现步骤

报告一个问题：上传披风时，选择披风文件后就自动弹到人物皮肤上；如果再次选择披风，再点上传，就会出现500错误，如果直接用人物的方式上传披风，就成功，但是会出现人物扭曲的图像，需要去皮肤库里改……
然后有些披风是上传不了的，但是3.5版本可以。

**Comment by g-plane** [comment]
> 如果直接用人物的方式上传披风

不太懂这句话是什么意思。

**Comment by g-plane** [comment]
未收到回复，关闭。
