### ISSUE TITLE
用户可在短时间内多次签到

### ISSUE THREAD

**Issue by tnqzh123** [bs-community/blessing-skin-server#68]
这个问题在 LittleSkin 上出现。

用户点击「签到」按钮后，在等待服务器返回结果时可以多次点击「签到」，服务器会返回多条“签到成功”，并且获取的奖励积分都不一样。

**Comment by xfl03** [comment]
似乎只在前端被限制了这一行为，后端并没有做对应的更改？

**Comment by g-plane** [comment]
后端那里会先检查是否可以签到才去更新积分的。

**Comment by Asnxthaony** [comment]
@g-plane 这里 reply 会怎么样。。。
