### ISSUE TITLE
安装插件报错

### ISSUE THREAD

**Issue by gundami** [bs-community/blessing-skin-server#69]
### The Problem 问题描述

安装插件/安装更新都会报错

```
{
"message": "Server Error"
}
```

### Environment 运行环境

- Blessing Skin 版本 4.2.0
- PHP 版本 7.2
-  Web 服务器 Apache
- Google Chrome ，https://www.gundami.club/public/admin/plugins/market

 ### Error Message 错误信息
 ```
{
"message": "Server Error"
}
```

### Steps to Reproduce 重现步骤

点击安装就报错

**Comment by g-plane** [comment]
请给日志。

**Comment by tnqzh123** [comment]
虽然这应该不是出现这个问题的原因，但是你好像没有正确安装 BS？
正常情况下，`/public/` 是不应该出现在 URI 中的。

**Comment by tnqzh123** [comment]
@tnqzh123 // 他甚至…

**Comment by gundami** [comment]
@tnqzh123 public文件夹不是主目录，现在的这个站点是我从另外一条机器上迁移过来的（包括数据库）

**Comment by tnqzh123** [comment]
@gundami 但是这给你带来了安全隐患。详见上一条回复。

**Comment by tnqzh123** [comment]
另外，请提供位于 `storage/logs/laravel.log` 的日志。

在没有错误日志的情况下诊断任何问题无异于闭门造车。

**Comment by gundami** [comment]
@tnqzh123 感谢提醒，我会修改的。
以下是日志 [链接](https://gundami-1256543714.cos.ap-shanghai.myqcloud.com/laravel.log)

**Comment by g-plane** [comment]
你没有开启 ZipArchive 扩展？

**Comment by gundami** [comment]
@g-plane 确实是，迁过去时忘记安装了，问题解决了
