### ISSUE TITLE
建议增加 UserrWillBeDeleted 事件

### ISSUE THREAD

**Issue by Asnxthaony** [bs-community/blessing-skin-server#70]
触发时机
> 用户被删除之前。

type
类型：整数
含义：
* 0 —— 用户自行删除
* 1 —— 用户被管理员删除

用于阻止用户删除账号。

**Comment by g-plane** [comment]
添加这个事件倒是可以，但我不希望允许阻止用户删除账号，而且目前做不到判断是用户删除还是管理员删除。

**Comment by g-plane** [comment]
可以考虑通过插件实现。

**Comment by Asnxthaony** [comment]
@g-plane 问题已通过其他方法解决，Thanks!
