### ISSUE TITLE
关于 OAuth 的表不会被自动创建

### ISSUE THREAD

**Issue by Asnxthaony** [bs-community/blessing-skin-server#72]
## The Problem 问题描述

关于 OAuth 的表不会被自动创建
![image](https://user-images.githubusercontent.com/12845643/60396294-012fd600-9b72-11e9-8a66-6bbb82886bd3.png)
用户需要手动执行 `php artisan migrate` 来完成数据表的创建。
![image](https://user-images.githubusercontent.com/12845643/60396313-405e2700-9b72-11e9-816d-37622cdc6989.png)

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): 4.2.1
- PHP 版本 (Version of PHP): 7.3.6
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version): Apache
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): Chrome, https://skin.localhost.dev/user/oauth/manage

## Error Message 错误信息

![image](https://user-images.githubusercontent.com/12845643/60396279-db0a3600-9b71-11e9-945f-00801ec067b1.png)

## Steps to Reproduce 重现步骤

1、按照指南架设一个皮肤站
2、登录并打开 OAuth2 应用，出现严重错误。

**Comment by g-plane** [comment]
是全新安装？

**Comment by Asnxthaony** [comment]
@g-plane 全新安装

**Comment by g-plane** [comment]
已确认。

![图片](https://user-images.githubusercontent.com/17216317/60397551-db5dfd80-9b80-11e9-89c2-53f36ebca5e8.png)
