### ISSUE TITLE
适用于BS V4的CDN源

### ISSUE THREAD

**Issue by hempflower** [bs-community/blessing-skin-server#74]
## The Problem 问题描述

适用于BS V4的CDN源
```
http://bs-mirror.i-creator.cn/v4/
https://bs-mirror.i-creator.cn/v4/
```

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): 4.2.1
- PHP 版本 (Version of PHP): 不需要
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version): 不需要
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): 不需要

## Error Message 错误信息
不需要

## Steps to Reproduce 重现步骤
不需要

**Comment by g-plane** [comment]
类似这种 issue，写的时候清空这个 issue 模板就可以。

**Comment by g-plane** [comment]
加了。
