### ISSUE TITLE
当用户访问验证链接时，显示 "Invalid signature."

### ISSUE THREAD

**Issue by hempflower** [bs-community/blessing-skin-server#75]
## The Problem 问题描述
当用户访问验证链接时，显示"Invalid signature."

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): 4.2.1
- PHP 版本 (Version of PHP): 7.2
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version): Tengine 2.2.3
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): Chrome https://mcskin.i-creator.cn/auth/verify/11272?signature=2a5d04e3b9f770a6a201d281c9565865d1b5f4e6eebaf359c2b5c9892c96af94

## Error Message 错误信息

![QQ截图20190702140416](https://user-images.githubusercontent.com/22955496/60487364-4bc86400-9cd2-11e9-89bc-f2b0c609d11f.png)

(日志里没有任何有价值的信息)

## Steps to Reproduce 重现步骤

-> 注册账号
-> 收到皮肤站发送的邮件
-> 点击发送的验证链接
-> 此问题出现

**Comment by hempflower** [comment]
laravel 自带的签名url理论上不应该出这个问题啊

**Comment by g-plane** [comment]
还保留有邮件内容吗？我想看看那个链接。

**Comment by hempflower** [comment]
> 还保留有邮件内容吗？我想看看那个链接。

已写在issue中:https://mcskin.i-creator.cn/auth/verify/11272?signature=2a5d04e3b9f770a6a201d281c9565865d1b5f4e6eebaf359c2b5c9892c96af94

**Comment by g-plane** [comment]
我边是没有问题的，`expires` 参数还在：

![图片](https://user-images.githubusercontent.com/17216317/60489626-5fc29480-9cd7-11e9-984f-07b547ce88ee.png)

**Comment by g-plane** [comment]
啊不对，看错了。

**Comment by g-plane** [comment]
没发现问题：

![图片](https://user-images.githubusercontent.com/17216317/60490465-27bc5100-9cd9-11e9-8ec7-782a5f380e02.png)

**Comment by hempflower** [comment]
我发现了一个问题。
在他验证签名的地方，获取到的url地址是http://而不是https://

**Comment by g-plane** [comment]
具体是？

**Comment by hempflower** [comment]
用`$request->url()`获取到的值为`http://mcskin.i-creator.cn/auth/verify/11272`
但我是开了https的

**Comment by g-plane** [comment]
试试这个：

![图片](https://user-images.githubusercontent.com/17216317/60492612-eed2ab00-9cdd-11e9-87c0-44a7448cecc9.png)

**Comment by hempflower** [comment]
已经开启

**Comment by g-plane** [comment]
@tnqzh123 LittleSkin 有遇到过这样的问题吗？

**Comment by hempflower** [comment]
当我用字符串替换，把http改成https后，验签成功了。

**Comment by g-plane** [comment]
在哪里？

**Comment by hempflower** [comment]
`/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php`  hasValidSignature()方法

**Comment by g-plane** [comment]
https://github.com/laravel/framework/issues/28311
https://github.com/laravel/framework/issues/28941

但似乎都没有给出解决方法。

**Comment by hempflower** [comment]
我找到了这个:https://laravel.com/docs/5.8/requests#configuring-trusted-proxies

**Comment by g-plane** [comment]
但 BS 这边也没办法写死 `proxies` 选项啊。

**Comment by hempflower** [comment]
直接信任全部代理

**Comment by g-plane** [comment]
你确定这样没问题吗？

**Comment by g-plane** [comment]
我稍后以插件的形式实现好了。

**Comment by hempflower** [comment]
~~我的假期啊.....~~

**Comment by g-plane** [comment]
高三也没这么快吧？

**Comment by hempflower** [comment]
> 高三也没这么快吧？

没放暑假，是高二会考我们才有的两天假，之后学校还要把假给补回来。

**Comment by g-plane** [comment]
你是有使用负载均衡吗？

**Comment by hempflower** [comment]
我用了CDN加速

**Comment by g-plane** [comment]
先把前面的硬核修改改回来吧，以免等下影响测试。

**Comment by hempflower** [comment]
> 先把前面的硬核修改改回来吧，以免等下影响测试。

ok

**Comment by g-plane** [comment]
执行这玩意的时间我可以看一集动画……

![图片](https://user-images.githubusercontent.com/17216317/60497365-49bcd000-9ce7-11e9-9136-acbdcec6697d.png)

**Comment by tnqzh123** [comment]
@g-plane
> LittleSkin 有遇到过这样的问题吗？
我没有遇到过这种情况，也没有用户报告过类似情况

**Comment by g-plane** [comment]
@hempflower 我已经发布了，试一下？

**Comment by hempflower** [comment]
貌似没有效果。

**Comment by g-plane** [comment]
那没有办法了。

**Comment by hempflower** [comment]
问题不大。
可以考虑在未来版本使用其他方式验证。

**Comment by g-plane** [comment]
此问题已在 v5 中尝试进行修复。
