### ISSUE TITLE
第三方更新源修改

### ISSUE THREAD

**Issue by nuo12360** [bs-community/blessing-skin-server#77]
Uranium's Mirror
https://bs-mirror.r9mc.com/update.php

**Comment by tnqzh123** [comment]
建议稍后再提交更新源修改。

Blessing Skin Server 4.3.6 貌似更改了官方更新源的地址，而更新源服务端还没有更新。

**Comment by g-plane** [comment]
@nuo12360 请及时更新你的更新源。

**Comment by g-plane** [comment]
URL 还是指向官方的 Azure Repos，这没有用。

**Comment by tnqzh123** [comment]
@nuo12360 检查你的更新源服务端的 `version.txt` 和 `status.txt`，这两个文件分别是用来存储本地保存的最新的完整更新包的版本和下载状态的。

如果 `version.txt` 中的内容不是 `4.3.6` 且 `status.txt` 中的内容为 `done` 或者 `init`，请检查你的目录权限设置。需要对这两个文件赋予读写权限才可以使更新源服务端正常运作。

**Comment by g-plane** [comment]
他/她未一定用 bs-community/update-source-server？

**Comment by tnqzh123** [comment]
@g-plane
> 他/她未一定用 bs-community/update-source-server？

已修改，我看上去像是用这个的 🤔
