### ISSUE TITLE
notifications 表设计不合理

### ISSUE THREAD

**Issue by tnqzh123** [bs-community/blessing-skin-server#78]
在 BS v4.3.6 更新的「通知」功能中，（Laravel 自动生成的）`notifications` 表的设计是：每个用户每条通知生成一条记录。这个设计并不合理。

如果通知对象较多（例如 LittleSkin 的全体用户），容易因为后端处理时间过长，而导致 CDN 回源超时等问题。

**Comment by g-plane** [comment]
不是表设计不合理，是没有用上队列去发送通知。
