### ISSUE TITLE
建议在快速安装向导中列出服务器程序正确运行所需的最小权限

### ISSUE THREAD

**Issue by wangbowen1220** [bs-community/blessing-skin-server#81]
在linux中配置服务器时需要指定文件的权限。为每个文件分配完全权限是不明智的，按照laravel文档配置权限显然是不够的（实测存在一些laravel文档中未提及的但同样需要写入权限的文件）。希望开发者能给出一个所需最小权限的列表。

**Comment by g-plane** [comment]
一般来说，在安装前程序会进行检测。不知道这能否满足需求？
