### ISSUE TITLE
网站显示出现异常

### ISSUE THREAD

**Issue by cnluminous** [bs-community/blessing-skin-server#82]
## The Problem 问题描述
网站模板显示异常，并且有一行错误(仅Nginx有，Apache无)，并且已经尝试过反复安装 composer和更换Apache，

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):4.0
- PHP 版本 (Version of PHP):7.1.29
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version):Nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):http://play.cnluminous.com/

## Error Message 错误信息
Warning: file_put_contents(/www/wwwroot/play.cnluminous.com/bootstrap/../vendor/autoload.php): failed to open stream: Permission denied in /www/wwwroot/play.cnluminous.com/bootstrap/chkenv.php on line 66

![1](https://user-images.githubusercontent.com/47070284/60948987-cfafcb00-a326-11e9-84e1-e58ae4b476df.png)
![2](https://user-images.githubusercontent.com/47070284/60948999-d63e4280-a326-11e9-88d7-113eb815c6ae.png)
![3](https://user-images.githubusercontent.com/47070284/60949003-d9d1c980-a326-11e9-8384-b778b511bfb7.png)
![4](https://user-images.githubusercontent.com/47070284/60949006-db9b8d00-a326-11e9-8e52-dc5b0bcd01ed.png)

## Steps to Reproduce 重现步骤
1.下载并解压到服务器
2.更改nginx.conf
3.取消禁用函数proc_open
4.安装composer环境
5.访问后出现问题

取消禁用函数proc_open
安装composer环境

**Comment by cnluminous** [comment]
已经重复多次安装步骤

**Comment by tnqzh123** [comment]
1. 以后版本号尽量精确到修订版本
2. 从报错上来这个问题是因为你的 Web 服务器没有权限写入 `.env` 文件导致的，检查你的文件权限

**Comment by cnluminous** [comment]
请问如何构建前端文件?

**Comment by g-plane** [comment]
临时的解决方案是，给 `vendor/autoload.php` 以写入权限。

**Comment by cnluminous** [comment]
Warning: file_put_contents(/www/wwwroot/play.cnluminous.com/bootstrap/../vendor/autoload.php): failed to open stream: Permission denied in /www/wwwroot/play.cnluminous.com/bootstrap/chkenv.php on line 66
这个已经没了，就是页面无法正常显示

**Comment by g-plane** [comment]
建议直接用构建好的 release 包。

**Comment by tnqzh123** [comment]
@cnluminous

> 请问如何构建前端文件?

https://github.com/bs-community/blessing-skin-server/blob/dev/README.md#%E8%87%AA%E8%A1%8C%E6%9E%84%E5%BB%BA

如果没有特殊需求，建议直接使用构建好的稳定版 releases 包

**Comment by cnluminous** [comment]
好的我试一下

**Comment by cnluminous** [comment]
感谢，已经解决
