### ISSUE TITLE
无法显示部分图片，使用Apache，已开启PHP的GD2插件和Apache的rewrite重写模块

### ISSUE THREAD

**Issue by Carrot-Sword** [bs-community/blessing-skin-server#85]
## The Problem 问题描述
    无法以下显示图像：
        用户头像
        皮肤封面
    以下图像可以显示：
        3D的皮肤预览
        首页背景图
        皮肤站图标
    在资源管理器中进行查找，可以找到头像图片（史蒂夫）。
## Environment 运行环境
    - Blessing Skin 版本:4.4.0
    - PHP 版本 (Version of PHP):7.3.7-win32-VC15-x64
    - Web 服务器: Apache2.4
    - 浏览器:FireFox on Windows
    *备注：已开启php的gd2插件，apache的重写模块已开启

## Error Message 错误信息
    直接访问头像地址时出现的错误页面：
    
![2019-07-29](https://user-images.githubusercontent.com/45888114/62018810-d8d9dc80-b1ee-11e9-9b8d-de43860a7c65.png)

    错误信息：
       404 Not Found
       Not Found
       The requested resource /avatar/128/MzM3NTY2MDA4NEBxcS5jb20=.png?tid=1 was not found on this server.

**Comment by Carrot-Sword** [comment]
抱歉，图片好像没显示出来，重新上传一下试试？
![2019-07-29](https://user-images.githubusercontent.com/45888114/62018775-adef8880-b1ee-11e9-9a7d-d65540133078.png)

**Comment by tnqzh123** [comment]
请参考 https://github.com/printempw/blessing-skin-server/issues/46

**Comment by Carrot-Sword** [comment]
没有，那个Issues我早就看过了，我用notepad++搜索过配置文件内容，连文本“png”都找不到

**Comment by tnqzh123** [comment]
@Carrot-Sword
> 没有，那个Issues我早就看过了，我用notepad++搜索过配置文件内容，连文本“png”都找不到

我不熟悉 Apache，也不知道你的具体情况，以下内容纯属口胡，如果帮不上你还请见谅：

如果你是单独开了一个配置文件用于存放 vhost 相关的配置并将其包含在 httpd.conf 中的（大多数一键包应该都是这样），请在 httpd.conf 中检查一下有没有应用到全局的类似的内容。

皮一下，另一个说起来比做起来简单但是我认为做完了能有很大的好处的解决方案是，换用 Nginx（逃

**Comment by Carrot-Sword** [comment]
呃呃呃

**Comment by g-plane** [comment]
我觉得是 Apache 的配置问题，至于是配置的哪里有问题，我也不清楚。

**Comment by Carrot-Sword** [comment]
好吧，我已经被Apache搞得没脉了，行，换Nginx

**Comment by Carrot-Sword** [comment]
算了吧，这个问题应该没什么解决的可能了。如果明天还没人提出解决方案的话，我就把这个问题关了。

**Comment by Carrot-Sword** [comment]
nginx下载怎么这么慢啊啊啊啊啊啊！

**Comment by Carrot-Sword** [comment]
还是伟大的PanDownload好（笑
