### ISSUE TITLE
Yggdrasil API 能否在V4以上的插件库支持?

### ISSUE THREAD

**Issue by ghost** [bs-community/blessing-skin-server#87]
我测试装了4.4版本.发现最新的版本已经不支持Yggdrasil API.
我皮肤站(3.5.0)给好几位服主提供了一体化账户注册和皮肤显示.都是使用Yggdrasil API+authlib injector.
希望在新版本加回这个非常有用的功能.
我看4.4版本也已经有了正版验证绑定功能.好像在3.0版本有人提过这个authlib injector和正版登录兼容.事实上是不太可能.那么是开发者放弃了authlib injector的方案吗?

**Comment by tnqzh123** [comment]
我…无话可说

BS 本来就没有内建 Yggdrasil API，一直都是通过插件实现的

请认真查看插件市场

**Comment by Merlefloyd** [comment]
> 我…我想骂人…
> 
> BS 本来就没有内建 Yggdrasil API，一直都是通过插件实现的
> 
> 请认真查看插件市场

V4版本的市场也没有Yggdrasil API.
wiki里面标记Yggdrasil API是官方插件.
所以我觉得你可能在V4版本没有考虑要再加.
所以我觉得我在这里问也没什么不妥吧.有啥想骂人的???
我仔细看了文档也看了wiki.也看了 [#84](https://github.com/bs-community/blessing-skin-server/issues/84#issue-473154976) V5版本路线图.
只是建议开发者再加上这个插件.

**Comment by tnqzh123** [comment]
@Merlefloyd
> V4版本的市场也没有Yggdrasil API.
wiki里面标记Yggdrasil API是官方插件.
所以我觉得你可能在V4版本没有考虑要再加.
所以我觉得我在这里问也没什么不妥吧.有啥想骂人的???
我仔细看了文档也看了wiki.也看了 #84 V5版本路线图.都没有打算加回Yggdrasil API支持.
只是建议开发者再加上这个插件.

我就知道你会这么说…

我求求你，点一下插件市场里的插件列表底部的「下一页」好不好？

那么多使用 v4 的皮肤站都有提供 Yggdrasil API 好吧？

**Comment by Chenwe-i-lin** [comment]
奇 人 共 赏

**Comment by Chenwe-i-lin** [comment]
我觉得是你脑子不支持.

**Comment by hempflower** [comment]
奇 人 共 赏
