### ISSUE TITLE
插件市场错误

### ISSUE THREAD

**Issue by AFlyignPig** [bs-community/blessing-skin-server#88]
## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin): 4.4.0
- PHP 版本 (Version of PHP): 7.2
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version): apache
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL): chrome https://api.fpserver.net/admin/plugins/market

## Error Message 错误信息
undefined
mb_strtolower() expects parameter 1 to be string, array given
undefined

还有切换显示数量无效

## Steps to Reproduce 重现步骤
在搜索栏输入任意字符
按enter搜索

## 附
玩家改名的话uuid会变啊
我是bungeecord咋办

**Comment by g-plane** [comment]
请至少附上日志或截图。对于一句话的消息，我们无法解决问题。

**Comment by AFlyignPig** [comment]
![7@QQK@L$K4ESM2~LVXXJT5B](https://user-images.githubusercontent.com/42002296/62425932-69de1580-b711-11e9-8fa0-fd31e080dfaa.png)
![MVE4)4F%DVMJDF S_BXYV%N](https://user-images.githubusercontent.com/42002296/62425933-6a76ac00-b711-11e9-85fa-f81e679422a8.png)
![EI $(0`~CH}22QP1QSDI$V1](https://user-images.githubusercontent.com/42002296/62425934-6b0f4280-b711-11e9-8465-b4d3384c03e3.png)

**Comment by tnqzh123** [comment]
@AFlyignPig 

从你提供的截图里看，这不像是 4.4.0，更像是 v3？

**Comment by g-plane** [comment]
3.5 已停止提供支持。
