### ISSUE TITLE
能否添加获取头像的功能？

### ISSUE THREAD

**Issue by zsn741656478** [bs-community/blessing-skin-server#89]
想使用头像显示插件
https://www.spigotmc.org/resources/picture-login.4514/

但似乎在WIKI没找到获取头像的URL

**Comment by tnqzh123** [comment]
v4 已有内建的头像 API

访问 `/avatar/player/{size}/{name}.png` 可获取角色对应的皮肤头像，使用时把 `{size}` 换成你需要的尺寸大小、`{name}` 换成相应的角色名。

**Comment by g-plane** [comment]
问题已被回答。

**Comment by RuofengX** [comment]
新版头像api是否改为了`/avatar/player/<name>?size=<像素边长>`

**Comment by g-plane** [comment]
是的。
