### ISSUE TITLE
安装后无法访问，403错误

### ISSUE THREAD

**Issue by Timo-AL** [bs-community/blessing-skin-server#91]
## The Problem 问题描述

解压并配置 .env 后，浏览器直接访问域名 403 错误，访问 /setup 404 错误，访问 /public/index.php 提示
```
[Error] The program lacks write permission to directory < bootstrap/cache > 
[错误] 程序缺少对 < bootstrap/cache > 目录的写权限，请手动授权。
```

## Environment 运行环境

- Blessing Skin 版本：4.4.0
- PHP 版本：7.2.21
- Web 服务器：Apache
- 什么浏览器，出现错误时的地址栏 URL 是什么：没有跳转，就是输入的 URL

## Error Message 错误信息

debug 模式下也没能在 logs 中找到日志文件，尝试对所有文件设置 777 权限，也没能奏效

## Steps to Reproduce 重现步骤

在 GCP 新开 VM 实例，使用脚本 teddysun/lamp 安装 LAMP 环境，新建 vhost，下载 Blessing Skin Server 解压

**Comment by tnqzh123** [comment]
不应该将所有文件设置为 777 权限。你应该将 BS 程序根目录下的文件的所有者设置为 Apache 的运行用户。

**Comment by g-plane** [comment]
请先把 Web 根目录设置为 public 目录。

**Comment by g-plane** [comment]
未收到回复，先关闭此 issue。如果还有问题，欢迎通过以下方式联系我们：
- 加入 QQ 讨论群 573741451
- 加入 Telegram 群组 @blessing_skin
