### ISSUE TITLE
官方更新源挂了?

### ISSUE THREAD

**Issue by 10935336** [bs-community/blessing-skin-server#92]
## The Problem 问题描述
![image](https://user-images.githubusercontent.com/32383605/62850553-c9da4a80-bd15-11e9-9e0d-cd90c75d1b75.png)
我尝试直接访问
`https://dev.azure.com/blessing-skin/51010f6d-9f99-40f1-a262-0a67f788df32/_apis/git/repositories/a9ff8df7-6dc3-4ff8-bb22-4871d3a43936/Items?path=%2Fupdate.json`

显示
`{"$id":"1","innerException":null,"message":"TF401174: The item 'update.json' could not be found in the repository 'Blessing Skin Server' at the version specified by '<Branch:  >' (resolved to commit '0862c68a4119d04576ff9176b788619c88753bae')","typeName":"Microsoft.TeamFoundation.Git.Server.GitItemNotFoundException, Microsoft.TeamFoundation.Git.Server","typeKey":"GitItemNotFoundException","errorCode":0,"eventId":3000}`

尝试更换源为`https://littleskin.cn/bs-update/update.php`显示
![image](https://user-images.githubusercontent.com/32383605/62850740-68ff4200-bd16-11e9-9594-1fb082bd498c.png)

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):4.2.1
- PHP 版本 (Version of PHP):7.3.4
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version):Nginx1.16.0
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):https://10935336.moe/admin/update

**Comment by tnqzh123** [comment]
官方更新源已变更至 `https://dev.azure.com/blessing-skin/51010f6d-9f99-40f1-a262-0a67f788df32/_apis/git/repositories/a9ff8df7-6dc3-4ff8-bb22-4871d3a43936/Items?path=%2Fupdate.json`

更新版本的 BS 已经切换至新的官方更新源，如果想要从旧版本 BS 一键更新至最新版本（当前最新版本 [4.4.0](https://github.com/bs-community/blessing-skin-server/releases/tag/4.4.0)），请在 .env 文件中添加一项 `UPDATE_SOURCE` 并将值设置为你想使用的包含最新版本 BS 的更新源地址。

**Comment by 10935336** [comment]
显示
![image](https://user-images.githubusercontent.com/32383605/62852204-53404b80-bd1b-11e9-9bd7-fafc5a7b0e71.png)

**Comment by tnqzh123** [comment]
🤔那你大概就只能手动更新了

查看 [Release 页面](https://github.com/bs-community/blessing-skin-server/releases) 来获取所有可用版本，下载你想要更新到的版本后解压覆盖旧版本即可。

请注意查看你的版本和你要更新到的版本之间的各个版本的更新日志中的说明，按照说明执行其中提到的所有 Artisan 指令。

**Comment by 10935336** [comment]
真就更新程序不兼容老版本呗

**Comment by g-plane** [comment]
只是你太晚了，过了那个兼容过渡期而已。
