### ISSUE TITLE
材质反复修改可见性后，用户积分莫名减少

### ISSUE THREAD

**Issue by hempflower** [bs-community/blessing-skin-server#94]
## The Problem 问题描述
皮肤反复修改可见性后，用户积分莫名减少。

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):4.3.6
- PHP 版本 (Version of PHP):7.2
- 什么 Web 服务器，Apache 还是 Nginx (Which web server and its version):nginx
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):[https://mcskin.cn/skinlib/show/1](https://mcskin.cn/skinlib/show/1)

## Error Message 错误信息

无错误信息

## Steps to Reproduce 重现步骤

打开的材质页面，反复进行公开->隐私->公开->隐私......这样的修改。用户的积分会不断减少。经仔细观察，私有->公开后，积分增加数目似乎并未按照公开材质奖励积分进行增加。而公开->私有扣除的积分似乎也不正确。
## 积分配置页面

![配置截图](https://user-images.githubusercontent.com/22955496/63910585-f3a3a900-ca59-11e9-9fd0-92f5dd85b11d.png)

**Comment by g-plane** [comment]
@tnqzh123 LittleSkin 有遇到这种情况吗？

**Comment by tnqzh123** [comment]
@g-plane 目前没有收到类似的问题的报告（谁会闲着蛋疼这么做…）
不过应该可以试一下

**Comment by g-plane** [comment]
已经测试过了，没有问题。

**Comment by tnqzh123** [comment]
@hempflower 能不能说一下「反复」具体指多少次？我在 LittleSkin 重复了五六次，每次扣减和增加的积分都一样多。BS 版本是开发版 `5465399`（稳定版 4.3.6 最后的提交是 `2eb4f4e`，落后了大约 133 个提交，中间有发布稳定版 4.4.0，最后的提交是 `777fc23`）。

@g-plane 奖励和扣减的积分好像确实有点问题？但是不一定能被称为“错误”。已上传的材质设为私有或公开时扣减或返还的积分不是按材质详情页面显示的文件大小（向上取整？）计算的，而是根据材质文件的实际大小（？）计算的；而「上传材质」页面的预估消耗积分的计算也有错误（材质大小向下取整？四舍五入？）。

**Comment by g-plane** [comment]
1. 扣减或返还是根据材质在数据库中记录的大小进行计算，这是一个整数：
https://github.com/bs-community/blessing-skin-server/blob/3d3e48844329ba017846729aabc7846dcfa11ef2/app/Http/Controllers/SkinlibController.php#L281

2. 「上传材质」页面是四舍五入：
https://github.com/bs-community/blessing-skin-server/blob/3d3e48844329ba017846729aabc7846dcfa11ef2/resources/assets/src/views/skinlib/Upload.vue#L138
这是一个估计值，实际以后端计算为准。
https://github.com/bs-community/blessing-skin-server/blob/3d3e48844329ba017846729aabc7846dcfa11ef2/resources/lang/zh_CN/front-end.yml#L85

**Comment by hempflower** [comment]
真是一个神奇的问题。等十一假升级4.4.0看看有没有什么问题。(目前问题根源应该是当私有->公开后没有奖励公开材质积分，仅仅返还了存储费用)

**Comment by g-plane** [comment]
这个本来就没有。
