### ISSUE TITLE
无法删除插件

### ISSUE THREAD

**Issue by tnqzh123** [bs-community/blessing-skin-server#95]
## The Problem 问题描述
在「插件管理」页面中删除插件时，尽管页面提示“插件已被成功删除”，但是 plugins 目录下仍然存在这个插件的文件，并且刷新页面后也会重新识别到这个插件。

## Environment 运行环境
- Blessing Skin 开发版 `016e11b`
- PHP 7.2.16
- Chrome 76 Stable

## Error Message 错误信息
laravel.log 中没有关于这个问题的错误日志。

## Steps to Reproduce 重现步骤
在「插件管理」页面中删除插件。

**Comment by g-plane** [comment]
未能复现，请检查是否存在权限问题？

**Comment by tnqzh123** [comment]
好像确实是🤔

但是这个时候应该返回 Permission denied 吧…我这里看到的全是“插件已被成功删除”

**Comment by g-plane** [comment]
不会的，Laravel 的 `deleteDirectory` 方法在删除失败时不会抛出错误，也不会返回特别的值。

**Comment by g-plane** [comment]
相关参考：
Laravel 的实现：
https://github.com/laravel/framework/blob/5.8/src/Illuminate/Filesystem/Filesystem.php#L547-L576

PHP：
https://www.php.net/manual/zh/function.rmdir.php

https://www.php.net/manual/zh/function.unlink.php
