### ISSUE TITLE
请帮忙查看错误：页面500，权限不足，内附日志文件，运行地址。

### ISSUE THREAD

**Issue by NiKosPro** [bs-community/blessing-skin-server#98]
**问题描述**
页面500
并不是权限不足
查看了日志显示的是看不到数据库的表

**运行环境**
Blessing Skin 通过快速搭建下载的不清楚版本
谷歌浏览器
PHP7.2

**运行界面地址**
http://mc.nk0.cc:88/
我开启了APP_DEBUG
附上日志文件
[laravel-2019-09-22.log](https://github.com/bs-community/blessing-skin-server/files/3639759/laravel-2019-09-22.log)

**Comment by NiKosPro** [comment]
上面写错了，是不确定版本

**Comment by tnqzh123** [comment]
我在 Releases 页面加了说明，说了不建议直接全新安装 v5.0.0-beta1 吧？

> **请注意**：这个版本 **不是** 最新稳定版，只是 v5 版本的第一个测试版。**如果你没有一定的技术实力的话，不建议从零开始搭建。**正确的做法应该是先搭建 4.4.0 稳定版后升级到 5.0.0-beta1。你也可以在插件市场中下载并安装「使用预览版」插件（插件唯一标识符 insider）后直接在管理面板中升级。

升级完成如果还出现这个错误，请打开你的终端，进入皮肤站根目录，执行 `php artisan migrate` 指令。

**Comment by NiKosPro** [comment]
新的错误，第一次安装后正常，但是我更改数据库与authme进行关联时出现问题，误删除了users表，然后就把所有有关的表都删除了，可是我再次安装的时候提示找不到users表，他无法自动创建表了

**Comment by NiKosPro** [comment]
![QQ截图20190923141439](https://user-images.githubusercontent.com/21047590/65404812-a7574900-de0c-11e9-9ae9-170a06a4c6d0.png)

**Comment by NiKosPro** [comment]
问题已解决，我将原本的数据库删除重新新建就可以了

**Comment by NiKosPro** [comment]
找到原因了，是因为有些表没删除，但是网页上面没报出，我之前是把报出的全部删除了
