### ISSUE TITLE
无法正常更新

### ISSUE THREAD

**Issue by xixikudo** [bs-community/blessing-skin-server#99]
## The Problem 问题描述

我不小心从github.com/printempw/blessing-skin-server下载了3.5.0版本并部署了，在检查更新界面无法正常更新……在.env中填写第三方更新源也无用

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):3.5.0
- PHP 版本 (Version of PHP):7.1.32
- Web 服务器 Apache
- Chrome浏览器

**Comment by tnqzh123** [comment]
3.5.0 是 v3 的最终版本，过时的版本不再被支持。

如果你需要更新到 v4，请参阅 [Blessing Skin 用户手册 - 从 v3 升级到 v4](https://blessing.netlify.com/v3-to-v4.html#_1-%E6%9B%B4%E6%94%B9%E6%82%A8%E7%9A%84-web-%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9A%84%E6%A0%B9%E7%9B%AE%E5%BD%95)。你也可以删除整个站点（包括数据库）后重新安装 v4。

**Comment by tnqzh123** [comment]
长时间未收到回复，Close。

如果还有需要，请 Reopen 这个 Issue 并附上相关信息。
